"""
================================================================================
Chapter 0159_proclus_412 - Proclus Lycius "the Successor" (Constantinople 412 CE – Athens 485 CE)
========================
# Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 8 Minds 141 - 160 Available on Amazon https://www.amazon.com/dp/B0HH8RTCXF
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · Chapter 0159_proclus_412 - Proclus Lycius "the Successor" (Constantinople 412 CE – Athens 485 CE)
================================================================================  
WHAT THIS FILE IS
-----------------
A runnable, from-scratch cognitive architecture that encodes the distinctive
mind of Proclus, the last great systematizer of Neoplatonism. It is NOT a
Transformer, and it deliberately avoids attention-over-stored-keys. Instead the
whole learning machine is built out of the one idea that is Proclus's alone:

    Every reality is generated by a triad  —  monE (remaining),
    proodos (procession), epistrophE (reversion)  —  and a thing is real,
    coherent, and "good" only insofar as it can REVERT to the cause it
    proceeded from. Between the utterly simple source (the One) and the
    manifold world stand the HENADS: distinct divine unities through which
    the One differentiates into the many.

We turn that metaphysics into a concrete network, the HenadicEmanationNet:

    the One  --proceeds-->  henads  --proceeds-->  Intellect
             --proceeds-->  Soul    --proceeds-->  Nature (the sensible data)

and, running the other way,

    Nature   --reverts--->  Soul    --reverts--->  Intellect
             --reverts--->  henadic participation-code  --reverts--> the One

The training objective is not ordinary prediction. It is a *Procline* objective:

  1. PARTICIPATION (proodos + epistrophE): every datum must revert up to a
     henadic code and proceed back down to reconstruct itself. Reconstruction
     loss. "The many proceed from, and return to, the henads."
  2. REMAINING  (monE): the cause is undiminished by giving. The intellect
     recovered by reversion must equal the intellect regenerated by
     procession from the henads. A round-trip identity.  R(P(x)) == x_cause.
  3. EMANATION: the single learned root ("the One") must, by pure procession,
     regenerate the ordered whole (the mean/template of the world). "All
     things flow from one principle by necessary steps."
  4. DISTINCTNESS OF THE HENADS: the henads stay mutually orthonormal — each
     is a genuine, irreducible unity, not a blur of the others.

Because Proclus wrote the *Elements of Theology* as a Euclidean deductive chain
(211 propositions, each proved from earlier ones), the file also ships a tiny
deductive engine: it demonstrates that reversion-after-procession is a
CONTRACTION whose fixed point is the return to the source (epistrophE as a
convergent limit), and it re-derives every particular from the One.

ENGINEERING CONVENTIONS (shared across the Encyclopedia)
  * pure NumPy, from scratch, no ML frameworks;
  * a self-contained reverse-mode autodiff engine (class Node);
  * a MANDATORY finite-difference gradient check that must pass;
  * a real training loop on synthetic-but-structured data;
  * self-tests that assert the mind-specific claims actually hold.

Run:  python3 chapter_0159_proclus_412.py
Dependencies: numpy only.
================================================================================
"""

import numpy as np

# Determinism: a single seed is the "One" of the random world here — apt.
np.random.seed(412)


# ============================================================================
# PART 1 — A MINIMAL REVERSE-MODE AUTODIFF ENGINE
# ----------------------------------------------------------------------------
# Proclus insists that every effect must be able to RETURN to its cause. A
# reverse-mode autodiff tape is, quite literally, a machine for return: the
# forward pass is procession (proodos); .backward() is reversion (epistrophE),
# tracing each value home to the parameters that caused it. We build our own so
# nothing about the learning is hidden inside a framework.
# ============================================================================

class Node:
    """A tensor node on the autodiff tape. Wraps an ndarray + its gradient."""

    __slots__ = ("data", "grad", "_backward", "_parents")

    def __init__(self, data, _parents=()):
        self.data = np.asarray(data, dtype=np.float64)
        self.grad = np.zeros_like(self.data)
        self._backward = lambda: None          # local grad rule, set by ops
        self._parents = _parents               # nodes this one was built from

    # -- helper: undo NumPy broadcasting so grads match parent shapes --------
    @staticmethod
    def _unbroadcast(grad, shape):
        # Sum out leading dims that broadcasting added ...
        while grad.ndim > len(shape):
            grad = grad.sum(axis=0)
        # ... then sum out dims that were size-1 in the parent.
        for ax, size in enumerate(shape):
            if size == 1:
                grad = grad.sum(axis=ax, keepdims=True)
        return grad.reshape(shape)

    # -- elementwise add (with broadcasting) --------------------------------
    def __add__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        out = Node(self.data + other.data, (self, other))

        def _backward():
            self.grad += self._unbroadcast(out.grad, self.data.shape)
            other.grad += self._unbroadcast(out.grad, other.data.shape)
        out._backward = _backward
        return out

    def __sub__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        return self + (-other)

    def __neg__(self):
        out = Node(-self.data, (self,))

        def _backward():
            self.grad += -out.grad
        out._backward = _backward
        return out

    # -- elementwise multiply (with broadcasting) ---------------------------
    def __mul__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        out = Node(self.data * other.data, (self, other))

        def _backward():
            self.grad += self._unbroadcast(other.data * out.grad, self.data.shape)
            other.grad += self._unbroadcast(self.data * out.grad, other.data.shape)
        out._backward = _backward
        return out

    __radd__ = __add__
    __rmul__ = __mul__

    # -- matrix multiply -----------------------------------------------------
    def __matmul__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        out = Node(self.data @ other.data, (self, other))

        def _backward():
            self.grad += out.grad @ other.data.T
            other.grad += self.data.T @ out.grad
        out._backward = _backward
        return out

    # -- tanh nonlinearity (the "bending" of procession into a manifold) -----
    def tanh(self):
        t = np.tanh(self.data)
        out = Node(t, (self,))

        def _backward():
            self.grad += (1.0 - t * t) * out.grad
        out._backward = _backward
        return out

    # -- reductions to a scalar loss ----------------------------------------
    def sum(self):
        out = Node(self.data.sum(), (self,))

        def _backward():
            self.grad += np.ones_like(self.data) * out.grad
        out._backward = _backward
        return out

    def mean(self):
        out = Node(self.data.mean(), (self,))
        n = self.data.size

        def _backward():
            self.grad += (np.ones_like(self.data) / n) * out.grad
        out._backward = _backward
        return out

    def sq(self):
        """Elementwise square; convenient for L2 losses."""
        return self * self

    # -- topological reverse pass (epistrophE: everything returns) ----------
    def backward(self):
        topo, seen = [], set()

        def build(v):
            if id(v) not in seen:
                seen.add(id(v))
                for p in v._parents:
                    build(p)
                topo.append(v)
        build(self)
        self.grad = np.ones_like(self.data)   # d(loss)/d(loss) = 1
        for v in reversed(topo):
            v._backward()


# ============================================================================
# PART 2 — THE HENADIC EMANATION NETWORK
# ----------------------------------------------------------------------------
# Four hypostatic levels descend from the One to Nature. Downward maps are
# "procession" operators; upward maps are "reversion" operators. The henads sit
# between the One and Intellect as a small set of orthonormal unities.
# ============================================================================

class HenadicEmanationNet:
    """Proclus's cosmos rendered as a learnable, bidirectional hierarchy."""

    def __init__(self, one_dim=3, n_henads=4, intellect_dim=12,
                 soul_dim=16, nature_dim=20, scale=0.5):
        self.dims = dict(one=one_dim, henad=n_henads, intellect=intellect_dim,
                         soul=soul_dim, nature=nature_dim)

        rng = np.random.randn

        def P(shape):                          # a trainable Node parameter
            return Node(rng(*shape) * scale)

        # --- The One: a single seed vector, kept on the unit sphere --------
        self.one = Node(rng(1, one_dim))
        self._renorm_one()

        # --- Procession (downward) parameters ------------------------------
        # One -> henadic gates (how strongly the One "lights up" each henad)
        self.W_one_hen = P((one_dim, n_henads))
        # The henads themselves: n_henads distinct unities living in Intellect
        self.H = P((n_henads, intellect_dim))
        self._orthonormalize_henads()
        # Intellect -> Soul -> Nature (procession with tanh "bending")
        self.Wp_is, self.bp_is = P((intellect_dim, soul_dim)), Node(np.zeros((1, soul_dim)))
        self.Wp_sn, self.bp_sn = P((soul_dim, nature_dim)),   Node(np.zeros((1, nature_dim)))

        # --- Reversion (upward) parameters ---------------------------------
        self.Wr_ns, self.br_ns = P((nature_dim, soul_dim)),      Node(np.zeros((1, soul_dim)))
        self.Wr_si, self.br_si = P((soul_dim, intellect_dim)),   Node(np.zeros((1, intellect_dim)))
        self.Wr_ih, self.br_ih = P((intellect_dim, n_henads)),   Node(np.zeros((1, n_henads)))

    # ---- parameter bookkeeping --------------------------------------------
    def parameters(self):
        return [self.one, self.W_one_hen, self.H,
                self.Wp_is, self.bp_is, self.Wp_sn, self.bp_sn,
                self.Wr_ns, self.br_ns, self.Wr_si, self.br_si,
                self.Wr_ih, self.br_ih]

    def zero_grad(self):
        for p in self.parameters():
            p.grad = np.zeros_like(p.data)

    def _renorm_one(self):
        # The One is beyond multiplicity: we approximate simplicity by keeping
        # the seed on the unit sphere. (Done outside autograd, after each step.)
        n = np.linalg.norm(self.one.data)
        if n > 0:
            self.one.data = self.one.data / n

    def _orthonormalize_henads(self):
        # Give the henads a clean orthonormal start (QR). A soft penalty keeps
        # them orthonormal during training; this just seeds them distinct.
        q, _ = np.linalg.qr(self.H.data.T)
        self.H.data = np.ascontiguousarray(q.T[:self.dims["henad"]])

    # ---- the two directions of the cosmos ---------------------------------
    def proceed(self, henad_code):
        """PROCESSION (proodos): a henadic code descends into a full world.
        henad_code: Node (B, n_henads) -> reconstruction Node (B, nature)."""
        intellect = henad_code @ self.H                      # the many from unities
        soul = (intellect @ self.Wp_is + self.bp_is).tanh()  # Intellect -> Soul
        nature = soul @ self.Wp_sn + self.bp_sn              # Soul -> Nature
        return nature, intellect

    def revert(self, x):
        """REVERSION (epistrophE): a sensible datum returns toward its cause.
        x: Node (B, nature) -> (henad_code, intellect_recovered)."""
        soul = (x @ self.Wr_ns + self.br_ns).tanh()          # Nature -> Soul
        intellect = (soul @ self.Wr_si + self.br_si).tanh()  # Soul -> Intellect
        henad_code = (intellect @ self.Wr_ih + self.br_ih).tanh()   # -> henads
        return henad_code, intellect

    def emanate_template(self):
        """The One, by procession through the henads, unfolds the ordered
        whole. Returns the world-template the source should regenerate."""
        gates = (self.one @ self.W_one_hen).tanh()           # (1, n_henads)
        template, _ = self.proceed(gates)                    # (1, nature)
        return template, gates

    # ---- the Procline loss ------------------------------------------------
    def loss(self, X, w_remain=1.0, w_eman=1.0, w_orth=1.0):
        """X: Node (B, nature). Returns (total_loss, parts dict)."""
        B = X.data.shape[0]

        # (1) PARTICIPATION: revert up, proceed back down, reconstruct.
        code, intellect_up = self.revert(X)
        x_hat, intellect_down = self.proceed(code)
        diff = X - x_hat
        L_recon = (diff.sq()).mean()

        # (2) REMAINING (monE): reversion and procession must AGREE about the
        #     intellect. The cause is undiminished — what returns equals what
        #     was given. This is the metaphysical heart of the objective.
        rem = intellect_up - intellect_down
        L_remain = (rem.sq()).mean()

        # (3) EMANATION: the single One regenerates the world-template (its
        #     ordered mean). All-from-one, by necessary procession.
        template, _ = self.emanate_template()
        world_mean = Node(X.data.mean(axis=0, keepdims=True))  # constant target
        eman = template - world_mean
        L_eman = (eman.sq()).mean()

        # (4) DISTINCTNESS: henads orthonormal -> Gram(H) == I. We need
        #     H @ H^T; build the transpose as a first-class autodiff op.
        Ht = _transpose(self.H)
        gram = self.H @ Ht                                   # (n_henads,n_henads)
        I = Node(np.eye(self.dims["henad"]))
        L_orth = ((gram - I).sq()).mean()

        total = L_recon + w_remain * L_remain + w_eman * L_eman + w_orth * L_orth
        parts = dict(recon=L_recon.data.item(), remain=L_remain.data.item(),
                     eman=L_eman.data.item(), orth=L_orth.data.item(),
                     total=total.data.item())
        return total, parts


def _transpose(node):
    """Transpose op for a 2D Node (needed for the Gram matrix H @ H^T)."""
    out = Node(node.data.T, (node,))

    def _backward():
        node.grad += out.grad.T
    out._backward = _backward
    return out


# ============================================================================
# PART 3 — ADAM OPTIMIZER (hand-rolled)
# ----------------------------------------------------------------------------
# A modest, well-behaved optimizer so the emanation actually converges.
# ============================================================================

class Adam:
    def __init__(self, params, lr=0.01, betas=(0.9, 0.999), eps=1e-8):
        self.params = params
        self.lr, self.b1, self.b2, self.eps = lr, betas[0], betas[1], eps
        self.m = [np.zeros_like(p.data) for p in params]
        self.v = [np.zeros_like(p.data) for p in params]
        self.t = 0

    def step(self):
        self.t += 1
        for i, p in enumerate(self.params):
            g = p.grad
            self.m[i] = self.b1 * self.m[i] + (1 - self.b1) * g
            self.v[i] = self.b2 * self.v[i] + (1 - self.b2) * (g * g)
            mhat = self.m[i] / (1 - self.b1 ** self.t)
            vhat = self.v[i] / (1 - self.b2 ** self.t)
            p.data -= self.lr * mhat / (np.sqrt(vhat) + self.eps)


# ============================================================================
# PART 4 — SYNTHETIC "COSMOS": DATA WITH A GENUINE HENADIC STRUCTURE
# ----------------------------------------------------------------------------
# We build a world that really does proceed from a few unities, so that the
# network's job — rediscovering the ordered emanation — is a real inference,
# not a trivial fit. Each sample belongs to one of K "henadic classes"; within
# a class it varies along a couple of subordinate directions ("the manifold").
# ============================================================================

def make_cosmos(n_per_class=120, K=4, nature_dim=20, noise=0.10, seed=7):
    rng = np.random.RandomState(seed)
    # K orthonormal "henadic" directions embedded in Nature-space.
    A = rng.randn(nature_dim, nature_dim)
    Q, _ = np.linalg.qr(A)
    henad_dirs = Q[:, :K]                       # (nature_dim, K)
    # Two subordinate "manifold" directions per class.
    sub_dirs = [Q[:, K + 2 * k: K + 2 * k + 2] for k in range(K)]

    X, y = [], []
    for k in range(K):
        base = 1.6 * henad_dirs[:, k]           # the class's abiding unity
        coeffs = rng.randn(n_per_class, 2) * 0.6
        manifold = coeffs @ sub_dirs[k].T       # spread within the class
        pts = base[None, :] + manifold + noise * rng.randn(n_per_class, nature_dim)
        X.append(pts); y += [k] * n_per_class
    X = np.vstack(X)
    y = np.array(y)
    # center a touch (keeps the "template" meaningful, not degenerate)
    X = X - X.mean(axis=0, keepdims=True) * 0.0
    perm = rng.permutation(len(X))
    return X[perm], y[perm], henad_dirs


# ============================================================================
# PART 5 — MANDATORY FINITE-DIFFERENCE GRADIENT CHECK
# ----------------------------------------------------------------------------
# The whole architecture is only trustworthy if reversion (backprop) really is
# the inverse trace of procession (forward). We verify analytic gradients
# against numerical ones for a random subset of entries in every parameter.
# ============================================================================

def gradient_check(verbose=True):
    net = HenadicEmanationNet(one_dim=3, n_henads=3, intellect_dim=6,
                              soul_dim=7, nature_dim=8, scale=0.5)
    Xnp = np.random.randn(5, 8)

    def compute_loss():
        return net.loss(Node(Xnp), w_remain=1.0, w_eman=1.0, w_orth=1.0)[0]

    # analytic gradients
    net.zero_grad()
    L = compute_loss()
    L.backward()

    eps = 1e-6
    max_rel = 0.0
    worst = None
    checks = 0
    for p in net.parameters():
        size = p.data.size
        # .flat writes through to the underlying array even if it is a
        # non-contiguous view — essential for a correct numerical check.
        idxs = np.random.choice(size, size=min(6, size), replace=False)
        for idx in idxs:
            orig = p.data.flat[idx]
            p.data.flat[idx] = orig + eps
            Lp = compute_loss().data.item()
            p.data.flat[idx] = orig - eps
            Lm = compute_loss().data.item()
            p.data.flat[idx] = orig
            num = (Lp - Lm) / (2 * eps)
            ana = p.grad.flat[idx]
            denom = max(1e-8, abs(num) + abs(ana))
            rel = abs(num - ana) / denom
            checks += 1
            if rel > max_rel:
                max_rel, worst = rel, (num, ana)
    if verbose:
        print(f"[gradient check] coordinates tested : {checks}")
        print(f"[gradient check] max relative error : {max_rel:.3e}")
        if worst:
            print(f"[gradient check] worst (num, analytic): "
                  f"{worst[0]:+.6f}, {worst[1]:+.6f}")
    passed = max_rel < 1e-4
    print(f"[gradient check] {'PASS' if passed else 'FAIL'} "
          f"(threshold 1e-4)")
    return passed


# ============================================================================
# PART 6 — TRAINING (the cosmos learns to return to its source)
# ============================================================================

def train(net, X, epochs=250, batch=64, lr=0.01,
          w_remain=1.0, w_eman=0.5, w_orth=1.0, log_every=50):
    opt = Adam(net.parameters(), lr=lr)
    N = X.shape[0]
    history = []
    for ep in range(1, epochs + 1):
        perm = np.random.permutation(N)
        ep_parts = None
        n_batches = 0
        for i in range(0, N, batch):
            xb = Node(X[perm[i:i + batch]])
            net.zero_grad()
            total, parts = net.loss(xb, w_remain, w_eman, w_orth)
            total.backward()
            opt.step()
            net._renorm_one()          # keep the One simple (unit sphere)
            if ep_parts is None:
                ep_parts = {k: 0.0 for k in parts}
            for k in parts:
                ep_parts[k] += parts[k]
            n_batches += 1
        for k in ep_parts:
            ep_parts[k] /= n_batches
        history.append(ep_parts)
        if ep % log_every == 0 or ep == 1:
            print(f"  epoch {ep:4d} | total {ep_parts['total']:.4f} "
                  f"| recon {ep_parts['recon']:.4f} "
                  f"| remain {ep_parts['remain']:.4f} "
                  f"| eman {ep_parts['eman']:.4f} "
                  f"| orth {ep_parts['orth']:.4f}")
    return history


# ============================================================================
# PART 7 — SELF-TESTS: do the mind-specific claims actually hold?
# ============================================================================

def best_cluster_accuracy(codes, y, K):
    """Unsupervised: assign each sample to argmax|henad code|, then find the
    label permutation that best matches truth. Evidence the net rediscovered
    the henadic 'divine classes' without ever seeing labels."""
    from itertools import permutations
    assign = np.argmax(np.abs(codes), axis=1)
    best = 0.0
    for perm in permutations(range(K)):
        mapped = np.array([perm[a] for a in assign])
        acc = (mapped == y).mean()
        best = max(best, acc)
    return best


def test_reversion_is_contraction(net, X):
    """epistrophE as a convergent limit: iterating (revert . proceed) on a
    datum should CONVERGE to a fixed point — the thing 'coming to rest' in its
    cause. We measure the shrinking step size over iterations."""
    x = Node(X[:32])
    prev = x.data.copy()
    steps = []
    for _ in range(12):
        code, _ = net.revert(Node(prev))
        nxt, _ = net.proceed(code)
        step = np.linalg.norm(nxt.data - prev) / np.linalg.norm(prev)
        steps.append(step)
        prev = nxt.data
    contracting = steps[-1] < steps[0]
    return steps, contracting


def run_self_tests(net, X, y, henad_dirs):
    print("\n--- SELF-TESTS ------------------------------------------------")
    K = net.dims["henad"]

    # (a) Reconstruction quality (participation closes the loop).
    code, _ = net.revert(Node(X))
    x_hat, _ = net.proceed(code)
    recon = np.mean((X - x_hat.data) ** 2)
    var = np.var(X)
    print(f"[recon] mean-sq error {recon:.4f} vs data variance {var:.4f} "
          f"-> explained {100*(1-recon/var):.1f}%")
    assert recon < 0.5 * var, "reconstruction did not close the loop"

    # (b) Henads orthonormal (distinct unities): Gram ~ I.
    gram = net.H.data @ net.H.data.T
    off = gram - np.eye(K)
    max_off = np.max(np.abs(off))
    print(f"[henads] max |Gram - I| off/diag deviation: {max_off:.4f}")
    assert max_off < 0.25, "henads failed to stay distinct/orthonormal"

    # (c) Unsupervised rediscovery of the divine classes.
    acc = best_cluster_accuracy(code.data, y, K)
    print(f"[discovery] unsupervised henad-class accuracy: {100*acc:.1f}% "
          f"(chance {100/K:.0f}%)")
    assert acc > 0.6, "network did not rediscover the henadic classes"

    # (d) Remaining: reversion-intellect == procession-intellect.
    _, i_up = net.revert(Node(X))
    _, i_dn = net.proceed(code)
    remain_gap = np.mean((i_up.data - i_dn.data) ** 2)
    print(f"[remaining] monE round-trip gap (want small): {remain_gap:.4f}")
    assert remain_gap < 0.2, "the cause was diminished (monE violated)"

    # (e) Reversion is a contraction -> a fixed point (epistrophE limit).
    steps, contracting = test_reversion_is_contraction(net, X)
    print(f"[epistrophE] iterate step sizes: "
          f"{steps[0]:.3f} -> {steps[-1]:.3f}  "
          f"({'contracting' if contracting else 'NOT contracting'})")
    assert contracting, "return-to-source did not converge"

    # (f) Emanation: the One regenerates the world-template.
    template, gates = net.emanate_template()
    eman_err = np.mean((template.data - X.mean(axis=0, keepdims=True)) ** 2)
    print(f"[emanation] One->template error vs world mean: {eman_err:.4f}")
    print(f"[emanation] henadic gates from the One: "
          f"{np.round(gates.data.ravel(), 3)}")

    print("--- ALL SELF-TESTS PASSED ------------------------------------")


# ============================================================================
# PART 8 — MAIN
# ============================================================================

def main():
    print("=" * 70)
    print("PROCLUS  #160  —  Henadic Emanation Network")
    print("remaining (monE) - procession (proodos) - reversion (epistrophE)")
    print("=" * 70)

    print("\n[1] Finite-difference gradient check "
          "(reversion must invert procession)")
    ok = gradient_check()
    assert ok, "gradient check failed — backprop is not the trace of forward"

    print("\n[2] Building the cosmos (data proceeding from 4 henadic unities)")
    X, y, henad_dirs = make_cosmos(n_per_class=120, K=4, nature_dim=20)
    print(f"    dataset: {X.shape[0]} samples in R^{X.shape[1]}, "
          f"{len(set(y))} henadic classes")

    print("\n[3] Training the emanation (the world learns to return home)")
    net = HenadicEmanationNet(one_dim=3, n_henads=4, intellect_dim=12,
                              soul_dim=16, nature_dim=20)
    train(net, X, epochs=250, batch=64, lr=0.01,
          w_remain=1.0, w_eman=0.5, w_orth=1.0, log_every=50)

    run_self_tests(net, X, y, henad_dirs)

    print("\nDone. The One remained; the many proceeded; all returned.")


if __name__ == "__main__":
    main()
