#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
THE PROPHASIS FORECASTER
A from-scratch cognitive architecture after the method of Thucydides (c.460-c.400 BCE)
 Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
Tome 4 Minds 61 - 80 Available on Amazon https://www.amazon.com/dp/B0H71JC95Q
Resume and Interactive Demos at https://artificiology.com/
Author: David Vivancos · Chapter 0065 · Thucydides of Athens
================================================================================

WHY THIS ARCHITECTURE INSTEAD OF A TRANSFORMER
------------------------------------------------
Thucydides did not build an oracle and he did not build a chronicle. He built a
forecasting instrument. Its three load-bearing claims are:

  (1) HUMAN NATURE IS A CONSTANT (to anthropinon). Beneath the chaos of events
      lies a small, invariant basis of motives. Thucydides names three again and
      again: FEAR (deos), HONOUR (time), and INTEREST (ophelia). Everything that
      a state "feels" is some mixture of these three.  ==> a 3-dimensional
      latent BOTTLENECK. The model is forbidden from explaining behaviour with a
      large vocabulary; it must compress the world into the same three drives.

  (2) THE TRUEST CAUSE IS NOT THE STATED CAUSE. Thucydides separates the
      *alethestate prophasis* (the truest cause: the growth of Athenian power and
      the fear it inspired, 1.23) from the *aitiai kai diaphorai* (the alleged
      grievances paraded in public). A forecaster that listens to pretext will be
      fooled. So the architecture must LEARN TO DISCARD PRETEXT and keep only the
      motive signal. We test this directly (the "prophasis test").

  (3) OUTCOMES FOLLOW POWER. The Melian Dialogue (5.89): "the strong do what they
      can and the weak suffer what they must." Between two actors, the result is
      not a free function of their wishes; it is GATED BY THE POWER ASYMMETRY.
      ==> a multiplicative power gate on the forecast, not an additive feature.

  And one method-claim that ties them together:

  (4) THE FUTURE RESEMBLES THE PAST ("a possession for all time", 1.22). Because
      nature recurs, PRECEDENT predicts. ==> a RECURRENT memory carrying the
      running constellation of the conflict forward in time.

A Transformer attends over stored tokens and has no opinion about which of those
tokens are pretext and which are cause; it has no built-in three-motive prior and
no power law. None of Thucydides' four commitments are native to it. So we build
something else: a recurrent, dyadic, motive-bottleneck state-space forecaster with
a Melian power gate. Pure NumPy, hand-derived backprop-through-time, a mandatory
finite-difference gradient check, a real training loop, and self-tests that verify
the *Thucydidean* behaviours, not just that the loss goes down.

PIPELINE (one timestep t, describing a dyad of actors A vs B):
    x_t  : noisy observation of the dyad (motive signal + PRETEXT noise + sensor noise)
    p_t  : scalar log power-asymmetry between the actors (the Melian variable)
    a_t  = tanh(W1 x_t + b1)            # perception
    z_t  = W2 a_t + b2  in R^3          # THE MOTIVE BOTTLENECK (fear, honour, interest)
    h_t  = tanh(Wh h_{t-1} + Uz z_t + bh)   # PRECEDENT (the future resembles the past)
    g_t  = 1 + wp * p_t                 # MELIAN POWER GATE (multiplicative)
    k_t  = h_t * g_t
    y_t  = softmax(Wy k_t + by)         # forecast: {DETER/peace, ESCALATE/war, SUBMIT}

The label is generated by a hidden Thucydidean law (see ThucydideanWorld): war is
driven by the *latent* fear of the weaker party and the interest of the stronger,
amplified by power asymmetry; extreme asymmetry produces submission; otherwise
deterrence. The pretext channel is pure decoy. A model that scores well MUST have
recovered the motives, discarded the pretext, and learned the power law.

Run:  python3 chapter_0065_thucydides_-460.py
================================================================================
"""

import numpy as np

# A single global seed so every run is reproducible and the pasted output is real.
RNG = np.random.default_rng(46)   # 46 -> a nod to c.460 BCE


# =============================================================================
# 1. THE THUCYDIDEAN WORLD  (the data-generating process)
# -----------------------------------------------------------------------------
# This is the "Peloponnesian" simulator. It manufactures dyadic crises whose
# *visible* surface is dominated by pretext, but whose *outcomes* obey a hidden
# law of motives-times-power. The model never sees the latent motives or the law;
# it must reconstruct both from noisy observation. This is exactly the position
# of the historian in exile: present with both parties, reading surfaces, hunting
# the truest cause.
# =============================================================================

# Outcome classes (the only three things that can happen when powers collide):
DETER, ESCALATE, SUBMIT = 0, 1, 2
N_CLASSES = 3

# Latent motive dimensions:
FEAR, HONOUR, INTEREST = 0, 1, 2
N_MOTIVES = 3


class ThucydideanWorld:
    """Generates sequences of dyadic crises with a hidden motive-times-power law."""

    def __init__(self, obs_dim=12, n_pretext=6, seed=0):
        # obs_dim total observation width. Of these, the first 3 carry a (noisy,
        # rotated) image of the true motives; n_pretext of the remainder are
        # high-variance PRETEXT (the public grievances) that predict nothing; the
        # rest are low-variance sensor channels.
        self.obs_dim = obs_dim
        self.n_pretext = n_pretext
        self.rng = np.random.default_rng(seed)
        # A fixed random projection from 3 motives -> obs space (how motives "show").
        self.motive_to_obs = self.rng.standard_normal((obs_dim, N_MOTIVES)) * 0.9
        # Which observation dimensions are pretext (decoy). We place them at the tail.
        self.pretext_idx = np.arange(obs_dim - n_pretext, obs_dim)

    def _label(self, motive, p):
        """The hidden Melian law that decides the outcome of one crisis.

        motive = (fear, honour, interest) of the *tension*, each ~roughly in [-2,2]
        p      = log power-asymmetry (positive => first actor stronger)
        """
        fear, honour, interest = motive
        asym = abs(p)   # the MAGNITUDE of the power gap is the Melian variable
        # Submission when one side overwhelmingly outweighs the other and the
        # weaker side's nerve is not iron: the weak suffer what they must.
        if asym > 1.0 and fear > -0.1:
            return SUBMIT
        # War when interest, fear, honour and (crucially) the power gap all run
        # hot enough to make force tempting but not yet total.
        war_drive = 0.9 * interest + 0.7 * fear + 0.4 * honour + 0.95 * asym
        if war_drive > 1.7:
            return ESCALATE
        # Otherwise the balance holds: deterrence / uneasy peace.
        return DETER

    def sample_sequence(self, T):
        """One conflict of length T: arrays X (T,obs_dim), P (T,), Y (T,)."""
        X = np.zeros((T, self.obs_dim))
        P = np.zeros(T)
        Y = np.zeros(T, dtype=np.int64)
        # Human nature is a constant but circumstance drifts: motives random-walk
        # slowly around a fixed disposition. This is why precedent helps.
        disposition = self.rng.standard_normal(N_MOTIVES) * 0.6
        motive = disposition.copy()
        for t in range(T):
            motive = 0.85 * motive + 0.15 * disposition \
                     + self.rng.standard_normal(N_MOTIVES) * 0.5
            p = self.rng.standard_normal() * 0.9        # power asymmetry of this beat
            # Build the observation: rotated motive image + sensor noise ...
            obs = self.motive_to_obs @ motive + self.rng.standard_normal(self.obs_dim) * 0.2
            # ... then drown part of it in PRETEXT (loud, but uncorrelated with Y).
            obs[self.pretext_idx] += self.rng.standard_normal(self.n_pretext) * 2.5
            X[t] = obs
            P[t] = p
            Y[t] = self._label(motive, p)
        return X, P, Y

    def sample_batch(self, n, T):
        return [self.sample_sequence(T) for _ in range(n)]


# =============================================================================
# 2. SMALL NUMERIC HELPERS
# =============================================================================

def softmax(v):
    v = v - np.max(v)
    e = np.exp(v)
    return e / np.sum(e)


def cross_entropy(probs, target):
    return -np.log(probs[target] + 1e-12)


# =============================================================================
# 3. THE PROPHASIS FORECASTER
# -----------------------------------------------------------------------------
# A recurrent model with a deliberately tiny 3-unit motive bottleneck and a
# multiplicative Melian power gate. We implement forward, backprop-through-time,
# and parameter bookkeeping by hand so that every gradient is auditable.
# =============================================================================

class ProphasisForecaster:
    def __init__(self, obs_dim, hidden=16, mem=12, seed=0):
        rng = np.random.default_rng(seed)
        s = 0.5
        # --- perception: obs -> hidden ---
        self.W1 = rng.standard_normal((hidden, obs_dim)) * s / np.sqrt(obs_dim)
        self.b1 = np.zeros(hidden)
        # --- motive bottleneck: hidden -> 3 (fear, honour, interest) ---
        self.W2 = rng.standard_normal((N_MOTIVES, hidden)) * s / np.sqrt(hidden)
        self.b2 = np.zeros(N_MOTIVES)
        # --- precedent recurrence ---
        self.Wh = rng.standard_normal((mem, mem)) * s / np.sqrt(mem)
        self.Uz = rng.standard_normal((mem, N_MOTIVES)) * s / np.sqrt(N_MOTIVES)
        self.bh = np.zeros(mem)
        # --- Melian power gate (one multiplier per memory unit) ---
        self.wp = np.zeros(mem)
        # --- forecast head ---
        self.Wy = rng.standard_normal((N_CLASSES, mem)) * s / np.sqrt(mem)
        self.by = np.zeros(N_CLASSES)
        self.hidden, self.mem, self.obs_dim = hidden, mem, obs_dim

    # ---- parameter access as a flat dict so the grad-check can iterate ----
    def params(self):
        return {'W1': self.W1, 'b1': self.b1, 'W2': self.W2, 'b2': self.b2,
                'Wh': self.Wh, 'Uz': self.Uz, 'bh': self.bh, 'wp': self.wp,
                'Wy': self.Wy, 'by': self.by}

    def zero_grads(self):
        return {k: np.zeros_like(v) for k, v in self.params().items()}

    # ---------------------------------------------------------------------
    # FORWARD over a whole sequence. Returns total loss, the per-step caches
    # needed for backprop, and the predicted class at each step.
    # ---------------------------------------------------------------------
    def forward(self, X, P, Y=None):
        T = X.shape[0]
        cache = []
        h_prev = np.zeros(self.mem)
        loss = 0.0
        preds = np.zeros(T, dtype=np.int64)
        zs = np.zeros((T, N_MOTIVES))     # exposed motives, for the prophasis test
        for t in range(T):
            x, p = X[t], P[t]
            q = abs(p)                                 # Melian gap = |power asymmetry|
            a = np.tanh(self.W1 @ x + self.b1)         # perception
            z = self.W2 @ a + self.b2                  # MOTIVE BOTTLENECK
            h = np.tanh(self.Wh @ h_prev + self.Uz @ z + self.bh)  # PRECEDENT
            g = 1.0 + self.wp * q                      # MELIAN POWER GATE (on the gap)
            k = h * g
            logits = self.Wy @ k + self.by
            probs = softmax(logits)
            preds[t] = int(np.argmax(probs))
            zs[t] = z
            if Y is not None:
                loss += cross_entropy(probs, Y[t])
            cache.append((x, q, a, z, h_prev, h, g, k, probs))
            h_prev = h
        return loss, cache, preds, zs

    # ---------------------------------------------------------------------
    # BACKWARD (BPTT). We walk the sequence in reverse, carrying the gradient
    # of the loss w.r.t. the *next* hidden state back through the recurrence.
    # ---------------------------------------------------------------------
    def backward(self, cache, Y):
        g = self.zero_grads()
        dh_next = np.zeros(self.mem)
        for t in reversed(range(len(cache))):
            x, q, a, z, h_prev, h, gate, k, probs = cache[t]
            # softmax + cross-entropy gradient
            dlogits = probs.copy()
            dlogits[Y[t]] -= 1.0                       # 3
            g['Wy'] += np.outer(dlogits, k)
            g['by'] += dlogits
            dk = self.Wy.T @ dlogits                   # M
            # k = h * gate  -> split
            dh = dk * gate                             # via h
            dgate = dk * h                             # via gate
            g['wp'] += dgate * q                       # gate = 1 + wp*q
            # add gradient flowing back from the future timestep
            dh = dh + dh_next                          # M
            dpre_h = dh * (1.0 - h * h)                # tanh'
            g['Wh'] += np.outer(dpre_h, h_prev)
            g['bh'] += dpre_h
            g['Uz'] += np.outer(dpre_h, z)
            dh_next = self.Wh.T @ dpre_h               # to t-1
            dz = self.Uz.T @ dpre_h                    # 3
            g['W2'] += np.outer(dz, a)
            g['b2'] += dz
            da = self.W2.T @ dz                        # H
            dpre_a = da * (1.0 - a * a)                # tanh'
            g['W1'] += np.outer(dpre_a, x)
            g['b1'] += dpre_a
        return g

    def loss_only(self, X, P, Y):
        loss, _, _, _ = self.forward(X, P, Y)
        return loss


# =============================================================================
# 4. FINITE-DIFFERENCE GRADIENT CHECK  (mandatory)
# -----------------------------------------------------------------------------
# We perturb every parameter entry by +/- eps, recompute the loss, and compare
# the numerical slope with the analytic gradient. If any tensor disagrees, the
# backprop is wrong and the whole instrument is untrustworthy -- the equivalent,
# for Thucydides, of citing a source he never cross-examined.
# =============================================================================

def gradient_check(model, X, P, Y, eps=1e-5, tol=1e-4, n_probe=40):
    _, cache, _, _ = model.forward(X, P, Y)
    analytic = model.backward(cache, Y)
    worst = 0.0
    report = {}
    prng = np.random.default_rng(7)
    for name, arr in model.params().items():
        flat = arr.ravel()
        gflat = analytic[name].ravel()
        n = flat.size
        idxs = np.arange(n) if n <= n_probe else prng.choice(n, n_probe, replace=False)
        max_rel = 0.0
        for i in idxs:
            orig = flat[i]
            flat[i] = orig + eps
            lp = model.loss_only(X, P, Y)
            flat[i] = orig - eps
            lm = model.loss_only(X, P, Y)
            flat[i] = orig
            num = (lp - lm) / (2 * eps)
            ana = gflat[i]
            denom = max(1e-9, abs(num) + abs(ana))
            rel = abs(num - ana) / denom
            max_rel = max(max_rel, rel)
        report[name] = max_rel
        worst = max(worst, max_rel)
    return worst, report


# =============================================================================
# 5. TRAINING  (plain SGD with gradient clipping; clear and reproducible)
# =============================================================================

def accuracy(model, batch):
    correct = total = 0
    for X, P, Y in batch:
        _, _, preds, _ = model.forward(X, P, Y)
        correct += int(np.sum(preds == Y))
        total += len(Y)
    return correct / total


def train(model, train_batch, val_batch, epochs=60, lr=0.05, clip=5.0):
    history = []
    for ep in range(epochs):
        total_loss = 0.0
        n_steps = 0
        order = RNG.permutation(len(train_batch))
        for j in order:
            X, P, Y = train_batch[j]
            loss, cache, _, _ = model.forward(X, P, Y)
            grads = model.backward(cache, Y)
            # average over timesteps so lr is sequence-length agnostic
            scale = 1.0 / len(Y)
            gnorm = np.sqrt(sum(np.sum((g * scale) ** 2) for g in grads.values()))
            clip_factor = clip / (gnorm + 1e-9) if gnorm > clip else 1.0
            for name, P_ in model.params().items():
                P_ -= lr * clip_factor * grads[name] * scale
            total_loss += loss / len(Y)
            n_steps += 1
        if ep % 10 == 0 or ep == epochs - 1:
            tr = accuracy(model, train_batch)
            va = accuracy(model, val_batch)
            history.append((ep, total_loss / n_steps, tr, va))
            print(f"  epoch {ep:3d} | loss {total_loss / n_steps:6.3f} "
                  f"| train acc {tr:5.3f} | val acc {va:5.3f}")
    return history


# =============================================================================
# 6. THUCYDIDEAN SELF-TESTS
# -----------------------------------------------------------------------------
# These do not merely check that loss fell. They check that the model is
# Thucydidean: that it (a) computes correct gradients, (b) beats the chronicler's
# baseline, (c) hunts the truest cause and ignores pretext, and (d) obeys the
# Melian power law.
# =============================================================================

def majority_baseline(batch):
    """The naive chronicler: always predict the single most common outcome."""
    counts = np.zeros(N_CLASSES)
    for _, _, Y in batch:
        for c in range(N_CLASSES):
            counts[c] += np.sum(Y == c)
    maj = int(np.argmax(counts))
    correct = total = 0
    for _, _, Y in batch:
        correct += int(np.sum(Y == maj))
        total += len(Y)
    return correct / total, maj


def prophasis_test(model, world, n=40, T=20):
    """Does the model's motive code z track the TRUTH (motives) and ignore the
    PRETEXT? We correlate each exposed z-channel against (i) the true latent
    motive image carried in the first obs dims and (ii) the loud pretext dims.
    A Thucydidean model loads on cause and not on pretext."""
    batch = world.sample_batch(n, T)
    Zs, true_sig, pretext_sig = [], [], []
    for X, P, Y in batch:
        _, _, _, zs = model.forward(X, P, Y)
        Zs.append(zs)
        # crude proxies: norm of motive-bearing obs vs norm of pretext obs
        true_sig.append(np.linalg.norm(X[:, :N_MOTIVES], axis=1))
        pretext_sig.append(np.linalg.norm(X[:, world.pretext_idx], axis=1))
    Z = np.vstack(Zs)
    zmag = np.linalg.norm(Z, axis=1)
    true_sig = np.concatenate(true_sig)
    pretext_sig = np.concatenate(pretext_sig)

    def corr(a, b):
        a = a - a.mean(); b = b - b.mean()
        d = (np.linalg.norm(a) * np.linalg.norm(b)) + 1e-12
        return float(a @ b / d)

    return corr(zmag, true_sig), corr(zmag, pretext_sig)


def melian_test(model, world, n=120, T=16):
    """Ablate the power gate (wp := 0) and measure how much accuracy collapses on
    HIGH-asymmetry crises. If the gate matters there, the model has internalised
    'the strong do what they can; the weak suffer what they must.'"""
    batch = world.sample_batch(n, T)
    # accuracy on high-asymmetry steps only
    def acc_high(use_gate):
        saved = model.wp.copy()
        if not use_gate:
            model.wp = np.zeros_like(model.wp)
        correct = total = 0
        for X, P, Y in batch:
            _, _, preds, _ = model.forward(X, P, Y)
            mask = np.abs(P) > 1.0
            correct += int(np.sum((preds == Y) & mask))
            total += int(np.sum(mask))
        model.wp = saved
        return correct / max(1, total)
    return acc_high(True), acc_high(False)


# =============================================================================
# 7. MAIN
# =============================================================================

def main():
    print("=" * 78)
    print("THE PROPHASIS FORECASTER  --  a Thucydidean cognitive architecture")
    print("=" * 78)

    world = ThucydideanWorld(obs_dim=12, n_pretext=6, seed=11)

    # ---- (a) gradient check on a tiny instance: correctness before everything ----
    print("\n[1] FINITE-DIFFERENCE GRADIENT CHECK")
    small = ProphasisForecaster(obs_dim=12, hidden=8, mem=6, seed=3)
    Xg, Pg, Yg = world.sample_sequence(T=7)
    worst, report = gradient_check(small, Xg, Pg, Yg)
    for k, v in report.items():
        print(f"    {k:>3} : max rel err {v:.2e}")
    print(f"    WORST relative error = {worst:.2e}  "
          f"({'PASS' if worst < 1e-4 else 'FAIL'}, tol 1e-4)")
    assert worst < 1e-4, "Gradient check failed -- backprop is wrong."

    # ---- (b) build data ----
    print("\n[2] BUILDING THE PELOPONNESIAN CORPUS")
    train_batch = world.sample_batch(n=140, T=18)
    val_batch = world.sample_batch(n=40, T=18)
    base_acc, maj = majority_baseline(val_batch)
    names = {DETER: "DETER", ESCALATE: "ESCALATE", SUBMIT: "SUBMIT"}
    print(f"    train sequences: {len(train_batch)}   val sequences: {len(val_batch)}")
    print(f"    chronicler's baseline (always '{names[maj]}'): {base_acc:.3f}")

    # ---- (c) train ----
    print("\n[3] TRAINING (forecast from invariant motives, not from pretext)")
    model = ProphasisForecaster(obs_dim=12, hidden=16, mem=12, seed=1)
    train(model, train_batch, val_batch, epochs=60, lr=0.05)
    final_val = accuracy(model, val_batch)

    # ---- (d) Thucydidean self-tests ----
    print("\n[4] SELF-TESTS")
    print(f"    (i)  forecast beats baseline : {final_val:.3f} vs {base_acc:.3f}  "
          f"({'PASS' if final_val > base_acc + 0.08 else 'FAIL'})")

    c_true, c_pre = prophasis_test(model, world)
    print(f"    (ii) prophasis test          : corr(motive code, TRUE cause)   = {c_true:+.3f}")
    print(f"                                   corr(motive code, PRETEXT noise) = {c_pre:+.3f}")
    print(f"                                   ({'PASS' if abs(c_true) > abs(c_pre) + 0.15 else 'FAIL'}"
          f": loads on cause, not pretext)")

    a_gate, a_nogate = melian_test(model, world)
    print(f"    (iii) Melian power law       : high-asym acc WITH gate    = {a_gate:.3f}")
    print(f"                                   high-asym acc gate ABLATED = {a_nogate:.3f}")
    print(f"                                   ({'PASS' if a_gate > a_nogate + 0.02 else 'FAIL'}"
          f": power gate carries weight)")

    print("\n[5] SUMMARY")
    ok = (worst < 1e-4 and final_val > base_acc + 0.08
          and abs(c_true) > abs(c_pre) + 0.15 and a_gate > a_nogate + 0.02)
    print(f"    gradient check ... {'PASS' if worst < 1e-4 else 'FAIL'}")
    print(f"    forecasting   ... {'PASS' if final_val > base_acc + 0.08 else 'FAIL'}")
    print(f"    prophasis     ... {'PASS' if abs(c_true) > abs(c_pre) + 0.15 else 'FAIL'}")
    print(f"    melian        ... {'PASS' if a_gate > a_nogate + 0.02 else 'FAIL'}")
    print(f"    >>> ALL THUCYDIDEAN TESTS {'PASSED' if ok else 'FAILED'} <<<")
    print("=" * 78)
    return ok


if __name__ == "__main__":
    main()
