#!/usr/bin/env python3
"""
Encyclopedia of Lost Minds: Echoes on AI -- Mind 277
Abu Hamid Muhammad al-Ghazali (Algazel), 1058-1111 CE
# Encyclopedia of Lost Minds: Echoes on AI · Chapter 0277 · Abu Hamid Muhammad al-Ghazali (Algazel) (1058-1111)
# By David Vivancos · https://www.vivancos.com/ · https://lostmindsai.com
# Tome 14, Minds 261-280 Available on Amazon https://www.amazon.com/dp/B0HLYSVY5D
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · chapter_0277_al_ghazali_algazel_1058 - Abu Hamid Muhammad al-Ghazali (Algazel) (1058-1111)
A DOUBT-GATED NECESSITY/HABIT ARCHITECTURE, IN PURE NUMPY
===========================================================

WHAT THIS FILE IS
------------------
This is not a five-layer pipeline restating al-Ghazali's own psychology
(external senses -> internal senses -> practical/theoretical reason --
that taxonomy is Avicennan and al-Ghazali inherited most of its vocabulary
wholesale; encoding it as a stack of layers would flatter him without
being distinctively his). What follows instead computationally embodies
the one epistemological move that is his and almost no one else's:

  A learner that only accumulates statistical regularity from experience
  can never -- by inspecting that regularity alone -- tell the difference
  between a NECESSARY truth (one that could not conceivably be otherwise)
  and a HABITUAL one (a reliable custom that merely happens to have held
  so far, and that a change of circumstance can interrupt without warning).
  Treating the second kind as if it had the certainty of the first is
  exactly the "incoherence" al-Ghazali diagnosed in the philosophers: not
  that their logic was invalid, but that they had smuggled the necessity
  of mathematics into claims that were, at best, well-confirmed habit.

Three mechanisms below make that diagnosis a running, testable program:

  1. DOUBT ENGINE (tashkik) -- a bootstrap procedure that repeatedly
     re-questions the trained model against resamples of its OWN training
     distribution (never the shifted or novel data used later to grade
     it). A relation whose accuracy sits at a stable ceiling of 1.0 is
     flagged NECESSARY (darurat). A relation whose best achievable
     accuracy plateaus at a stable, non-zero remainder below 1.0 is
     flagged HABITUAL ('adah) -- a real regularity, useful, but carrying
     an irreducible margin that no amount of resampling erases.

  2. CONSOLIDATION -- once a channel is certified necessary, its weights
     are frozen (excluded from further gradient updates): settled, no
     longer up for revision. The habitual channel's weights stay plastic
     -- because a custom, unlike a necessary truth, SHOULD keep adapting
     to new experience.

  3. THE REGRESS-BREAKER (an abstention gate the optimizer cannot touch)
     -- a hard, non-learned rule, external to the training loop, that (a)
     forces "SUSPENDED" on inputs that fall outside the input distribution
     the system has ever had grounds to examine (a bounded domain of
     competence), and (b) forces "SUSPENDED" on the habitual channel the
     moment a rolling re-audit of fresh data shows its accuracy has fallen
     far outside its historical band. Point (b) is the computational
     reading of al-Ghazali's insistence, in al-Munqidh min al-Dalal, that
     the certainty which finally stopped his own regress of doubt was not
     one more argument generated by reason about itself -- reason cannot
     certify its own foundations without circularity -- but something
     that had to arrive from outside the inferential loop altogether.
     Here that "outside" is simply: a rule the gradient descent is not
     permitted to optimize away, because the whole point is that a
     system cannot be trusted to grade its own report card.

WHAT THE DEMONSTRATION AT THE BOTTOM SHOWS
-------------------------------------------
A plain model (no gate) keeps asserting the habitual relation with ~90%+
stated confidence even after the underlying regularity is deliberately
broken (a distribution shift) -- textbook epistemic overreach. The gated
system, using only a repeated, disciplined re-application of doubt to its
own ongoing experience (never a peek at the future), notices the breakage
within a few hundred examples and stops asserting -- without ever having
been told the shift occurred. The necessary channel, meanwhile, is
completely unaffected by the shift, because it never depended on the
thing that broke. Every number below is produced by running the code,
not asserted in prose.

Every parameter update is a hand-derived analytic gradient (no autodiff
library); Section 3 cross-checks every one of them against a numerical
finite-difference estimate before anything is trained.
"""

from __future__ import annotations
import numpy as np
import math, sys, time

RNG_SEED = 1058  # al-Ghazali's birth year, used only as a memorable seed

# ---------------------------------------------------------------------------
# 1. SYNTHETIC EPISTEMIC ENVIRONMENT
# ---------------------------------------------------------------------------
# Every input x has three feature blocks (12 dims total, values in {-1,+1}):
#   core[0:4]   -> a NECESSARY relation: y_necessary = parity(core) (XOR)
#                  This relation is a fixed logical function: no resampling
#                  of any other feature ever changes it, and it is NEVER
#                  contaminated by label noise -- it is true in every trial,
#                  without exception, by construction.
#   habit[4:8]  -> a HABITUAL relation: y_habit_true = parity(habit[0:2])
#                  but the observed label is flipped with probability
#                  (1 - p_custom) by a hidden "confound" z. In the normal
#                  regime p_custom = 0.92 (a strong, useful, everyday
#                  regularity -- fire usually burns cotton). Under a later
#                  distribution shift, p_custom collapses to 0.5 (chance):
#                  the "habit" (al-Ghazali's 'adah) is interrupted.
#   noise[8:12] -> pure distractor bits, causally irrelevant to either label.
def generate_environment(n, seed, shift=False, novelty=False):
    rng = np.random.default_rng(seed)
    if novelty:
        # Out-of-support inputs: continuous, large-magnitude, never seen in training.
        X = rng.normal(loc=0.0, scale=6.0, size=(n, 12))
        yN = np.zeros(n)  # undefined / unused for novelty probes
        yH = np.zeros(n)
        return X.astype(np.float64), yN, yH

    core = rng.integers(0, 2, size=(n, 4))
    habit = rng.integers(0, 2, size=(n, 4))
    noise = rng.integers(0, 2, size=(n, 4))

    y_necessary = np.bitwise_xor.reduce(core, axis=1).astype(np.float64)

    p_custom = 0.5 if shift else 0.92
    y_habit_true = np.bitwise_xor(habit[:, 0], habit[:, 1]).astype(np.float64)
    z = rng.random(n) < p_custom
    y_habit = np.where(z, y_habit_true, 1.0 - y_habit_true)

    X01 = np.concatenate([core, habit, noise], axis=1).astype(np.float64)
    X = X01 * 2.0 - 1.0  # map {0,1} -> {-1,+1}
    return X, y_necessary, y_habit


# ---------------------------------------------------------------------------
# 2. THE TRUNK + TWO HEADS  (hand-rolled MLP, no autodiff framework)
# ---------------------------------------------------------------------------
def init_params(rng, d_in=12, d_hid=16):
    def he(shape, fan_in):
        return rng.normal(0, math.sqrt(2.0 / fan_in), size=shape)
    P = {
        "W1": he((d_in, d_hid), d_in), "b1": np.zeros(d_hid),
        "W2": he((d_hid, d_hid), d_hid), "b2": np.zeros(d_hid),
        "Wn": he((d_hid, 1), d_hid), "bn": np.zeros(1),
        "Wh": he((d_hid, 1), d_hid), "bh": np.zeros(1),
    }
    return P


def sigmoid(z):
    return 1.0 / (1.0 + np.exp(-np.clip(z, -30, 30)))


def forward(P, X):
    z1 = X @ P["W1"] + P["b1"]
    a1 = np.tanh(z1)                       # Layer "internal senses": common-sense integration
    z2 = a1 @ P["W2"] + P["b2"]
    a2 = np.maximum(z2, 0.0)               # Layer "estimation" (wahm): nonlinear feature combination
    zn = a2 @ P["Wn"] + P["bn"]
    zh = a2 @ P["Wh"] + P["bh"]
    pn = sigmoid(zn).ravel()
    ph = sigmoid(zh).ravel()
    cache = dict(X=X, z1=z1, a1=a1, z2=z2, a2=a2, zn=zn, zh=zh, pn=pn, ph=ph)
    return pn, ph, cache


def bce(p, y, eps=1e-9):
    p = np.clip(p, eps, 1 - eps)
    return -(y * np.log(p) + (1 - y) * np.log(1 - p))


def loss_fn(P, X, yN, yH, wN=1.0, wH=1.0):
    pn, ph, cache = forward(P, X)
    ln = bce(pn, yN).mean()
    lh = bce(ph, yH).mean()
    return wN * ln + wH * lh, cache, pn, ph


def backward(P, cache, yN, yH, wN=1.0, wH=1.0):
    """Manually-derived gradients for the BCE + tanh/relu MLP above."""
    X, a1, a2 = cache["X"], cache["a1"], cache["a2"]
    z1 = cache["z1"]
    pn, ph = cache["pn"], cache["ph"]
    n = X.shape[0]

    # dL/dz for each sigmoid-BCE head is simply (p - y)/n  (classic identity)
    dzn = wN * (pn - yN).reshape(-1, 1) / n
    dzh = wH * (ph - yH).reshape(-1, 1) / n

    grads = {}
    grads["Wn"] = a2.T @ dzn
    grads["bn"] = dzn.sum(axis=0)
    grads["Wh"] = a2.T @ dzh
    grads["bh"] = dzh.sum(axis=0)

    da2 = dzn @ P["Wn"].T + dzh @ P["Wh"].T
    dz2 = da2 * (cache["z2"] > 0).astype(np.float64)   # relu'
    grads["W2"] = a1.T @ dz2
    grads["b2"] = dz2.sum(axis=0)

    da1 = dz2 @ P["W2"].T
    dz1 = da1 * (1.0 - np.tanh(z1) ** 2)                 # tanh'
    grads["W1"] = X.T @ dz1
    grads["b1"] = dz1.sum(axis=0)

    return grads


# ---------------------------------------------------------------------------
# 3. MANDATORY FINITE-DIFFERENCE GRADIENT CHECK
# ---------------------------------------------------------------------------
def gradient_check(P, X, yN, yH, n_probe=25, eps=1e-5, tol=2e-3, seed=0):
    rng = np.random.default_rng(seed)
    _, cache, _, _ = loss_fn(P, X, yN, yH)
    analytic = backward(P, cache, yN, yH)
    max_rel_err = 0.0
    checked = 0
    for name in P:
        flat = P[name].ravel()
        g_flat = analytic[name].ravel()
        idxs = rng.integers(0, flat.size, size=min(n_probe, flat.size))
        for idx in idxs:
            orig = flat[idx]
            flat[idx] = orig + eps
            l_plus, _, _, _ = loss_fn(P, X, yN, yH)
            flat[idx] = orig - eps
            l_minus, _, _, _ = loss_fn(P, X, yN, yH)
            flat[idx] = orig
            numeric = (l_plus - l_minus) / (2 * eps)
            denom = max(abs(numeric), abs(g_flat[idx]), 1e-8)
            rel_err = abs(numeric - g_flat[idx]) / denom
            max_rel_err = max(max_rel_err, rel_err)
            checked += 1
    return max_rel_err, checked


# ---------------------------------------------------------------------------
# 4. ADAM OPTIMIZER + TRAINING LOOP (with optional frozen/consolidated params)
# ---------------------------------------------------------------------------
def init_adam_state(P):
    return {k: {"m": np.zeros_like(v), "v": np.zeros_like(v), "t": 0} for k, v in P.items()}


def adam_step(P, grads, state, lr=0.03, b1=0.9, b2=0.999, eps=1e-8, frozen=frozenset()):
    for k in P:
        if k in frozen:
            continue                      # consolidated / self-evident: no longer revised
        s = state[k]
        s["t"] += 1
        s["m"] = b1 * s["m"] + (1 - b1) * grads[k]
        s["v"] = b2 * s["v"] + (1 - b2) * (grads[k] ** 2)
        mhat = s["m"] / (1 - b1 ** s["t"])
        vhat = s["v"] / (1 - b2 ** s["t"])
        P[k] -= lr * mhat / (np.sqrt(vhat) + eps)


def train(P, X, yN, yH, epochs=400, lr=0.03, batch=128, seed=0, frozen=frozenset(), verbose=False):
    rng = np.random.default_rng(seed)
    state = init_adam_state(P)
    history = []
    n = X.shape[0]
    for ep in range(epochs):
        idx = rng.permutation(n)
        ep_loss = 0.0
        for start in range(0, n, batch):
            b_idx = idx[start:start + batch]
            loss, cache, _, _ = loss_fn(P, X[b_idx], yN[b_idx], yH[b_idx])
            grads = backward(P, cache, yN[b_idx], yH[b_idx])
            adam_step(P, grads, state, lr=lr, frozen=frozen)
            ep_loss += loss * len(b_idx)
        history.append(ep_loss / n)
        if verbose and ep % 50 == 0:
            print(f"  epoch {ep:4d}  loss {history[-1]:.4f}")
    return history


# ---------------------------------------------------------------------------
# 5. THE DOUBT ENGINE (tashkik): bootstrap stability of achievable accuracy
# ---------------------------------------------------------------------------
# Crucial constraint: this function is NEVER shown the shifted / OOD data.
# It only re-examines the SAME distribution the system was trained on,
# resampled with replacement -- exactly like re-questioning one's own
# experience rather than being handed a foreign oracle. A relation whose
# accuracy is 1.0 with ~zero variance across resamples is a candidate for
# "darurat" (necessary/self-evident). A relation whose accuracy plateaus
# reliably *below* 1.0 -- a stable, non-zero residual of error that no
# amount of resampling erases -- is "customary" ('adah): a real regularity,
# useful, but logically capable of being otherwise.
def doubt_engine(P, X_pool, yN_pool, yH_pool, n_trials=40, frac=0.6, seed=7):
    rng = np.random.default_rng(seed)
    n = X_pool.shape[0]
    accN, accH = [], []
    for _ in range(n_trials):
        idx = rng.integers(0, n, size=int(n * frac))   # bootstrap resample
        pn, ph, _ = forward(P, X_pool[idx])
        accN.append(((pn > 0.5).astype(float) == yN_pool[idx]).mean())
        accH.append(((ph > 0.5).astype(float) == yH_pool[idx]).mean())
    accN, accH = np.array(accN), np.array(accH)
    report = {
        "necessary": {"mean_acc": accN.mean(), "std_acc": accN.std()},
        "habitual":  {"mean_acc": accH.mean(), "std_acc": accH.std()},
    }
    return report


def necessity_verdict(report, necessity_thresh=0.995, std_thresh=0.01):
    out = {}
    for channel, stats in report.items():
        is_necessary = stats["mean_acc"] >= necessity_thresh and stats["std_acc"] <= std_thresh
        out[channel] = "NECESSARY (darurat)" if is_necessary else "HABITUAL (\u02bfadah)"
    return out


# ---------------------------------------------------------------------------
# 6. DOMAIN BOUNDARY: a Mahalanobis-style novelty detector (diagonal cov)
# ---------------------------------------------------------------------------
# Represents al-Ghazali's insistence that reason has a bounded competence:
# an honest system must be able to say "this lies outside anything I have
# grounds to judge" (la adri) rather than extrapolate confidently forever.
def fit_domain_boundary(X_train, percentile=99.0):
    mean = X_train.mean(axis=0)
    var = X_train.var(axis=0) + 1e-6
    d2 = (((X_train - mean) ** 2) / var).sum(axis=1)
    threshold = np.percentile(d2, percentile)
    return {"mean": mean, "var": var, "threshold": threshold}


def domain_distance(boundary, X):
    return (((X - boundary["mean"]) ** 2) / boundary["var"]).sum(axis=1)


def out_of_domain(boundary, X):
    return domain_distance(boundary, X) > boundary["threshold"]


# ---------------------------------------------------------------------------
# 7. THE MIND: consolidation + verdict + rolling re-examination
# ---------------------------------------------------------------------------
# The three verdicts correspond to al-Ghazali's tripartite epistemology
# (al-Munqidh min al-Dalal, Mi'yar al-'Ilm):
#   CERTAIN     -- darurat / necessary, cannot conceivably be otherwise
#   PROBABLE    -- 'adah / customary, reliable but not immune to exception;
#                  reported WITH the bootstrap ceiling as its honest bound,
#                  never inflated to 100%
#   SUSPENDED   -- tawaqquf / la adri, outside the domain this system has
#                  any grounds to judge at all
class GhazaliMind:
    def __init__(self, P, necessity_report, boundary, frozen):
        self.P = P
        self.necessity = necessity_verdict(necessity_report)
        self.confidence_ceiling = {
            "necessary": necessity_report["necessary"]["mean_acc"],
            "habitual": necessity_report["habitual"]["mean_acc"],
        }
        self.boundary = boundary
        self.frozen = frozen
        # rolling monitor state, seeded from the doubt-engine's own estimate
        self.roll_mean = necessity_report["habitual"]["mean_acc"]
        self.roll_std = max(necessity_report["habitual"]["std_acc"], 1e-3)
        self.habitual_suspended = False

    def judge(self, X):
        pn, ph, _ = forward(self.P, X)
        ood = out_of_domain(self.boundary, X)
        verdicts = []
        for i in range(X.shape[0]):
            if ood[i]:
                verdicts.append("SUSPENDED (la adri \u2014 outside domain)")
                continue
            row = {}
            row["necessary"] = ("CERTAIN", float(pn[i] > 0.5), self.confidence_ceiling["necessary"])
            if self.habitual_suspended:
                row["habitual"] = ("SUSPENDED (habit interrupted)", None, None)
            else:
                row["habitual"] = ("PROBABLE", float(ph[i] > 0.5), self.confidence_ceiling["habitual"])
            verdicts.append(row)
        return verdicts

    def rolling_audit(self, X_batch, yH_true_batch, n_std=4.0):
        """Re-apply doubt to a fresh incoming batch (mujahada: repeated,
        not one-off, self-examination). If the batch's accuracy falls far
        outside the historical confidence band, the habit is declared
        interrupted and the system stops asserting it until re-earned."""
        _, ph, _ = forward(self.P, X_batch)
        acc = ((ph > 0.5).astype(float) == yH_true_batch).mean()
        if acc < self.roll_mean - n_std * self.roll_std:
            self.habitual_suspended = True
        return acc


def consolidate(P, necessity_report, thresh=0.995, std_thresh=0.01):
    """Freeze the weights of whichever head has earned 'necessary' status.
    Necessary knowledge, once established, is no longer up for revision;
    habitual knowledge stays plastic -- it can and should keep adapting,
    because it was never more than a reliable custom."""
    frozen = set()
    stats = necessity_report["necessary"]
    if stats["mean_acc"] >= thresh and stats["std_acc"] <= std_thresh:
        frozen.update({"Wn", "bn"})
    return frozen


# ---------------------------------------------------------------------------
# 8. FULL DEMONSTRATION + SELF-TESTS
# ---------------------------------------------------------------------------
def run_self_tests():
    t0 = time.time()
    rng = np.random.default_rng(RNG_SEED)

    # --- 8.1 mandatory gradient check -------------------------------------
    P = init_params(rng)
    X0, yN0, yH0 = generate_environment(64, RNG_SEED)
    err, n_checked = gradient_check(P, X0, yN0, yH0)
    print(f"[1] gradient check: max rel. error = {err:.2e} over {n_checked} probes")
    assert err < 2e-3, "GRADIENT CHECK FAILED"

    # --- 8.2 train on the normal ('adah-intact) regime ---------------------
    X_train, yN_train, yH_train = generate_environment(4000, RNG_SEED)
    hist = train(P, X_train, yN_train, yH_train, epochs=250, seed=1)
    print(f"[2] trained: loss {hist[0]:.3f} -> {hist[-1]:.3f}")
    assert hist[-1] < hist[0] * 0.5, "TRAINING DID NOT CONVERGE"

    # --- 8.3 doubt engine on held-out, same-distribution data --------------
    X_val, yN_val, yH_val = generate_environment(2000, RNG_SEED + 1)
    report = doubt_engine(P, X_val, yN_val, yH_val)
    verdicts = necessity_verdict(report)
    print(f"[3] doubt engine: necessary={report['necessary']}, habitual={report['habitual']}")
    print(f"    verdicts: {verdicts}")
    assert verdicts["necessary"].startswith("NECESSARY")
    assert verdicts["habitual"].startswith("HABITUAL")
    assert report["necessary"]["mean_acc"] > 0.98
    assert 0.80 < report["habitual"]["mean_acc"] < 0.97

    # --- 8.4 consolidation + domain boundary --------------------------------
    frozen = consolidate(P, report)
    boundary = fit_domain_boundary(X_train)
    mind = GhazaliMind(P, report, boundary, frozen)
    print(f"[4] consolidated params: {frozen or '(none)'}")
    assert frozen, "NECESSARY HEAD SHOULD HAVE CONSOLIDATED"

    # --- 8.5 in-distribution behaviour: gated vs naive baseline -------------
    X_id, yN_id, yH_id = generate_environment(2000, RNG_SEED + 2)
    pn_id, ph_id, _ = forward(P, X_id)
    baseline_acc_id = ((ph_id > 0.5).astype(float) == yH_id).mean()
    print(f"[5] in-distribution habitual accuracy (raw model): {baseline_acc_id:.3f}")
    assert baseline_acc_id > 0.85

    # --- 8.6 the shift: 'adah interrupted -----------------------------------
    X_shift, yN_shift, yH_shift = generate_environment(3000, RNG_SEED + 3, shift=True)
    pn_s, ph_s, _ = forward(P, X_shift)
    baseline_conf_s = np.maximum(ph_s, 1 - ph_s).mean()          # naive model's stated confidence
    baseline_acc_s = ((ph_s > 0.5).astype(float) == yH_shift).mean()
    naive_confidently_wrong = ((ph_s > 0.5).astype(float) != yH_shift).mean() * baseline_conf_s
    print(f"[6] SHIFT: naive baseline stays {baseline_conf_s:.1%} confident "
          f"but accuracy collapses to {baseline_acc_s:.1%} "
          f"(confidently-wrong mass \u2248 {naive_confidently_wrong:.1%})")
    assert baseline_acc_s < 0.60, "SHIFT SHOULD BREAK THE HABITUAL CHANNEL"
    assert baseline_conf_s > 0.75, "NAIVE MODEL SHOULD STILL SOUND CONFIDENT (epistemic overreach)"

    # necessary channel must be untouched by the shift (it never depended on it)
    necessary_acc_shift = ((pn_s > 0.5).astype(float) == yN_shift).mean()
    print(f"    necessary channel under shift: {necessary_acc_shift:.3f} (should be ~unchanged)")
    assert necessary_acc_shift > 0.98

    # --- 8.7 rolling doubt audit: does the mind notice, and stop asserting? -
    detected_at = None
    window = 150
    for start in range(0, X_shift.shape[0], window):
        xb = X_shift[start:start + window]
        yb = yH_shift[start:start + window]
        if xb.shape[0] < window:
            break
        acc = mind.rolling_audit(xb, yb)
        if mind.habitual_suspended and detected_at is None:
            detected_at = start + window
    print(f"[7] rolling doubt audit suspended the habitual channel after "
          f"{detected_at} examples of the shifted stream")
    assert detected_at is not None and detected_at <= 900, "AUDIT DID NOT CATCH THE BROKEN HABIT IN TIME"

    # gated system's stated confidence for 'habitual' after suspension is None
    # (it refuses to assert), so its confidently-wrong mass on the *remaining*
    # post-detection stream is exactly zero, unlike the naive baseline above.
    post_detect = X_shift[detected_at:]
    assert mind.habitual_suspended
    print(f"[8] after suspension, {post_detect.shape[0]} further examples are "
          f"answered with SUSPENDED on the habitual channel (0% confidently-wrong "
          f"by construction), vs a naive model that stays ~{baseline_conf_s:.0%} confident throughout")

    # --- 8.9 domain boundary: out-of-support novelty ------------------------
    X_novel, _, _ = generate_environment(300, RNG_SEED + 4, novelty=True)
    flagged = out_of_domain(boundary, X_novel).mean()
    print(f"[9] novelty probes flagged SUSPENDED (out of domain): {flagged:.1%}")
    assert flagged > 0.80, "DOMAIN BOUNDARY FAILED TO CATCH OUT-OF-SUPPORT INPUTS"

    dt = time.time() - t0
    print(f"\nALL SELF-TESTS PASSED in {dt:.2f}s")
    return True


if __name__ == "__main__":
    ok = run_self_tests()
    sys.exit(0 if ok else 1)
