#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
 Chapter 0161 — Aryabhata (476 - c.550 CE)
 THE KUTTAKA-JYA ENGINE : a generative-recurrence architecture
========================
# Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 9 Minds 161 - 180 Available on Amazon https://www.amazon.com/dp/B0HJC1QF59
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · Chapter 0161_aryabhata_476 - Aryabhata (476 - c.550 CE)
================================================================================  

WHO, AND WHY THIS DESIGN
------------------------
Aryabhata, writing the Aryabhatiya at age 23 in Kusumapura (c.499 CE), left a
single surviving book of 121 verses.  Two of its ideas are the cognitive
signature this file tries to *embody in running code* rather than merely
describe:

  1. THE SINE (jya) TABLE is not stored -- it is GENERATED by a local rule.
     Aryabhata (Ganitapada v.12) observed that the *second difference of the
     sine is proportional to the sine itself*.  In modern terms his 24-entry
     R-sine table is the exact orbit of the linear recurrence

            S[n+1] = 2*cos(eps)*S[n] - S[n-1]          (eps = 225'/3438 rad)

     which is precisely a discrete harmonic oscillator -- a rotation in the
     plane.  He compressed a whole curve into ONE update rule + a seed.

  2. THE KUTTAKA ("pulverizer", Ganitapada v.32-33) solves the linear
     indeterminate equation  a*x - b*y = c  by grinding the coefficients down
     to successively smaller remainders (the extended Euclidean algorithm,
     >1000 years early).  The pulverizer is how his astronomy answers the
     question "WHEN do two cycles coincide?" -- the modular arithmetic of
     conjunctions in a yuga.

The thesis that follows from *these two ideas together*:

     INTELLIGENCE IS THE ART OF THE COMPRESSED GENERATIVE RULE.
     Do not memorise the world's trajectory; learn the small recurrence that
     regenerates it, and roll that rule forward to PREDICT BY CALCULATION.
     Where the trajectory is periodic, the rule is an oscillator (jya).
     Where the question is "when do phases align", the rule is remainder
     descent (kuttaka).  Number itself is a positional recurrence
     (place-to-place, tenfold -- "sthanat sthanam dasagunam", Ganitapada v.2).

This is deliberately NOT a Transformer, NOT attention over stored keys, and
NOT a look-up table.  It is a learnable bank of discrete oscillators (a
rotational linear state-space model whose transition is Aryabhata's own sine
recurrence) coupled to an exact integer pulverizer.  Everything here is
pure NumPy, from scratch, with a hand-derived backward pass and a mandatory
finite-difference gradient check.

WHAT THE FILE CONTAINS
----------------------
  * JyaEngine        - learnable oscillator bank (rotational state-space model)
                       forward pass + hand-written reverse-mode BPTT.
  * grad_check()     - finite-difference verification of every gradient
                       (MANDATORY; must pass).
  * Adam optimiser   - tiny from-scratch optimiser.
  * train_demo()     - learn the frequencies of a synthetic multi-periodic
                       "planetary longitude" from a short warm-up window, then
                       EXTRAPOLATE (predict-by-calculation) into the future.
  * aryabhata_sine_table() - regenerate his 24 R-sines from the recurrence and
                       compare to his historical integers.
  * kuttaka()        - the pulverizer: extended Euclid returning the Valli
                       (list of quotients) + Bezout coefficients.
  * crt_kuttaka()    - align two cycles (Chinese-Remainder via the pulverizer)
                       = "conjunction epoch"; cross-checked against the running
                       oscillator engine.
  * horner_encode/decode() - place-value as a positional recurrence.
  * self_tests()     - runs all of the above and prints a verifiable report.

Run:  python3 chapter_0161_aryabhata_476.py
================================================================================
"""

from __future__ import annotations
import numpy as np

# A fixed seed so the printed report is reproducible.
RNG = np.random.default_rng(476)          # 476 CE, Aryabhata's birth year.


# =============================================================================
# PART I.  THE PULVERIZER  (kuttaka)  -- exact integer number theory
# =============================================================================
# Aryabhata's most distinctive algorithm.  "Kuttaka" = to pulverise: reduce a
# hard congruence to an easier one with smaller coefficients, recurse, then
# back-substitute.  It is the extended Euclidean algorithm.  We keep the
# "Valli" (the ladder/creeper of quotients) because Aryabhata's own method is
# organised around that column of quotients.

def kuttaka(a: int, b: int):
    """Extended Euclidean 'pulverizer'.

    Returns (g, x, y, valli) with  a*x + b*y = g = gcd(a, b),
    where 'valli' is the list of quotients produced while grinding a, b down
    (Aryabhata's ladder).  Iterative, so it never overflows the stack.
    """
    valli = []
    old_r, r = int(a), int(b)
    old_s, s = 1, 0          # coefficients of 'a'
    old_t, t = 0, 1          # coefficients of 'b'
    while r != 0:
        q = old_r // r
        valli.append(q)
        old_r, r = r, old_r - q * r
        old_s, s = s, old_s - q * s
        old_t, t = t, old_t - q * t
    g = old_r
    # sign convention: make gcd non-negative
    if g < 0:
        g, old_s, old_t = -g, -old_s, -old_t
    return g, old_s, old_t, valli


def solve_linear_diophantine(a: int, b: int, c: int):
    """Solve a*x + b*y = c in integers, or return None if unsolvable.

    Returns one particular solution (x0, y0) plus the step (dx, dy): the full
    family is (x0 + k*dx, y0 + k*dy) for integer k.
    """
    g, x, y, _ = kuttaka(a, b)
    if c % g != 0:
        return None
    factor = c // g
    x0, y0 = x * factor, y * factor
    dx, dy = b // g, -a // g
    return (x0, y0, dx, dy)


def modinv(a: int, m: int):
    """Multiplicative inverse of a modulo m via the pulverizer (or None)."""
    g, x, _, _ = kuttaka(a % m, m)
    if g != 1:
        return None
    return x % m


def crt_kuttaka(r1: int, m1: int, r2: int, m2: int):
    """Chinese Remainder via kuttaka: smallest t>=0 with
    t == r1 (mod m1) and t == r2 (mod m2).  Returns (t, lcm) or None.

    This is the 'conjunction epoch' problem of Indian astronomy: given two
    bodies whose cycles have lengths m1, m2 and whose current phases are r1,
    r2, find WHEN the joint phase repeats -- pure prediction by calculation.
    """
    g, p, q, _ = kuttaka(m1, m2)
    if (r2 - r1) % g != 0:
        return None
    lcm = m1 // g * m2
    # t = r1 + m1 * k, where k solves m1*k == (r2 - r1) (mod m2)
    k = ((r2 - r1) // g * p) % (m2 // g)
    t = (r1 + m1 * k) % lcm
    return t, lcm


# =============================================================================
# PART II.  PLACE VALUE  (positional recurrence)
# =============================================================================
# "sthanat sthanam dasagunam syat" -- from place to place, each is ten times
# the preceding (Ganitapada v.2).  Evaluating a number from its digits is
# Horner's rule: a recurrence  v <- v*base + digit.  Aryabhata's own numeral
# notation alternated squared/non-squared places (base-100 groups); we keep
# the general positional recurrence, the essential idea.

def horner_encode(digits, base: int = 10) -> int:
    """Most-significant-digit-first list -> integer, by the positional
    recurrence v <- v*base + d  (the 'tenfold place' rule)."""
    v = 0
    for d in digits:
        v = v * base + int(d)
    return v


def horner_decode(v: int, base: int = 10):
    """Integer -> most-significant-first digit list (inverse recurrence)."""
    v = int(v)
    if v == 0:
        return [0]
    out = []
    while v > 0:
        out.append(v % base)
        v //= base
    return out[::-1]


# =============================================================================
# PART III.  THE JYA ENGINE  (learnable oscillator bank)
# =============================================================================
# A rotational linear state-space model.  State s in R^{2K} is K planar
# oscillators.  Each oscillator k advances by a scaled rotation
#
#     A_k = rho_k * [[ cos th_k, -sin th_k],
#                    [ sin th_k,  cos th_k]] ,   rho_k = exp(lr_k)
#
# The autonomous roll  s[t] = A s[t-1]  with readout  y[t] = C s[t] + b  is
# EXACTLY Aryabhata's generative move: a whole (quasi-)periodic trajectory is
# regenerated from a seed state s0 and the local rule A.  Learning the rule =
# learning the frequencies (th_k) that make the world calculable.
#
# Parameters (all learnable):
#   th   : (K,)     angular frequency of each oscillator
#   lr   : (K,)     log-radius; rho = exp(lr)  (rho ~ 1 => pure oscillation)
#   C    : (D, 2K)  linear readout from state to observation
#   b    : (D,)     output bias
#   s0   : (2K,)    initial (seed) state
# =============================================================================

class JyaEngine:
    def __init__(self, K: int, D: int = 1, seed: int = 476):
        self.K, self.D = K, D
        rng = np.random.default_rng(seed)
        # Spread initial frequencies across (0, pi); small so rollouts are smooth.
        self.th = rng.uniform(0.05, 1.2, size=K)
        self.lr = np.zeros(K)                       # rho = 1 at init (undamped)
        self.C = rng.normal(0, 0.3, size=(D, 2 * K))
        self.b = np.zeros(D)
        self.s0 = rng.normal(0, 1.0, size=2 * K)

    # ---- parameter <-> flat vector helpers (used by the gradient checker) ----
    def get_params(self):
        return {"th": self.th, "lr": self.lr, "C": self.C, "b": self.b, "s0": self.s0}

    def _block(self, k):
        """Return the 2x2 transition block A_k and its pieces."""
        c, s = np.cos(self.th[k]), np.sin(self.th[k])
        rho = np.exp(self.lr[k])
        R = np.array([[c, -s], [s, c]])
        return rho * R, rho, c, s, R

    def _A(self):
        """Assemble the (2K x 2K) block-diagonal transition matrix."""
        K = self.K
        A = np.zeros((2 * K, 2 * K))
        for k in range(K):
            Ak, *_ = self._block(k)
            A[2 * k:2 * k + 2, 2 * k:2 * k + 2] = Ak
        return A

    # ------------------------------------------------------------------ forward
    def forward(self, T: int):
        """Roll the recurrence for T steps. Returns (Y, cache).
        Y has shape (T, D): Y[t] = C s[t+1] + b for t = 0..T-1 (states s1..sT).
        """
        A = self._A()
        S = np.zeros((T + 1, 2 * self.K))
        S[0] = self.s0
        for t in range(1, T + 1):
            S[t] = A @ S[t - 1]
        Y = S[1:] @ self.C.T + self.b          # (T, D)
        cache = (A, S, T)
        return Y, cache

    # ------------------------------------------------------- loss + backward
    def loss_and_grad(self, target, weight=None):
        """MSE loss between the rolled output and `target` (T, D).

        `weight` (T,) optionally down-weights steps (e.g. 0 outside the warm-up
        window so we fit only what we've 'observed' and truly EXTRAPOLATE the
        rest).  Returns (loss, grads dict) with grads for every parameter,
        derived by hand (reverse-mode BPTT).
        """
        target = np.asarray(target, dtype=float)
        if target.ndim == 1:
            target = target[:, None]
        T = target.shape[0]
        if weight is None:
            weight = np.ones(T)
        Y, (A, S, _) = self.forward(T)

        diff = Y - target                               # (T, D)
        wdiff = diff * weight[:, None]                  # w * (y - t)
        denom = weight.sum() * self.D
        loss = np.sum(wdiff * diff) / denom             # sum(w*(y-t)^2)/denom

        # dL/dY  (consistent with the weighted loss above)
        dY = 2.0 * wdiff / denom                        # (T, D)

        # Grads for readout
        gC = dY.T @ S[1:]                               # (D, 2K)
        gb = dY.sum(axis=0)                             # (D,)

        # Backprop through the recurrence to get dL/dA and dL/ds0.
        gA = np.zeros_like(A)
        delta = np.zeros(2 * self.K)                    # dL/ds_{t}, carried back
        AT = A.T
        CT = self.C.T
        for t in range(T, 0, -1):
            # gradient into state s[t] : from this step's output + future states
            delta = CT @ dY[t - 1] + AT @ delta
            gA += np.outer(delta, S[t - 1])
        gs0 = AT @ delta                                # dL/ds0 via s1 = A s0
        # NOTE: after the loop, `delta` holds dL/ds_1's contribution already
        # folded; the outer accumulation used s[t-1] correctly for each t.

        # Map dL/dA (only diagonal 2x2 blocks are real parameters) to th, lr.
        gth = np.zeros(self.K)
        glr = np.zeros(self.K)
        for k in range(self.K):
            Ak, rho, c, s, R = self._block(k)
            Gk = gA[2 * k:2 * k + 2, 2 * k:2 * k + 2]
            # dA_k/dth = rho * [[-s,-c],[c,-s]]
            dth = rho * np.array([[-s, -c], [c, -s]])
            # dA_k/dlr = A_k  (rho = exp(lr) => drho/dlr = rho)
            gth[k] = np.sum(Gk * dth)
            glr[k] = np.sum(Gk * Ak)

        grads = {"th": gth, "lr": glr, "C": gC, "b": gb, "s0": gs0}
        return loss, grads


# =============================================================================
# PART IV.  MANDATORY FINITE-DIFFERENCE GRADIENT CHECK
# =============================================================================

def grad_check(verbose=True):
    """Central finite differences vs analytic grads on every parameter."""
    K, D, T = 3, 2, 18
    net = JyaEngine(K=K, D=D, seed=11)
    # slightly damp so the roll doesn't blow up during the check
    net.lr = RNG.normal(-0.02, 0.02, size=K)
    target = RNG.normal(0, 1, size=(T, D))
    weight = RNG.uniform(0.3, 1.0, size=T)

    loss0, grads = net.loss_and_grad(target, weight)
    h = 1e-6
    max_rel = 0.0
    worst = None
    for name in ["th", "lr", "C", "b", "s0"]:
        P = net.get_params()[name]
        flat = P.ravel()
        g_an = grads[name].ravel()
        for i in range(flat.size):
            orig = flat[i]
            flat[i] = orig + h
            lp, _ = net.loss_and_grad(target, weight)
            flat[i] = orig - h
            lm, _ = net.loss_and_grad(target, weight)
            flat[i] = orig
            g_fd = (lp - lm) / (2 * h)
            denom = max(1.0, abs(g_fd) + abs(g_an[i]))
            rel = abs(g_fd - g_an[i]) / denom
            if rel > max_rel:
                max_rel, worst = rel, f"{name}[{i}]"
    if verbose:
        print(f"  gradient check   : max relative error = {max_rel:.3e}  "
              f"(worst: {worst})")
        print(f"                     {'PASS' if max_rel < 1e-5 else 'FAIL'} "
              f"(threshold 1e-5)")
    return max_rel


# =============================================================================
# PART V.  A TINY ADAM OPTIMISER (from scratch) + TRAINING DEMO
# =============================================================================

class Adam:
    def __init__(self, params, lr=0.02, b1=0.9, b2=0.999, eps=1e-8):
        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps
        self.m = {k: np.zeros_like(v) for k, v in params.items()}
        self.v = {k: np.zeros_like(v) for k, v in params.items()}
        self.t = 0

    def step(self, params, grads):
        self.t += 1
        for k in params:
            self.m[k] = self.b1 * self.m[k] + (1 - self.b1) * grads[k]
            self.v[k] = self.b2 * self.v[k] + (1 - self.b2) * grads[k] ** 2
            mhat = self.m[k] / (1 - self.b1 ** self.t)
            vhat = self.v[k] / (1 - self.b2 ** self.t)
            params[k] -= self.lr * mhat / (np.sqrt(vhat) + self.eps)


def train_demo(verbose=True):
    """Learn a multi-periodic 'planetary longitude' from a short warm-up
    window, then EXTRAPOLATE. This is Aryabhata's core act: fit the rule on a
    little, regenerate the rest by calculation.
    """
    # --- synthesise a target: three commensurate-ish 'planets' ---------------
    T_total = 160
    T_warm = 90                    # only these steps are 'observed'
    tt = np.arange(1, T_total + 1)
    true_freqs = [0.18, 0.41, 0.77]
    amps = [1.0, 0.5, 0.3]
    phases = [0.4, 1.1, 2.0]
    signal = sum(a * np.sin(f * tt + p) for a, f, p in zip(amps, true_freqs, phases))
    signal = signal[:, None]                         # (T,1)

    weight = np.zeros(T_total)
    weight[:T_warm] = 1.0                            # fit warm-up only

    net = JyaEngine(K=4, D=1, seed=476)              # 4 oscillators (>3 needed)
    net.lr = np.full(net.K, -0.001)                 # near-undamped
    opt = Adam(net.get_params(), lr=0.03)

    params = net.get_params()
    hist = []
    n_iter = 5000
    for it in range(n_iter):
        loss, grads = net.loss_and_grad(signal, weight)
        # cosine-style learning-rate decay for a stable final fit
        opt.lr = 0.03 * (0.5 * (1 + np.cos(np.pi * it / n_iter)))
        opt.step(params, grads)
        # keep oscillators from decaying/exploding: clamp log-radius gently
        params["lr"][:] = np.clip(params["lr"], -0.05, 0.02)
        if it % 1000 == 0 or it == n_iter - 1:
            hist.append((it, loss))

    Y, _ = net.forward(T_total)
    warm_mse = np.mean((Y[:T_warm, 0] - signal[:T_warm, 0]) ** 2)
    extrap_mse = np.mean((Y[T_warm:, 0] - signal[T_warm:, 0]) ** 2)

    # Rank the K oscillators by how much output energy they carry, so we read
    # off the frequencies the model actually relies on (K=4 fits 3 tones, so a
    # spare oscillator carries ~0 energy).
    freqs = np.abs(net.th) % np.pi
    energy = np.array([np.hypot(net.C[0, 2 * k], net.C[0, 2 * k + 1])
                       for k in range(net.K)])
    order = np.argsort(-energy)
    ranked = [(round(float(freqs[k]), 3), round(float(energy[k]), 3)) for k in order]

    if verbose:
        print(f"  training (fit on {T_warm}/{T_total} steps, extrapolate rest):")
        for it, l in hist:
            print(f"      iter {it:5d}   warm-up loss = {l:.6e}")
        print(f"  warm-up   MSE    : {warm_mse:.3e}")
        print(f"  EXTRAPOLATION MSE: {extrap_mse:.3e}   "
              f"(future predicted by rolling the learned rule)")
        print(f"  true frequencies : {sorted(true_freqs)}")
        print(f"  learned (freq, readout-energy), ranked:")
        for f, e in ranked:
            print(f"                     freq={f:.3f}  energy={e:.3f}")
    return warm_mse, extrap_mse


# =============================================================================
# PART VI.  REGENERATE ARYABHATA'S SINE TABLE FROM THE RECURRENCE
# =============================================================================
# His historical 24 R-sines (radius R = 3438), Ganitapada v.12.

ARYABHATA_RSINES = [225, 449, 671, 890, 1105, 1315, 1520, 1719, 1910, 2093,
                    2267, 2431, 2585, 2728, 2859, 2978, 3084, 3177, 3256,
                    3321, 3372, 3409, 3431, 3438]


def aryabhata_sine_table(verbose=True):
    """Regenerate the 24 R-sines by the SAME local rule Aryabhata used:
    the second sine-difference is proportional to the sine, i.e. the exact
    oscillator recurrence  S[n+1] = 2 cos(eps) S[n] - S[n-1].
    """
    R = 3438.0
    eps = 225.0 / R                    # step of 3 deg 45' in radians (= 225'/R)
    two_cos = 2.0 * np.cos(eps)

    S = np.zeros(25)
    S[0] = 0.0
    S[1] = R * np.sin(eps)             # seed = first half-chord
    for n in range(1, 24):
        S[n + 1] = two_cos * S[n] - S[n - 1]
    regen = [int(v) for v in np.round(S[1:])]

    true_vals = np.array([R * np.sin(n * eps) for n in range(1, 25)])
    err_vs_true = float(np.max(np.abs(S[1:] - true_vals)))
    err_vs_hist = int(np.max(np.abs(np.array(regen) - np.array(ARYABHATA_RSINES))))

    if verbose:
        print("  sine table regenerated from the 2nd-difference recurrence:")
        print(f"      first 8 regen : {regen[:8]}")
        print(f"      first 8 hist. : {ARYABHATA_RSINES[:8]}")
        print(f"      last  value   : regen={regen[-1]} hist={ARYABHATA_RSINES[-1]} (=R)")
        print(f"      max |regen - exact R*sin| = {err_vs_true:.2e}")
        print(f"      max |regen - Aryabhata's integers| = {err_vs_hist} unit(s)")
    return err_vs_true, err_vs_hist


# =============================================================================
# PART VII.  CONJUNCTION: kuttaka predicts, the JyaEngine confirms
# =============================================================================

def conjunction_demo(verbose=True):
    """Two bodies with integer periods and phase offsets.  The pulverizer
    predicts the epoch of joint-phase recurrence; the oscillator engine is
    rolled forward to CONFIRM they coincide there. Number theory + harmonic
    generation, unified -- the whole architecture in miniature.
    """
    m1, m2 = 12, 20                       # cycle lengths (steps)
    r1, r2 = 5, 9                          # current phases within each cycle
    res = crt_kuttaka(r1, m1, r2, m2)
    ok_bruteforce = None
    predicted = None
    if res is not None:
        predicted, lcm = res
        # brute-force verify
        found = None
        for t in range(lcm):
            if t % m1 == r1 and t % m2 == r2:
                found = t
                break
        ok_bruteforce = (found == predicted)

    # Cross-check with the engine: two pure oscillators whose phases at step t
    # are (t mod m). They "coincide" (both at phase 0) at t = lcm(m1,m2).
    g, _, _, _ = kuttaka(m1, m2)
    lcm = m1 // g * m2
    net = JyaEngine(K=2, D=2, seed=7)
    net.lr = np.zeros(2)
    net.th = np.array([2 * np.pi / m1, 2 * np.pi / m2])
    # read each oscillator's x-coordinate
    net.C = np.array([[1., 0., 0., 0.], [0., 0., 1., 0.]])
    net.b = np.zeros(2)
    net.s0 = np.array([1., 0., 1., 0.])   # both start at phase 0
    Y, _ = net.forward(lcm)
    # both back to +1 (phase 0) exactly at t = lcm
    at_lcm = np.allclose(Y[lcm - 1], [1., 1.], atol=1e-6)

    if verbose:
        print("  conjunction (pulverizer predicts, oscillators confirm):")
        print(f"      t == {r1} (mod {m1}) and t == {r2} (mod {m2})")
        print(f"      kuttaka epoch  = {predicted}   brute-force match: {ok_bruteforce}")
        print(f"      lcm({m1},{m2}) = {lcm}; oscillators realign at lcm: {at_lcm}")
    return ok_bruteforce, at_lcm


# =============================================================================
# PART VIII.  SELF TESTS  (everything, verifiable)
# =============================================================================

def self_tests():
    print("=" * 72)
    print(" KUTTAKA-JYA ENGINE  --  self-test report  (Aryabhata, ch.162)")
    print("=" * 72)

    results = {}

    # 1) Pulverizer / Diophantine ------------------------------------------
    print("\n[1] The pulverizer (kuttaka): exact linear Diophantine solutions")
    cases = [(1247, 1624, 29), (17, 4, 1), (99, 78, 3), (240, 46, 2)]
    all_ok = True
    for a, b, c in cases:
        g, x, y, valli = kuttaka(a, b)
        id_ok = (a * x + b * y == g)
        sol = solve_linear_diophantine(a, b, c)
        if sol is None:
            solve_ok = (c % g != 0)
            detail = "unsolvable (correctly detected)"
        else:
            x0, y0, dx, dy = sol
            solve_ok = (a * x0 + b * y0 == c)
            detail = f"x={x0}, y={y0} (+k*({dx},{dy}))"
        all_ok = all_ok and id_ok and solve_ok
        print(f"    a={a:5d} b={b:5d}: gcd={g}, valli={valli}")
        print(f"        Bezout {a}*{x}+{b}*{y}={g} -> {id_ok};  "
              f"a*x+b*y={c}: {detail} -> {solve_ok}")
    # modular inverse
    inv = modinv(17, 43)
    inv_ok = (inv is not None and (17 * inv) % 43 == 1)
    print(f"    modular inverse 17^-1 mod 43 = {inv}  ->  {inv_ok}")
    results["kuttaka"] = all_ok and inv_ok

    # 2) Place value -------------------------------------------------------
    print("\n[2] Place value as a positional recurrence (Horner)")
    n = 62832                           # his circumference-of-diameter-20000
    d = horner_decode(n)
    back = horner_encode(d)
    pv_ok = (back == n)
    print(f"    {n} -> digits {d} -> {back}   round-trip: {pv_ok}")
    results["placevalue"] = pv_ok

    # 3) Sine table regeneration ------------------------------------------
    print("\n[3] Sine (jya) table regenerated from the local rule")
    e_true, e_hist = aryabhata_sine_table()
    results["sine"] = (e_true < 1e-6 and e_hist <= 2)

    # 4) Gradient check ----------------------------------------------------
    print("\n[4] Backprop correctness")
    mr = grad_check()
    results["grad"] = (mr < 1e-5)

    # 5) Training + extrapolation -----------------------------------------
    print("\n[5] Learn the rule, then predict by calculation")
    warm, extra = train_demo()
    results["train"] = (warm < 1e-2 and extra < 5e-2)

    # 6) Conjunction -------------------------------------------------------
    print("\n[6] Conjunction epoch")
    bf, lcm_ok = conjunction_demo()
    results["conjunction"] = bool(bf and lcm_ok)

    # summary --------------------------------------------------------------
    print("\n" + "=" * 72)
    print(" SUMMARY")
    for k, v in results.items():
        print(f"    {k:12s}: {'PASS' if v else 'FAIL'}")
    every = all(results.values())
    print("-" * 72)
    print(f"  ALL TESTS: {'PASS' if every else 'FAIL'}")
    print("=" * 72)
    return every


if __name__ == "__main__":
    ok = self_tests()
    raise SystemExit(0 if ok else 1)
