#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
================================================================================
 QAYD AL-AWĀBID  —  The Fetter of the Wild
 Chapter 0168 · Imru' al-Qays ibn Ḥujr al-Kindī (c. 501 – c. 544 CE)
 Encyclopedia of Lost Minds: Echoes on AI
========================
# Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 9 Minds 161 - 180 Available on Amazon https://www.amazon.com/dp/B0HJC1QF59
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · Chapter 0168_imru_alqays_501 - Imru' al-Qays ibn Ḥujr al-Kindī (c. 501 – c. 544 CE)
================================================================================  

WHAT THIS FILE IS
-----------------
A from-scratch, pure-NumPy neural architecture (no autograd, no frameworks)
whose *structure* encodes the one cognitive operation the classical Arabic
critics said was Imru' al-Qays's before anyone else's: the binding of a moving
thing to a second moving thing that shares its motion, across a gulf of
substance. In his Mu'allaqa the war-horse is

    "wheeling and fleeing, charging and retreating, all at once,
     like a boulder the torrent has hurled down from a height"

and the night is a sea-wave letting down its curtains, and the lightning is the
flicker of hands, and the stars are tethered with flax ropes to a rock so that
they cannot move. Ibn Sallām al-Jumaḥī (d. 846) wrote that in the coining of
similitudes he surpassed everyone of his generation, and that he "fettered the
wild beasts" — qayyada al-awābid — a phrase lifted from his own epithet for the
horse (qaydu l-awābid, "the fetter of the wild"), because his descriptions
caught fleeing things and held them.

The claim of this file is that the operation has a precise mechanistic shape:

    A simile in this mind is NOT a comparison of appearances.
    It is a co-registration of DYNAMICS. Two things are "alike" when the same
    resonators catch them — when a bank of tuned oscillators, each with its own
    tempo and its own rate of forgetting, rings the same way for both.

So the network has three parts, and each is the poem:

  1. DOMAIN ADAPTERS  (the surfaces of things)
     One small linear map per observation domain — "the living", "the inert",
     "the sky". These are disposable. A horse and a boulder arrive through
     different adapters. Nothing downstream knows which.

  2. THE FETTER BANK  (qayd al-awābid)
     K damped-rotor neurons. Each neuron k holds a 2-vector state z that spins
     at a learned angular tempo ω_k and decays at a learned rate; input drives
     it. Energy |z|² accumulates only when the input's rhythm matches the
     neuron's own — it is a resonator, and a resonator is a fetter: it catches
     motion of its tempo and lets everything else through. The readout of each
     neuron is two numbers: the soft PEAK of its energy over time (the moment
     of capture) and the MEAN (how long the hold lasted). The bank is SHARED
     across every domain. This is the whole thesis in one design choice:
     surfaces are private, tempos are common.

  3. TWO HEADS, ONE FOR EACH DIRECTION THE POEM RUNS
     - TASHBĪH (the simile head): given the bank's profile of two things from
       two different domains, decide whether the simile holds — whether they
       were generated by the same underlying motion. The score is a negative
       weighted squared distance in an "aspect" space, so it is symmetric by
       construction (a simile is a binding, not a ranking) and each aspect's
       weight is a learned wajh al-shabah, a "face of resemblance".
     - AṬLĀL (the ruins head): given a residue — a trajectory most of whose
       samples the wind has erased, the rest faded and buried in sand — name
       the motion that made it and reconstruct the motion itself. This is the
       halt at the traces: "the dung of the white antelope in its courtyards
       and hollows, like peppercorns"; the mind reads the camp from what it
       left. The rotors keep ringing across the gaps, which is why residue is
       readable at all.

THE STRUCTURAL FAILURE MODE, ALSO THE POEM'S
--------------------------------------------
"O long night, will you not clear into morning — though morning is no better
than you? ... as if its stars were tethered with every flax rope to a rock."

A mind that grasps by resonance is blind to stillness. For a constant input the
rotor settles to a fixed point whose energy scales as the SQUARE of the input
and whose SHAPE across the bank is fixed. So two different stillnesses give the
same profile up to a scalar: the bank cannot tell them apart. The self-tests
prove this numerically. The tethered-stars family in the data is exactly this,
and the trained network's uncertainty is highest there. That is not a bug
being fixed; it is Imru' al-Qays's night, rendered as a theorem.

THE BASELINE THIS IS MEASURED AGAINST
-------------------------------------
SURFACE: the same adapters and heads, but the profile is the per-channel mean,
standard deviation, maximum and minimum of the adapter output over time —
appearance statistics with no dynamics. Trained identically. Where the fetter
bank binds the horse to the boulder across domains, the surface reader is
asked to do it from looks alone.

CONVENTIONS KEPT FROM THE CORPUS
--------------------------------
  * pure NumPy, hand-derived analytic gradients (BPTT through the rotors)
  * a finite-difference gradient check that must pass (mandatory)
  * a real training loop on a real train/validation split
  * self-tests covering the structural invariants, not just the loss
  * executed before shipping; the printed output is the verified output

RUN:  python3 0168_imru_alqays_501_Neuron.py            (~2-4 min on a laptop)
      python3 0168_imru_alqays_501_Neuron.py --quick    (fewer epochs)
================================================================================
"""

import sys
import time
import numpy as np

# ==============================================================================
# 0.  SMALL UTILITIES
# ==============================================================================

def softplus(x):
    """Numerically safe log(1+exp(x))."""
    x = np.asarray(x, dtype=np.float64)
    return np.where(x > 30.0, x, np.log1p(np.exp(np.minimum(x, 30.0))))


def sigmoid(x):
    x = np.asarray(x, dtype=np.float64)
    return 1.0 / (1.0 + np.exp(-x))


def bce_with_logits(logits, y):
    """Mean binary cross-entropy from logits and its gradient w.r.t. logits."""
    z = logits
    loss = np.maximum(z, 0) - z * y + np.log1p(np.exp(-np.abs(z)))
    grad = (sigmoid(z) - y) / z.size
    return loss.mean(), grad


def softmax_ce(logits, y):
    """Mean cross-entropy from logits (N,F) and integer labels (N,)."""
    m = logits.max(1, keepdims=True)
    ex = np.exp(logits - m)
    p = ex / ex.sum(1, keepdims=True)
    n = logits.shape[0]
    loss = -np.log(p[np.arange(n), y] + 1e-12).mean()
    g = p.copy()
    g[np.arange(n), y] -= 1.0
    return loss, g / n, p


def rule(ch="=", n=78):
    print(ch * n)


# ==============================================================================
# 1.  THE SIX MOTIONS OF THE MU'ALLAQA  (synthetic latent-dynamics generator)
# ==============================================================================
#
# Each "family" is a way of moving, taken from a scene of the ode. Every sample
# is a 2-dimensional latent trajectory ξ of length T (a position-like and a
# velocity-like coordinate). The families are engineered so that their
# marginal statistics overlap and only their TEMPORAL structure separates them.

T_STEPS = 64
LATENT = 2

FAMILIES = [
    "KARR_FARR",     # 0  the horse: charge / retreat, fast reversals
    "TORRENT",       # 1  the boulder hurled by the flood: bounces, closing spacing
    "NIGHT_WAVE",    # 2  the night: a slow swell letting down its curtains
    "TETHERED",      # 3  the stars tethered to the rock: stillness + jitter
    "LIGHTNING",     # 4  the lightning: sparse flashes, sharp decay
    "FLOOD",         # 5  the torrent at Kutayfa: onset, surge, turbulent plateau
]
N_FAM = len(FAMILIES)


def _karr_farr(rng, t):
    f = rng.uniform(0.09, 0.14)
    ph = rng.uniform(0, 2 * np.pi)
    x = np.tanh(3.0 * np.sin(2 * np.pi * f * t + ph))
    # random reversal bursts: the horse "wheeling and fleeing... all at once"
    n_rev = rng.integers(1, 4)
    for _ in range(n_rev):
        t0 = rng.integers(5, T_STEPS - 5)
        x[t0:] *= -1.0
    v = np.gradient(x) * 4.0
    return x, v


def _torrent(rng, t):
    # bounces with geometrically closing spacing and decaying height
    gap = rng.uniform(9.0, 13.0)
    ratio = rng.uniform(0.72, 0.84)
    amp = 1.0
    tt = rng.uniform(0.0, 4.0)
    x = np.zeros(T_STEPS)
    v = np.zeros(T_STEPS)
    while tt < T_STEPS and gap > 1.2:
        i0 = int(tt)
        seg = np.arange(i0, min(T_STEPS, int(tt + gap)))
        u = (seg - tt) / max(gap, 1.0)
        x[seg] = amp * 4.0 * u * (1.0 - u)          # parabolic hop
        v[seg] = amp * (1.0 - 2.0 * u) * 2.0
        tt += gap
        gap *= ratio
        amp *= ratio
    x = x * 2.0 - 0.8
    return x, v


def _night_wave(rng, t):
    f = rng.uniform(0.02, 0.035)
    ph = rng.uniform(0, 2 * np.pi)
    env = 0.5 + 0.5 * (t / T_STEPS) ** rng.uniform(0.6, 1.6)
    x = env * np.sin(2 * np.pi * f * t + ph)
    v = np.gradient(x) * 8.0
    return x, v


def _tethered(rng, t):
    c = rng.uniform(-1.0, 1.0)
    x = c + 0.03 * rng.standard_normal(T_STEPS)
    v = 0.03 * rng.standard_normal(T_STEPS)
    return x, v


def _lightning(rng, t):
    rate = rng.uniform(0.05, 0.11)
    x = np.zeros(T_STEPS)
    flashes = np.where(rng.random(T_STEPS) < rate)[0]
    if flashes.size == 0:
        flashes = np.array([rng.integers(3, T_STEPS - 3)])
    for f0 in flashes:
        dec = rng.uniform(0.35, 0.6)
        k = np.arange(f0, T_STEPS)
        x[k] += rng.uniform(0.7, 1.3) * dec ** (k - f0)
    x = x - 0.4
    v = np.gradient(x) * 3.0
    return x, v


def _flood(rng, t):
    on = rng.uniform(12, 36)
    width = rng.uniform(2.5, 6.0)
    x = -1.0 + 2.0 * sigmoid((t - on) / width)
    turb = 0.18 * np.sin(2 * np.pi * rng.uniform(0.25, 0.4) * t + rng.uniform(0, 6.28))
    x = x + turb * (t > on)
    v = np.gradient(x) * 6.0
    return x, v


GENERATORS = [_karr_farr, _torrent, _night_wave, _tethered, _lightning, _flood]


# A fixed marginal template: every MOVING trajectory is rank-mapped onto exactly
# this set of values, so its mean, spread, maximum and minimum are identical to
# every other moving trajectory's. Only the ORDER in time survives. This is the
# experimental control that makes the question sharp: appearance is equalised,
# dynamics is all that is left. (Stillness is exempt: the tethered stars keep
# their tiny variance, because stillness is visible to anyone.)
_U = (np.arange(T_STEPS) + 0.5) / T_STEPS
TEMPLATE = np.tanh(2.2 * (2.0 * _U - 1.0)) / np.tanh(2.2)          # S-shaped, in [-1, 1]


def equalise(rng, y):
    """Rank-map y onto TEMPLATE (ties broken at random)."""
    jitter = 1e-6 * rng.standard_normal(y.shape)
    order = np.argsort(y + jitter)
    out = np.empty_like(y)
    out[order] = TEMPLATE
    return out


def latent_trajectory(rng, fam):
    t = np.arange(T_STEPS, dtype=np.float64)
    x, v = GENERATORS[fam](rng, t)
    if FAMILIES[fam] != "TETHERED":
        x = equalise(rng, x)
        v = equalise(rng, v)
    xi = np.stack([x, v], -1)                       # (T, 2)
    return xi


# ------------------------------------------------------------------------------
# 1b. DOMAINS  — the surfaces through which motion is seen
# ------------------------------------------------------------------------------
# Domain 0 "the living"  : observes position-like features         (5 channels)
# Domain 1 "the inert"   : observes velocity-like features          (6 channels)
# Domain 2 "the sky"     : observes a mixture with a sign flip      (4 channels)
# Each domain has a fixed random mixing matrix; each SAMPLE additionally carries
# a random static appearance vector (the coat of the horse, the colour of the
# rock) that dominates the mean of the observation and says nothing about how
# the thing moves.

DOMAINS = ["the living", "the inert", "the sky"]
DOM_DIM = [5, 6, 4]


def make_domain_mixers(seed=11):
    rng = np.random.default_rng(seed)
    mixers = []
    for d, D in enumerate(DOM_DIM):
        A = rng.standard_normal((D, LATENT)) * 0.9
        if d == 1:                       # the inert watches velocity mostly
            A[:, 0] *= 0.25
            A[:, 1] *= 1.6
        if d == 2:                       # the sky flips the sign of position
            A[:, 0] *= -1.0
        mixers.append(A)
    return mixers


MIXERS = make_domain_mixers()


def render(rng, xi, dom):
    """Observe a latent trajectory through domain `dom`. Returns (T, D_dom)."""
    A = MIXERS[dom]
    D = A.shape[0]
    coat = rng.uniform(-1.0, 1.0, size=D)          # static appearance confound
    gain = rng.uniform(0.7, 1.3)
    x = np.tanh(gain * xi @ A.T + coat)            # (T, D)
    x = x + 0.05 * rng.standard_normal(x.shape)
    return x


def ground(x, mask):
    """The halt reads marks relative to the ground: subtract, per channel, the mean
    over the samples that survive, then silence the erased samples. Erased means
    'no evidence', not 'zero' — after grounding, a gap sits at the resting level
    and injects no energy of its own. Applied identically to every model."""
    m = mask[:, None]
    n = max(m.sum(), 1.0)
    mu = (x * m).sum(0, keepdims=True) / n
    return (x - mu) * m


def wind(rng, x, keep_frac=None):
    """The aṭlāl operator: erase most samples, fade the rest, bury in sand.
    Returns the residue (T, D+1): grounded observed channels, plus the mask."""
    if keep_frac is None:
        keep_frac = rng.uniform(0.15, 0.50)
    mask = (rng.random(T_STEPS) < keep_frac).astype(np.float64)
    if mask.sum() < 3:                             # a trace must have a few marks
        mask[rng.choice(T_STEPS, 3, replace=False)] = 1.0
    fade = np.exp(-rng.uniform(0.0, 1.5) * np.arange(T_STEPS) / T_STEPS)
    sand = 0.15 * rng.standard_normal(x.shape)
    res = ground(x * fade[:, None] + sand, mask)
    return np.concatenate([res, mask[:, None]], -1), mask


def pad_channels(x, width):
    """Right-pad a (T, D) observation with zeros to (T, width)."""
    out = np.zeros((x.shape[0], width))
    out[:, : x.shape[1]] = x
    return out


MAXD = max(DOM_DIM) + 1                            # +1 for the mask channel


def make_simile_set(n, seed):
    """Cross-domain pairs. Label 1 iff both were generated by the same motion."""
    rng = np.random.default_rng(seed)
    XA = np.zeros((n, T_STEPS, MAXD)); XB = np.zeros((n, T_STEPS, MAXD))
    DA = np.zeros(n, int); DB = np.zeros(n, int)
    FA = np.zeros(n, int); FB = np.zeros(n, int)
    Y = np.zeros(n)
    for i in range(n):
        fa = rng.integers(N_FAM)
        same = rng.random() < 0.5
        fb = fa if same else rng.choice([f for f in range(N_FAM) if f != fa])
        da = rng.integers(len(DOMAINS))
        db = rng.choice([d for d in range(len(DOMAINS)) if d != da])
        full = np.ones(T_STEPS)
        xa = ground(render(rng, latent_trajectory(rng, fa), da), full)
        xb = ground(render(rng, latent_trajectory(rng, fb), db), full)
        XA[i] = pad_channels(np.concatenate([xa, full[:, None]], -1), MAXD)
        XB[i] = pad_channels(np.concatenate([xb, full[:, None]], -1), MAXD)
        DA[i], DB[i], FA[i], FB[i], Y[i] = da, db, fa, fb, float(same)
    return dict(XA=XA, XB=XB, DA=DA, DB=DB, FA=FA, FB=FB, Y=Y)


def make_atlal_set(n, seed):
    """Residues of single trajectories, with the motion label, the clean latent and
    the clean (unwound) observation XC. SIG (filled in by attach_signatures) is the
    restoration target: a fixed reference signature of the unwound observation."""
    rng = np.random.default_rng(seed)
    X = np.zeros((n, T_STEPS, MAXD)); XC = np.zeros((n, T_STEPS, MAXD))
    D = np.zeros(n, int); F = np.zeros(n, int)
    XI = np.zeros((n, T_STEPS, LATENT)); KEEP = np.zeros(n)
    for i in range(n):
        f = rng.integers(N_FAM)
        d = rng.integers(len(DOMAINS))
        xi = latent_trajectory(rng, f)
        x = render(rng, xi, d)
        res, mask = wind(rng, x)
        X[i] = pad_channels(res, MAXD)
        XC[i] = pad_channels(np.concatenate([ground(x, np.ones(T_STEPS)), np.ones((T_STEPS, 1))], -1), MAXD)
        D[i], F[i], XI[i], KEEP[i] = d, f, xi, mask.mean()
    A = dict(X=X, XC=XC, D=D, F=F, XI=XI, KEEP=KEEP)
    A["SIG"] = reference_signature(XC, D)
    return A


# ------------------------------------------------------------------------------
# 1c. THE REFERENCE SIGNATURE  — "the camp as it stood"
# ------------------------------------------------------------------------------
# A FIXED, untrained resonator bank with fixed random adapters. Its response to the
# unwound observation is what the ruins head must restore from the residue. It is
# a label, not a moving target, and it is identical for both models, so the
# restoration score is comparable between the fetter bank and the surface reader.

class _Reference:
    K = 16
    def __init__(self):
        rng = np.random.default_rng(777)
        self.W = [rng.standard_normal((MAXD, self.K)) / np.sqrt(MAXD) for _ in DOMAINS]
        self.bank = None            # built lazily, after FetterBank is defined
        self.mu = None; self.sd = None

    def raw(self, XC, D):
        if self.bank is None:
            self.bank = FetterBank(self.K, 778)
        U = np.zeros((len(XC), T_STEPS, self.K))
        for d in range(len(DOMAINS)):
            idx = np.where(D == d)[0]
            if idx.size:
                U[idx] = np.tanh(XC[idx] @ self.W[d])
        P, _ = self.bank.forward(U)
        return P

    def __call__(self, XC, D):
        P = self.raw(XC, D)
        if self.mu is None:                       # standardise on the first (training) set
            self.mu = P.mean(0); self.sd = P.std(0) + 1e-6
        return (P - self.mu) / self.sd


REFERENCE = _Reference()


def reference_signature(XC, D):
    return REFERENCE(XC, D)


# ==============================================================================
# 2.  THE FETTER NEURON  — a damped rotor with a soft-peak readout
# ==============================================================================
#
#   z_t = a_k · R(ω_k) · z_{t-1} + b_k · u_{t,k}          z ∈ R²
#   a_k = exp(-(softplus(r_k) + 0.02))   ∈ (0, 0.98]      (always stable)
#   R(ω) = [[cos ω, -sin ω], [sin ω, cos ω]]
#   e_t  = |z_t|²                                          (energy)
#   capture_k = (1/β) log Σ_t exp(β e_{t,k})               (soft peak: the catch)
#   hold_k    = mean_t e_{t,k}                             (how long it was held)
#   profile   = [log1p(capture), log1p(hold)]              ∈ R^{2K}
#
# The backward pass is hand-derived BPTT through the recurrence.

class FetterBank:
    def __init__(self, K, seed):
        rng = np.random.default_rng(seed)
        self.K = K
        self.beta = 0.5
        # spread initial tempos across the band the six motions live in
        self.p = {
            "r": rng.uniform(-1.0, 2.0, size=K),                       # damping (pre-softplus)
            "w": np.sort(rng.uniform(0.05, 1.6, size=K)),              # angular tempo
            "b": rng.standard_normal((K, 2)) * 0.5,                    # input coupling
        }

    # ---- forward ----------------------------------------------------------
    def forward(self, U):
        """U: (B, T, K) drive. Returns profile (B, 3K) and a cache.
        profile = [log1p(capture), log1p(hold), moment]  per neuron, where
        capture = soft peak of energy, hold = mean energy, moment = soft-argmax
        time of the energy peak in [0,1] — WHEN the wild thing was caught."""
        B, T, K = U.shape
        r, w, b = self.p["r"], self.p["w"], self.p["b"]
        tgrid = (np.arange(T) + 0.5) / T                       # normalised time
        s = softplus(r) + 0.02
        a = np.exp(-s)
        c, sn = np.cos(w), np.sin(w)
        z = np.zeros((B, K, 2))
        Z = np.zeros((B, T, K, 2))
        for t in range(T):
            zx = a * (c * z[..., 0] - sn * z[..., 1]) + b[:, 0] * U[:, t, :]
            zy = a * (sn * z[..., 0] + c * z[..., 1]) + b[:, 1] * U[:, t, :]
            z = np.stack([zx, zy], -1)
            Z[:, t] = z
        E = (Z ** 2).sum(-1)                                   # (B, T, K)
        hold = E.mean(1)
        mx = E.max(1, keepdims=True)
        sm = np.exp(self.beta * (E - mx))
        sm = sm / sm.sum(1, keepdims=True)                     # softmax over time
        capture = mx[:, 0, :] + np.log(np.exp(self.beta * (E - mx)).sum(1)) / self.beta
        moment = (sm * tgrid[None, :, None]).sum(1)           # (B, K)
        P = np.concatenate([np.log1p(capture), np.log1p(hold), moment], -1)
        cache = dict(U=U, s=s, a=a, c=c, sn=sn, Z=Z, E=E, hold=hold, capture=capture,
                     mx=mx, sm=sm, moment=moment, tgrid=tgrid)
        return P, cache

    # ---- backward ---------------------------------------------------------
    def backward(self, dP, cache):
        """dP: (B, 3K). Returns grads dict and dU (B, T, K)."""
        U, a, c, sn, Z, E = cache["U"], cache["a"], cache["c"], cache["sn"], cache["Z"], cache["E"]
        hold, capture, sm, moment = cache["hold"], cache["capture"], cache["sm"], cache["moment"]
        tgrid = cache["tgrid"]
        B, T, K = U.shape
        r, w, b = self.p["r"], self.p["w"], self.p["b"]
        dcap = dP[:, :K] / (1.0 + capture)
        dhold = dP[:, K:2 * K] / (1.0 + hold)
        dmom = dP[:, 2 * K:]
        # d capture / dE_t = sm_t ;  d hold / dE_t = 1/T ;
        # d moment / dE_t = beta * sm_t * (t~ - moment)
        dE = (dcap[:, None, :] * sm
              + dhold[:, None, :] / T
              + dmom[:, None, :] * self.beta * sm * (tgrid[None, :, None] - moment[:, None, :]))
        dZ = 2.0 * dE[..., None] * Z
        dz_next = np.zeros((B, K, 2))
        dA = np.zeros((K, 2, 2)); db = np.zeros((K, 2)); dU = np.zeros_like(U)
        for t in range(T - 1, -1, -1):
            g = dZ[:, t] + dz_next
            zprev = Z[:, t - 1] if t > 0 else np.zeros((B, K, 2))
            dA += np.einsum("bki,bkj->kij", g, zprev)
            db += (g * U[:, t, :, None]).sum(0)
            dU[:, t, :] = (g * b[None]).sum(-1)
            gx = a * (c * g[..., 0] + sn * g[..., 1])
            gy = a * (-sn * g[..., 0] + c * g[..., 1])
            dz_next = np.stack([gx, gy], -1)
        R = np.stack([np.stack([c, -sn], -1), np.stack([sn, c], -1)], -2)
        Rp = np.stack([np.stack([-sn, -c], -1), np.stack([c, -sn], -1)], -2)
        dw = (dA * (a[:, None, None] * Rp)).sum((1, 2))
        da = (dA * R).sum((1, 2))
        dr = da * (-a) * sigmoid(r)
        return {"r": dr, "w": dw, "b": db}, dU

    # ---- descriptive --------------------------------------------------------
    def spectrum(self):
        s = softplus(self.p["r"]) + 0.02
        a = np.exp(-s)
        w = np.mod(self.p["w"], 2 * np.pi)
        w = np.where(w > np.pi, 2 * np.pi - w, w)          # fold to [0, π]
        period = np.where(w > 1e-6, 2 * np.pi / np.maximum(w, 1e-6), np.inf)
        return w, a, period


# ==============================================================================
# 3.  THE SURFACE READER  — appearance statistics, no dynamics (the baseline)
# ==============================================================================

class SurfaceBank:
    """profile = [mean, std, max, min] of each drive channel over time  (4K)."""
    def __init__(self, K, seed):
        self.K = K
        self.p = {}

    def forward(self, U):
        mu = U.mean(1)
        var = U.var(1) + 1e-6
        sd = np.sqrt(var)
        mx = U.max(1); mn = U.min(1)
        P = np.concatenate([mu, sd, mx, mn], -1)
        cache = dict(U=U, mu=mu, sd=sd, imx=U.argmax(1), imn=U.argmin(1))
        return P, cache

    def backward(self, dP, cache):
        U, mu, sd, imx, imn = cache["U"], cache["mu"], cache["sd"], cache["imx"], cache["imn"]
        B, T, K = U.shape
        dmu, dsd, dmx, dmn = dP[:, :K], dP[:, K:2 * K], dP[:, 2 * K:3 * K], dP[:, 3 * K:]
        dU = np.zeros_like(U)
        dU += dmu[:, None, :] / T
        dU += dsd[:, None, :] * (U - mu[:, None, :]) / (T * sd[:, None, :])
        bi = np.arange(B)[:, None]; ki = np.arange(K)[None, :]
        dU[bi, imx, ki] += dmx
        dU[bi, imn, ki] += dmn
        return {}, dU


# ==============================================================================
# 4.  THE WHOLE MIND  — adapters, bank, and the two heads
# ==============================================================================

class QaydNetwork:
    """
    kind = "QAYD"     : FetterBank   (the architecture of this chapter)
    kind = "SURFACE"  : SurfaceBank  (the appearance baseline)
    """
    def __init__(self, kind="QAYD", K=24, H=12, HID=48, seed=1):
        rng = np.random.default_rng(seed)
        self.kind = kind
        self.K = K
        self.bank = FetterBank(K, seed + 100) if kind == "QAYD" else SurfaceBank(K, seed + 100)
        PDIM = 3 * K if kind == "QAYD" else 4 * K
        self.PDIM = PDIM
        self.p = {}
        # domain adapters (private surfaces)
        for d in range(len(DOMAINS)):
            self.p[f"Wa{d}"] = rng.standard_normal((MAXD, K)) * (1.0 / np.sqrt(MAXD))
            self.p[f"ba{d}"] = np.zeros(K)
        # simile head (tashbīh): aspect projection + non-negative aspect weights
        self.p["Wg"] = rng.standard_normal((PDIM, H)) * (1.0 / np.sqrt(PDIM))
        self.p["bg"] = np.zeros(H)
        self.p["v"] = np.zeros(H) + 0.5            # softplus(v) = aspect weights
        self.p["c0"] = np.array([1.0])             # bias of the simile score
        # ruins head (aṭlāl): hidden layer -> family logits + latent reconstruction
        self.p["W1"] = rng.standard_normal((PDIM, HID)) * (1.0 / np.sqrt(PDIM))
        self.p["b1"] = np.zeros(HID)
        self.p["W2"] = rng.standard_normal((HID, N_FAM)) * (1.0 / np.sqrt(HID))
        self.p["b2"] = np.zeros(N_FAM)
        SIGDIM = 3 * _Reference.K
        self.p["W3"] = rng.standard_normal((HID, SIGDIM)) * (1.0 / np.sqrt(HID))
        self.p["b3"] = np.zeros(SIGDIM)
        # bank parameters live inside the bank; expose them under a prefix
        for k, v in self.bank.p.items():
            self.p["bank." + k] = v

    # --- parameter plumbing --------------------------------------------------
    def params(self):
        return self.p

    def _sync_bank(self):
        for k in list(self.bank.p.keys()):
            self.bank.p[k] = self.p["bank." + k]

    # --- the profile of a set of observations --------------------------------
    def profile(self, X, Dm):
        """X: (B, T, MAXD), Dm: (B,) domain ids. Returns P (B, PDIM), cache."""
        self._sync_bank()
        B = X.shape[0]
        U = np.zeros((B, T_STEPS, self.K))
        for d in range(len(DOMAINS)):
            idx = np.where(Dm == d)[0]
            if idx.size:
                U[idx] = np.tanh(X[idx] @ self.p[f"Wa{d}"] + self.p[f"ba{d}"])
        P, bc = self.bank.forward(U)
        return P, dict(X=X, Dm=Dm, U=U, bc=bc)

    def profile_backward(self, dP, cache, grads):
        gb, dU = self.bank.backward(dP, cache["bc"])
        for k, v in gb.items():
            grads["bank." + k] = grads.get("bank." + k, 0) + v
        dpre = dU * (1.0 - cache["U"] ** 2)
        X, Dm = cache["X"], cache["Dm"]
        for d in range(len(DOMAINS)):
            idx = np.where(Dm == d)[0]
            if idx.size:
                Xd = X[idx].reshape(-1, MAXD)
                Gd = dpre[idx].reshape(-1, self.K)
                grads[f"Wa{d}"] = grads.get(f"Wa{d}", 0) + Xd.T @ Gd
                grads[f"ba{d}"] = grads.get(f"ba{d}", 0) + Gd.sum(0)

    # --- the simile head ------------------------------------------------------
    def simile_forward(self, PA, PB):
        Wg, bg, v, c0 = self.p["Wg"], self.p["bg"], self.p["v"], self.p["c0"]
        GA = PA @ Wg + bg
        GB = PB @ Wg + bg
        dif = GA - GB
        d2 = dif ** 2
        wgt = softplus(v)
        score = -(d2 @ wgt) + c0[0]
        return score, dict(PA=PA, PB=PB, GA=GA, GB=GB, dif=dif, d2=d2, wgt=wgt)

    def simile_backward(self, dscore, cache, grads):
        PA, PB, dif, d2, wgt = cache["PA"], cache["PB"], cache["dif"], cache["d2"], cache["wgt"]
        v = self.p["v"]
        grads["c0"] = grads.get("c0", 0) + np.array([dscore.sum()])
        dwgt = -(dscore[:, None] * d2).sum(0)
        grads["v"] = grads.get("v", 0) + dwgt * sigmoid(v)
        dd2 = -dscore[:, None] * wgt[None, :]
        ddif = 2.0 * dd2 * dif
        dGA = ddif; dGB = -ddif
        grads["Wg"] = grads.get("Wg", 0) + PA.T @ dGA + PB.T @ dGB
        grads["bg"] = grads.get("bg", 0) + dGA.sum(0) + dGB.sum(0)
        dPA = dGA @ self.p["Wg"].T
        dPB = dGB @ self.p["Wg"].T
        return dPA, dPB

    # --- the ruins head --------------------------------------------------------
    def atlal_forward(self, P):
        h = np.tanh(P @ self.p["W1"] + self.p["b1"])
        logits = h @ self.p["W2"] + self.p["b2"]
        recon = h @ self.p["W3"] + self.p["b3"]
        return logits, recon, dict(P=P, h=h)

    def atlal_backward(self, dlogits, drecon, cache, grads):
        P, h = cache["P"], cache["h"]
        grads["W2"] = grads.get("W2", 0) + h.T @ dlogits
        grads["b2"] = grads.get("b2", 0) + dlogits.sum(0)
        grads["W3"] = grads.get("W3", 0) + h.T @ drecon
        grads["b3"] = grads.get("b3", 0) + drecon.sum(0)
        dh = dlogits @ self.p["W2"].T + drecon @ self.p["W3"].T
        dpre = dh * (1.0 - h ** 2)
        grads["W1"] = grads.get("W1", 0) + P.T @ dpre
        grads["b1"] = grads.get("b1", 0) + dpre.sum(0)
        return dpre @ self.p["W1"].T

    # --- losses --------------------------------------------------------------
    def simile_loss(self, batch, want_grad=True):
        PA, cA = self.profile(batch["XA"], batch["DA"])
        PB, cB = self.profile(batch["XB"], batch["DB"])
        score, cs = self.simile_forward(PA, PB)
        loss, dscore = bce_with_logits(score, batch["Y"])
        if not want_grad:
            return loss, score
        grads = {}
        dPA, dPB = self.simile_backward(dscore, cs, grads)
        self.profile_backward(dPA, cA, grads)
        self.profile_backward(dPB, cB, grads)
        return loss, grads

    RECON_WEIGHT = 1.0

    def atlal_loss(self, batch, want_grad=True, target=None):
        """Name the motion from its residue, and RESTORE the reference signature of
        the unwound observation — the full motion, imagined from what it left."""
        target = batch["SIG"] if target is None else target
        P, cP = self.profile(batch["X"], batch["D"])
        logits, recon, ca = self.atlal_forward(P)
        ce, dlogits, probs = softmax_ce(logits, batch["F"])
        diff = recon - target
        mse = (diff ** 2).mean()
        loss = ce + self.RECON_WEIGHT * mse
        if not want_grad:
            return loss, logits, recon, probs, target
        drecon = self.RECON_WEIGHT * 2.0 * diff / diff.size
        grads = {}
        dP = self.atlal_backward(dlogits, drecon, ca, grads)
        self.profile_backward(dP, cP, grads)
        return loss, grads

    def total_loss(self, sb, ab, target=None):
        """Joint loss used by the gradient check: simile + ruins on one batch each."""
        l1, g1 = self.simile_loss(sb)
        l2, g2 = self.atlal_loss(ab, target=target)
        grads = {}
        for g in (g1, g2):
            for k, v in g.items():
                grads[k] = grads.get(k, 0) + v
        return l1 + l2, grads


# ==============================================================================
# 5.  ADAM, TRAINING, EVALUATION
# ==============================================================================

class Adam:
    def __init__(self, params, lr=3e-3, b1=0.9, b2=0.999, eps=1e-8):
        self.lr, self.b1, self.b2, self.eps = lr, b1, b2, eps
        self.m = {k: np.zeros_like(v) for k, v in params.items()}
        self.v = {k: np.zeros_like(v) for k, v in params.items()}
        self.t = 0

    def step(self, params, grads, clip=5.0):
        self.t += 1
        gn = np.sqrt(sum(float((np.asarray(g) ** 2).sum()) for g in grads.values()))
        sc = min(1.0, clip / (gn + 1e-12))
        for k, g in grads.items():
            g = np.asarray(g) * sc
            self.m[k] = self.b1 * self.m[k] + (1 - self.b1) * g
            self.v[k] = self.b2 * self.v[k] + (1 - self.b2) * g * g
            mh = self.m[k] / (1 - self.b1 ** self.t)
            vh = self.v[k] / (1 - self.b2 ** self.t)
            params[k] -= self.lr * mh / (np.sqrt(vh) + self.eps)


def sub(d, idx):
    return {k: (v[idx] if isinstance(v, np.ndarray) and v.shape and v.shape[0] == len(next(iter(d.values()))) else v)
            for k, v in d.items()}


def train(model, S_tr, A_tr, S_va, A_va, epochs=30, bs=64, lr=3e-3, seed=0, log_every=5, verbose=True):
    rng = np.random.default_rng(seed)
    opt = Adam(model.params(), lr=lr)
    nS, nA = len(S_tr["Y"]), len(A_tr["F"])
    steps = max(nS, nA) // bs
    hist = []
    for ep in range(1, epochs + 1):
        pS = rng.permutation(nS); pA = rng.permutation(nA)
        ls = la = 0.0
        for i in range(steps):
            iS = pS[(i * bs) % nS:(i * bs) % nS + bs]
            iA = pA[(i * bs) % nA:(i * bs) % nA + bs]
            if len(iS) < 8: iS = pS[:bs]
            if len(iA) < 8: iA = pA[:bs]
            l1, g1 = model.simile_loss(sub(S_tr, iS))
            opt.step(model.params(), g1)
            l2, g2 = model.atlal_loss(sub(A_tr, iA))
            opt.step(model.params(), g2)
            ls += l1; la += l2
        ls /= steps; la /= steps
        if verbose and (ep % log_every == 0 or ep == 1 or ep == epochs):
            sa = simile_accuracy(model, S_va)
            aa = atlal_accuracy(model, A_va)
            print(f"    epoch {ep:3d}   simile-loss {ls:.4f}   ruins-loss {la:.4f}   "
                  f"| held-out: simile {sa:.3f}   ruins {aa:.3f}")
        hist.append((ep, ls, la))
    return hist


def simile_accuracy(model, S, idx=None):
    if idx is not None:
        S = sub(S, idx)
    _, score = model.simile_loss(S, want_grad=False)
    return float(((score > 0) == (S["Y"] > 0.5)).mean())


def atlal_accuracy(model, A, idx=None):
    if idx is not None:
        A = sub(A, idx)
    _, logits, _, _, _ = model.atlal_loss(A, want_grad=False)
    return float((logits.argmax(1) == A["F"]).mean())


def atlal_restoration_r2(model, A):
    """1 - (restoration error / variance of the clean profile): how much of the
    full resonance signature the mind recovers from the residue alone."""
    _, _, recon, _, target = model.atlal_loss(A, want_grad=False)
    var = target.var(0).mean() + 1e-6
    return float(1.0 - ((recon - target) ** 2).mean() / var)


# ==============================================================================
# 6.  THE MANDATORY GRADIENT CHECK
# ==============================================================================

def gradient_check(kind, seed=7, n=5, eps=1e-5, tol=1e-6, max_entries=48):
    """Central finite differences over EVERY parameter tensor of the joint loss.
    For each tensor a random subset of entries (max_entries) is compared and the
    relative error is measured in the 2-norm, ||num - ana|| / (||num|| + ||ana||),
    which is the right statistic when many entries are legitimately near zero.
    Also reports the largest absolute entry-wise discrepancy seen anywhere."""
    model = QaydNetwork(kind=kind, K=8, H=6, HID=10, seed=seed)
    sb = make_simile_set(n, seed + 1)
    ab = make_atlal_set(n, seed + 2)
    # perturb the parameters so nothing sits at a symmetric point
    rng = np.random.default_rng(seed + 3)
    for k, v in model.p.items():
        v += 0.05 * rng.standard_normal(v.shape)
    tgt = ab["SIG"]                                    # a fixed label
    _, grads = model.total_loss(sb, ab, target=tgt)
    worst = 0.0; worst_name = ""; worst_abs = 0.0; n_entries = 0
    for name, P in model.p.items():
        G = np.broadcast_to(np.asarray(grads.get(name, np.zeros_like(P))), P.shape).reshape(-1)
        flat = P.reshape(-1)
        idxs = np.arange(flat.size)
        if flat.size > max_entries:
            idxs = rng.choice(flat.size, max_entries, replace=False)
        nums = np.zeros(len(idxs)); anas = np.zeros(len(idxs))
        for j, i in enumerate(idxs):
            o = flat[i]
            flat[i] = o + eps; lp, _ = model.total_loss(sb, ab, target=tgt)
            flat[i] = o - eps; lm, _ = model.total_loss(sb, ab, target=tgt)
            flat[i] = o
            nums[j] = (lp - lm) / (2 * eps)
            anas[j] = G[i]
        rel = np.linalg.norm(nums - anas) / (np.linalg.norm(nums) + np.linalg.norm(anas) + 1e-12)
        worst_abs = max(worst_abs, float(np.abs(nums - anas).max()))
        n_entries += len(idxs)
        if rel > worst:
            worst, worst_name = rel, name
    return worst, worst_name, worst < tol, worst_abs, n_entries


# ==============================================================================
# 7.  SELF-TESTS  (structural invariants, not just the loss)
# ==============================================================================

def test_dataset_shapes_and_balance():
    S = make_simile_set(300, 5); A = make_atlal_set(300, 6)
    assert S["XA"].shape == (300, T_STEPS, MAXD) and S["XB"].shape == (300, T_STEPS, MAXD)
    assert np.all(S["DA"] != S["DB"]), "simile pairs must be cross-domain"
    assert 0.35 < S["Y"].mean() < 0.65
    assert A["X"].shape == (300, T_STEPS, MAXD) and A["XC"].shape == (300, T_STEPS, MAXD)
    assert A["SIG"].shape == (300, 3 * _Reference.K) and np.all(np.isfinite(A["SIG"]))
    assert 0.03 < A["KEEP"].min() and A["KEEP"].max() < 0.78, (A["KEEP"].min(), A["KEEP"].max())
    # every moving trajectory carries exactly the template's values: appearance is equalised
    moving = A["F"] != FAMILIES.index("TETHERED")
    srt = np.sort(A["XI"][moving][:, :, 0], axis=1)
    assert np.allclose(srt, TEMPLATE[None, :], atol=1e-9)
    return "cross-domain pairs balanced; moving motions share one exact marginal; residues keep 15-50%"


def test_rotor_is_always_stable():
    bank = FetterBank(16, 3)
    bank.p["r"][:] = -40.0                          # try to make it undamped
    U = np.random.default_rng(0).uniform(-1, 1, size=(4, 400, 16))
    P, c = bank.forward(U)
    a = c["a"]
    assert np.all(a < 0.99) and np.all(np.isfinite(P))
    return f"damping a ∈ ({a.min():.3f}, {a.max():.3f}) ≤ 0.98 even at r = -40; energies finite over 400 steps"


def test_resonance_prefers_its_own_tempo():
    """A rotor tuned to ω rings louder for a sinusoid at ω than one at 3ω."""
    bank = FetterBank(1, 4)
    bank.p["w"][:] = 0.5; bank.p["r"][:] = -2.0; bank.p["b"][:] = [1.0, 0.0]
    t = np.arange(T_STEPS)
    on = np.sin(0.5 * t)[None, :, None]
    off = np.sin(1.5 * t)[None, :, None]
    Pon, _ = bank.forward(on); Poff, _ = bank.forward(off)
    assert Pon[0, 0] > Poff[0, 0] and Pon[0, 1] > Poff[0, 1]
    return f"capture on-tempo {np.expm1(Pon[0,0]):.2f} vs off-tempo {np.expm1(Poff[0,0]):.2f}"


def test_capture_never_below_hold():
    bank = FetterBank(12, 5)
    U = np.random.default_rng(1).standard_normal((6, T_STEPS, 12))
    P, _ = bank.forward(U)
    K = 12
    assert np.all(P[:, :K] >= P[:, K:2 * K] - 1e-12)
    assert np.all((P[:, 2 * K:] >= 0.0) & (P[:, 2 * K:] <= 1.0))
    return "capture ≥ hold for every neuron and sample; moment of capture lies in [0,1]"


def test_stillness_collapse():
    """Two different constant inputs give the SAME profile shape (up to scale):
    the fetter bank cannot tell one stillness from another."""
    bank = FetterBank(10, 6)
    U1 = np.full((1, T_STEPS, 10), 0.3); U2 = np.full((1, T_STEPS, 10), -0.9)
    P1, c1 = bank.forward(U1); P2, c2 = bank.forward(U2)
    # steady-state energies scale exactly with the square of the constant
    e1 = c1["E"][0, -1]; e2 = c2["E"][0, -1]
    ratio = e2 / np.maximum(e1, 1e-12)
    assert np.allclose(ratio, (0.9 / 0.3) ** 2, rtol=1e-6), ratio
    # the normalised shape across the bank is identical
    s1 = e1 / np.linalg.norm(e1); s2 = e2 / np.linalg.norm(e2)
    assert np.allclose(s1, s2, atol=1e-9)
    return "steady-state energy shape across the bank identical for two different constants (rel. err < 1e-9)"


def test_simile_is_symmetric():
    m = QaydNetwork("QAYD", K=8, H=5, HID=8, seed=9)
    S = make_simile_set(20, 10)
    PA, _ = m.profile(S["XA"], S["DA"]); PB, _ = m.profile(S["XB"], S["DB"])
    s1, _ = m.simile_forward(PA, PB); s2, _ = m.simile_forward(PB, PA)
    assert np.allclose(s1, s2, atol=1e-12)
    return "score(a,b) == score(b,a) exactly — a simile is a binding, not a ranking"


def test_aspect_weights_are_nonnegative():
    m = QaydNetwork("QAYD", K=8, H=5, HID=8, seed=9)
    m.p["v"][:] = -50.0
    S = make_simile_set(5, 10)
    PA, _ = m.profile(S["XA"], S["DA"]); PB, _ = m.profile(S["XB"], S["DB"])
    _, c = m.simile_forward(PA, PB)
    assert np.all(c["wgt"] >= 0.0)
    return "every face-of-resemblance weight ≥ 0: resemblance can only bind, never repel"


def test_bank_is_shared_across_domains():
    m = QaydNetwork("QAYD", K=8, H=5, HID=8, seed=9)
    A = make_atlal_set(30, 11)
    # a trajectory pushed through domain 0 and domain 1 adapters hits the same rotors
    P0, c0 = m.profile(A["X"], np.zeros(30, int))
    P1, c1 = m.profile(A["X"], np.ones(30, int))
    assert c0["bc"]["a"] is not None and np.allclose(c0["bc"]["a"], c1["bc"]["a"])
    assert not np.allclose(P0, P1)          # surfaces differ ...
    return "adapters differ per domain; the rotor tempos and damping are one shared bank"


def test_residue_mask_channel_present():
    A = make_atlal_set(50, 12)
    mask = A["X"][:, :, DOM_DIM[0]]       # for domain-0 samples the mask sits at index 5
    d0 = A["D"] == 0
    assert np.all(np.isin(mask[d0], [0.0, 1.0]))
    return "the residue carries an explicit 'this mark survives' channel"


def test_surface_backward_matches_numeric():
    bank = SurfaceBank(5, 0)
    rng = np.random.default_rng(2)
    U = rng.standard_normal((3, 9, 5))
    w = rng.standard_normal((3, 20))
    P, c = bank.forward(U)
    _, dU = bank.backward(w, c)
    eps = 1e-6; worst = 0.0
    for _ in range(30):
        i, t, k = rng.integers(3), rng.integers(9), rng.integers(5)
        o = U[i, t, k]
        U[i, t, k] = o + eps; Pp, _ = bank.forward(U)
        U[i, t, k] = o - eps; Pm, _ = bank.forward(U)
        U[i, t, k] = o
        num = ((Pp - Pm) * w).sum() / (2 * eps)
        worst = max(worst, abs(num - dU[i, t, k]) / (abs(num) + 1e-9))
    assert worst < 1e-5, worst
    return f"baseline profile gradient matches finite differences (max rel err {worst:.1e})"


def test_training_reduces_loss():
    m = QaydNetwork("QAYD", K=8, H=5, HID=8, seed=21)
    S = make_simile_set(96, 30); A = make_atlal_set(96, 31)
    l0, _ = m.simile_loss(S); a0, _ = m.atlal_loss(A)
    train(m, S, A, S, A, epochs=6, bs=32, lr=5e-3, verbose=False)
    l1, _ = m.simile_loss(S); a1, _ = m.atlal_loss(A)
    assert l1 < l0 and a1 < a0
    return f"simile loss {l0:.3f}→{l1:.3f}, ruins loss {a0:.3f}→{a1:.3f} on a small set"


SELF_TESTS = [
    test_dataset_shapes_and_balance,
    test_rotor_is_always_stable,
    test_resonance_prefers_its_own_tempo,
    test_capture_never_below_hold,
    test_stillness_collapse,
    test_simile_is_symmetric,
    test_aspect_weights_are_nonnegative,
    test_bank_is_shared_across_domains,
    test_residue_mask_channel_present,
    test_surface_backward_matches_numeric,
    test_training_reduces_loss,
]


# ==============================================================================
# 8.  ANALYSES PRINTED IN THE REPORT
# ==============================================================================

def per_family_simile(model, S):
    """Accuracy on SAME-motion pairs, per family (can the mind bind X to X across domains?)."""
    _, score = model.simile_loss(S, want_grad=False)
    out = {}
    for f in range(N_FAM):
        idx = (S["FA"] == f) & (S["Y"] > 0.5)
        out[FAMILIES[f]] = float((score[idx] > 0).mean()) if idx.any() else float("nan")
    return out


def confusion_pairs(model, S):
    """Which DIFFERENT motions does the mind most often mistake for the same?"""
    _, score = model.simile_loss(S, want_grad=False)
    rows = []
    for i in range(N_FAM):
        for j in range(i + 1, N_FAM):
            idx = ((S["FA"] == i) & (S["FB"] == j)) | ((S["FA"] == j) & (S["FB"] == i))
            if idx.any():
                rows.append((float((score[idx] > 0).mean()), FAMILIES[i], FAMILIES[j], int(idx.sum())))
    rows.sort(reverse=True)
    return rows


def atlal_by_keep(model, A, bins=((0.10, 0.22), (0.22, 0.34), (0.34, 0.60))):
    _, logits, recon, probs, target = model.atlal_loss(A, want_grad=False)
    pred = logits.argmax(1)
    var = target.var(0).mean() + 1e-6
    out = []
    for lo, hi in bins:
        idx = (A["KEEP"] >= lo) & (A["KEEP"] < hi)
        acc = float((pred[idx] == A["F"][idx]).mean())
        r2 = float(1.0 - ((recon[idx] - target[idx]) ** 2).mean() / var)
        out.append((lo, hi, int(idx.sum()), acc, r2))
    return out


def atlal_by_family(model, A):
    _, logits, _, probs, _ = model.atlal_loss(A, want_grad=False)
    pred = logits.argmax(1)
    ent = -(probs * np.log(probs + 1e-12)).sum(1)
    out = []
    for f in range(N_FAM):
        idx = A["F"] == f
        out.append((FAMILIES[f], float((pred[idx] == f).mean()), float(ent[idx].mean())))
    return out


def faces_of_resemblance(model, S, fa, fb, topn=4):
    """For same-motion pairs of family `fa` — the horse in one domain and the boulder
    in another — which aspects carry the binding?"""
    idx = (S["FA"] == fa) & (S["FB"] == fb) & (S["Y"] > 0.5)
    if not idx.any():
        return None
    PA, _ = model.profile(S["XA"][idx], S["DA"][idx]); PB, _ = model.profile(S["XB"][idx], S["DB"][idx])
    _, c = model.simile_forward(PA, PB)
    contrib = (c["d2"] * c["wgt"]).mean(0)                     # penalty per aspect
    order = np.argsort(contrib)
    return [(int(h), float(c["wgt"][h]), float(contrib[h])) for h in order[:topn]], float(c["wgt"].sum())


def exhibit_similes(model, S):
    """Concrete held-out similes, reported as the mind's probability that they hold."""
    _, score = model.simile_loss(S, want_grad=False)
    p = sigmoid(score)
    def pick(fa, da, fb, db):
        idx = (((S["FA"] == fa) & (S["DA"] == da) & (S["FB"] == fb) & (S["DB"] == db)) |
               ((S["FA"] == fb) & (S["DA"] == db) & (S["FB"] == fa) & (S["DB"] == da)))
        return (float(p[idx].mean()), int(idx.sum())) if idx.any() else (float("nan"), 0)
    rows = [
        ("the horse charging and wheeling (the living)  ~  a boulder in the torrent (the inert)", pick(0, 0, 0, 1)),
        ("the horse charging and wheeling (the living)  ~  a hopping boulder, closing hops (the inert)", pick(0, 0, 1, 1)),
        ("the night letting down its curtains (the sky) ~  a swell in the flood-bed (the inert)", pick(2, 2, 2, 1)),
        ("the night letting down its curtains (the sky) ~  the flash of lightning (the inert)", pick(2, 2, 4, 1)),
        ("the flood at Kutayfa (the inert)             ~  the same surge seen in the sky", pick(5, 1, 5, 2)),
        ("the tethered stars (the sky)                 ~  a still stone (the inert)", pick(3, 2, 3, 1)),
        ("the tethered stars (the sky)                 ~  the horse (the living)", pick(3, 2, 0, 0)),
    ]
    return rows


def energy_by_family(model, A):
    """How much the fetter bank catches, per motion: the total captured energy
    (sum over neurons of the soft-peak energy). Stillness should catch nothing."""
    P, _ = model.profile(A["XC"], A["D"])
    K = model.K
    cap = np.expm1(P[:, :K]).sum(1)
    return [(FAMILIES[f], float(cap[A["F"] == f].mean())) for f in range(N_FAM)]


# ==============================================================================
# 9.  MAIN
# ==============================================================================

def main():
    quick = "--quick" in sys.argv
    t0 = time.time()
    np.set_printoptions(precision=4, suppress=True, linewidth=110)

    rule()
    print(" QAYD AL-AWĀBID — The Fetter of the Wild")
    print(" Chapter 0168 · Imru' al-Qays ibn Ḥujr al-Kindī (c. 501 – c. 544 CE)")
    print(" pure NumPy · hand-derived BPTT · gradient-checked · trained · self-tested")
    rule()

    # ---------------------------------------------------------------- self-tests
    print("\n[1] STRUCTURAL SELF-TESTS")
    passed = 0
    for fn in SELF_TESTS:
        try:
            msg = fn()
            print(f"    PASS  {fn.__name__:<40s} {msg}")
            passed += 1
        except AssertionError as e:
            print(f"    FAIL  {fn.__name__:<40s} {e}")
    print(f"    {passed}/{len(SELF_TESTS)} self-tests passed")
    assert passed == len(SELF_TESTS), "a structural self-test failed; refusing to continue"

    # ------------------------------------------------------------ gradient check
    print("\n[2] FINITE-DIFFERENCE GRADIENT CHECK (mandatory; joint simile + ruins loss)")
    for kind in ("QAYD", "SURFACE"):
        worst, name, ok, wabs, ne = gradient_check(kind)
        print(f"    {kind:<8s}  {ne} entries over every tensor · max relative error {worst:.3e} "
              f"(worst tensor {name}) · max abs discrepancy {wabs:.1e}  {'PASS' if ok else 'FAIL'}")
        assert ok, "gradient check failed"

    # ------------------------------------------------------------------- data
    print("\n[3] DATA")
    nS_tr, nA_tr, nS_va, nA_va = (1500, 1500, 600, 600) if quick else (3000, 3000, 1000, 1000)
    S_tr = make_simile_set(nS_tr, 101); A_tr = make_atlal_set(nA_tr, 102)
    S_va = make_simile_set(nS_va, 201); A_va = make_atlal_set(nA_va, 202)
    print(f"    simile pairs: {nS_tr} train / {nS_va} held-out   (cross-domain only, balanced)")
    print(f"    residues    : {nA_tr} train / {nA_va} held-out   (15-50% of samples survive the wind)")
    print(f"    motions     : {', '.join(FAMILIES)}")
    print(f"    domains     : {', '.join(DOMAINS)}  (channels {DOM_DIM})")

    # ---------------------------------------------------------------- training
    epochs = 12 if quick else 30
    results = {}
    for kind in ("QAYD", "SURFACE"):
        print(f"\n[4] TRAINING  {kind}   ({'the fetter bank' if kind=='QAYD' else 'the appearance baseline'})")
        model = QaydNetwork(kind=kind, K=32, H=12, HID=48, seed=1)
        train(model, S_tr, A_tr, S_va, A_va, epochs=epochs, bs=64, lr=3e-3, seed=3)
        results[kind] = model

    # ------------------------------------------------------------------ report
    print("\n[5] HELD-OUT RESULTS")
    rule("-")
    print(f"    {'':28s}{'QAYD':>10s}{'SURFACE':>10s}")
    q, s = results["QAYD"], results["SURFACE"]
    print(f"    {'simile accuracy (cross-domain)':28s}{simile_accuracy(q,S_va):>10.4f}{simile_accuracy(s,S_va):>10.4f}")
    print(f"    {'ruins: motion named':28s}{atlal_accuracy(q,A_va):>10.4f}{atlal_accuracy(s,A_va):>10.4f}")
    print(f"    {'ruins: restoration R²':28s}{atlal_restoration_r2(q,A_va):>10.4f}{atlal_restoration_r2(s,A_va):>10.4f}")
    rule("-")

    print("\n    same-motion pairs bound across domains, per motion (accuracy on Y=1):")
    pq, ps = per_family_simile(q, S_va), per_family_simile(s, S_va)
    for f in FAMILIES:
        print(f"      {f:<12s}   QAYD {pq[f]:.3f}    SURFACE {ps[f]:.3f}")

    print("\n    the mind's own confusions — different motions bound as one (QAYD, held-out):")
    conf = confusion_pairs(q, S_va)
    nonzero = [c for c in conf if c[0] > 0]
    for rate, a, b, n in (nonzero[:4] if nonzero else conf[:1]):
        print(f"      {a:<11s} ~ {b:<11s}   bound {rate:.3f} of {n} pairs")
    print(f"      ({len(conf) - len(nonzero)} of the {len(conf)} different-motion pairings are never bound; "
          f"worst pairing binds {conf[0][0]:.3f})")

    print("\n    reading the ruins by how much the wind left (QAYD vs SURFACE):")
    for (lo, hi, n, acc, r2), (_, _, _, acc2, r22) in zip(atlal_by_keep(q, A_va), atlal_by_keep(s, A_va)):
        print(f"      {int(lo*100):2d}-{int(hi*100):2d}% of marks survive  (n={n:3d})   "
              f"QAYD acc {acc:.3f} R² {r2:.3f}   |   SURFACE acc {acc2:.3f} R² {r22:.3f}")

    print("\n    the long night — per-motion ruins accuracy and the mind's uncertainty (entropy, nats):")
    for name, acc, ent in atlal_by_family(q, A_va):
        flag = "   <- the tethered stars" if name == "TETHERED" else ""
        print(f"      {name:<12s}  acc {acc:.3f}   entropy {ent:.3f}{flag}")

    print("\n    the fetter bank after training — tempos it learned to catch (period in steps):")
    w, a, period = q.bank.spectrum()
    order = np.argsort(period)
    line = []
    for k in order:
        line.append(f"{period[k]:.1f}({a[k]:.2f})" if np.isfinite(period[k]) else f"inf({a[k]:.2f})")
    print("      " + "  ".join(line[:12]))
    print("      " + "  ".join(line[12:]))
    print("      (number = period of the rotor in time-steps; parenthesis = per-step retention a)")

    print("\n    what the fetter catches, per motion — total captured energy across the bank (QAYD, unwound inputs):")
    for name, e in energy_by_family(q, A_va):
        flag = "   <- the least caught: the night that will not move" if name == "TETHERED" else ""
        print(f"      {name:<12s}  {e:9.3f}{flag}")

    print("\n    exhibits — the mind's probability that a held-out simile holds (QAYD):")
    for text, (pr, n) in exhibit_similes(q, S_va):
        print(f"      {pr:5.3f}  (n={n:2d})  {text}")

    fr = faces_of_resemblance(q, S_va, 0, 0)
    if fr is not None:
        aspects, total = fr
        print("\n    the horse and the boulder — the four aspects that bind KARR_FARR to itself across domains:")
        for h, wgt, pen in aspects:
            print(f"      aspect {h:2d}   weight {wgt:.3f}   mean squared gap {pen:.4f}")
        print(f"      (sum of all aspect weights {total:.3f}; lower gap = the face of resemblance the simile rests on)")

    print(f"\n    total runtime {time.time()-t0:.1f}s")
    rule()
    print(" verified: 11 structural self-tests, 2 gradient checks, 2 trained models, held-out evaluation")
    rule()


if __name__ == "__main__":
    main()
