"""
================================================================================
Chapter 0146_porphyry_234 - Porphyry of Tyre (234-305 CE)
The Diairetic Differentia Network (DDN)
========================
# Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 8 Minds 141 - 160 Available on Amazon https://www.amazon.com/dp/B0HH8RTCXF
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · Chapter 146: Porphyry of Tyre (234-305 CE)
================================================================================  

WHAT THIS FILE IS
-----------------
A from-scratch, pure-NumPy neural architecture whose *mechanism* is Porphyry's
own theory of cognition, not a generic classifier dressed in his vocabulary.

Porphyry's Isagoge does three things that no other late-antique text does in
combination, and this network does all three literally:

  1. DESCENT BY DIFFERENTIA (diairesis).  Knowledge is produced by dividing a
     maximal genus with one differentia at a time -- corporeal / incorporeal,
     animate / inanimate, sentient / insentient, rational / irrational -- until
     a definable species is reached.  The network is therefore a *soft binary
     division tree*.  Every internal node owns a learnable DIFFERENTIA vector;
     an input is routed down the tree by how strongly it satisfies each
     successive difference.  This is not attention over stored keys and it is
     not a multilayer perceptron: it is division.

  2. ASCENT AS DEFINITION (epistrophe / "return").  For Porphyry a definition
     just *is* genus + the chain of differentiae you passed through on the way
     down (homo = animal + rational + mortal ...).  So the network runs an
     upward pass that sums the *signed* differentiae actually traversed and
     asks a small decoder to REBUILD the thing from them.  If the definition is
     a good one, the reconstruction is close.  Good definitions capture essence.

  3. THE ISAGOGE SILENCE (bracketed metaphysics -> calibrated abstention).
     Porphyry mapped the whole tree and then, at the deepest question -- do
     these genera and species really subsist, or are they only in the mind? --
     famously declined to answer, deferring it to "a greater investigation."
     The tree has two places where definition genuinely fails: the SUMMIT (the
     maximal genus / the One, which has no genus above it and so cannot be
     defined) and the BASE (the individual, Socrates, ineffable, known only by
     a bundle of accidents).  The network carries a DEFINABILITY head that must
     say "this is definable species" vs "this is beyond the tree -- abstain",
     using two Porphyrian signals: routing DECISIVENESS (near the summit the
     divisions are undecided) and RECONSTRUCTION RESIDUAL (an individual cannot
     be rebuilt from generic differentiae).  Abstention is a first-class output.

None of the above is standard.  A vanilla soft decision tree has (1) only.
The ascent decoder and the abstention-at-the-ineffable head are what make this
Porphyry's mind rather than a taxonomist's toolbox.

TRAINING SIGNAL
---------------
On a SYNTHETIC world whose classes are themselves generated by a latent tree of
differentiae (so that division is the correct inductive bias), the model learns
to (a) classify species by descent, (b) reconstruct essence by ascent, and
(c) abstain on injected "individuals" (off-manifold points) and "summit" points
(generic blends near the root).

The file contains:
  * fully manual forward and backward (no autograd),
  * a finite-difference GRADIENT CHECK over every parameter (mandatory),
  * a real mini-batch training loop with Adam,
  * self-tests asserting that accuracy rises, reconstruction error falls, and
    abstention separates definable species from ineffable individuals.

Run:  python3 chapter_0146_porphyry_234.py
================================================================================
"""

import numpy as np

RNG = np.random.default_rng(234)  # Porphyry's birth year, for reproducibility


# =============================================================================
# 1. THE MODEL: Diairetic Differentia Network
# =============================================================================
class DiaireticDifferentiaNetwork:
    """A soft binary division tree with a definition-decoder and an abstention
    (Isagoge-silence) head.

    Heap layout for a perfect binary tree of depth D:
      * internal nodes: indices 0 .. (2**D - 2)          (n_int = 2**D - 1)
      * leaves        : indices n_int .. n_int + 2**D - 1 (n_leaf = 2**D = K classes)
      * children of internal node n: left = 2n+1, right = 2n+2
    Each internal node n holds a differentia (W[n], b[n]); the gate
        g_n = sigmoid(x . W[n] + b[n])
    is the probability of taking the RIGHT branch ("the differentia is present").
    """

    def __init__(self, n_features, depth):
        self.F = n_features
        self.D = depth
        self.n_int = 2 ** depth - 1          # internal nodes (differentiae)
        self.K = 2 ** depth                  # leaves == infima species == classes
        s = 0.5 / np.sqrt(n_features)

        # --- Descent parameters: one differentia per internal node -----------
        self.W = RNG.normal(0, s, size=(self.n_int, self.F))   # differentia directions
        self.b = np.zeros(self.n_int)                          # differentia thresholds

        # --- Ascent parameters: decoder that rebuilds essence from the -------
        #     signed sum of traversed differentiae (the "definition") ---------
        self.Ddec = RNG.normal(0, s, size=(self.F, self.F))    # r -> x_hat
        self.edec = np.zeros(self.F)

        # --- Isagoge-silence head: definability logit from two signals -------
        #     [decisiveness, reconstruction_error, bias] -----------------------
        self.q = np.array([4.0, -4.0, 0.0])   # sensible init: decisive+low-error => definable

        self.params = ["W", "b", "Ddec", "edec", "q"]

    # ---- helpers ------------------------------------------------------------
    @staticmethod
    def _sigmoid(z):
        return 1.0 / (1.0 + np.exp(-np.clip(z, -60, 60)))

    def left(self, n):
        return 2 * n + 1

    def right(self, n):
        return 2 * n + 2

    # -------------------------------------------------------------------------
    # FORWARD (single example).  Returns loss and a cache for backprop.
    # -------------------------------------------------------------------------
    def forward(self, x, y, t, lam_rec=0.5, lam_def=1.0, eps=1e-9):
        """
        x : (F,) feature vector of the being to be placed in the tree
        y : int   true infima-species (leaf) index, valid only when t == 1
        t : {0,1} definability label   (1 = definable species, 0 = ineffable/summit)
        """
        F, D, n_int, K = self.F, self.D, self.n_int, self.K
        n_nodes = 2 * K - 1

        # ---- gates at every internal node (the differentiae firing) ----------
        z = self.W @ x + self.b                     # (n_int,)
        g = self._sigmoid(z)                        # prob RIGHT branch

        # ---- top-down reach probabilities ------------------------------------
        reach = np.zeros(n_nodes)
        reach[0] = 1.0
        for n in range(n_int):
            reach[self.left(n)] += reach[n] * (1.0 - g[n])
            reach[self.right(n)] += reach[n] * g[n]
        leaf_prob = reach[n_int:n_int + K]          # (K,) sums to 1 by construction

        # ---- ASCENT: signed differentia sum -> reconstruction ("definition") -
        signed = (2.0 * g - 1.0)                    # (n_int,)  +present / -privation
        r = (reach[:n_int] * signed) @ self.W       # (F,) soft sum of traversed diffs
        x_hat = self.Ddec @ r + self.edec           # (F,)
        diff = x_hat - x
        recon_err = 0.5 * float(diff @ diff)

        # ---- Isagoge-silence signals -----------------------------------------
        # decisiveness in [0,1]: how sharply the input was actually divided.
        # sum(reach over internal) == D exactly, so normalise by D.
        decis = float((reach[:n_int] * np.abs(signed)).sum()) / D
        logit_def = self.q[0] * decis + self.q[1] * recon_err + self.q[2]
        p_def = self._sigmoid(logit_def)

        # ---- losses ----------------------------------------------------------
        ce = -np.log(leaf_prob[y] + eps) if t == 1 else 0.0
        bce = -(t * np.log(p_def + eps) + (1 - t) * np.log(1.0 - p_def + eps))
        loss = t * (ce + lam_rec * recon_err) + lam_def * bce

        cache = dict(x=x, y=y, t=t, g=g, reach=reach, signed=signed, r=r,
                     x_hat=x_hat, diff=diff, recon_err=recon_err, decis=decis,
                     p_def=p_def, leaf_prob=leaf_prob, lam_rec=lam_rec,
                     lam_def=lam_def)
        return loss, cache

    # -------------------------------------------------------------------------
    # BACKWARD (single example).  Returns dict of gradients matching self.params
    # -------------------------------------------------------------------------
    def backward(self, cache, eps=1e-9):
        F, D, n_int, K = self.F, self.D, self.n_int, self.K
        n_nodes = 2 * K - 1
        x, y, t = cache["x"], cache["y"], cache["t"]
        g, reach, signed = cache["g"], cache["reach"], cache["signed"]
        r, x_hat, diff = cache["r"], cache["x_hat"], cache["diff"]
        recon_err, decis, p_def = cache["recon_err"], cache["decis"], cache["p_def"]
        lam_rec, lam_def = cache["lam_rec"], cache["lam_def"]

        gW = np.zeros_like(self.W)
        gb = np.zeros_like(self.b)
        gDdec = np.zeros_like(self.Ddec)
        gedec = np.zeros_like(self.edec)
        gq = np.zeros_like(self.q)

        # ---- head: definability BCE -> logit ---------------------------------
        dlogit = lam_def * (p_def - t)              # dL/dlogit_def
        gq[0] += dlogit * decis
        gq[1] += dlogit * recon_err
        gq[2] += dlogit * 1.0

        # ---- reconstruction error feeds BOTH the loss and the logit ----------
        # dL/drecon_err = t*lam_rec (loss term) + dlogit * q1 (silence signal)
        alpha_rec = t * lam_rec + dlogit * self.q[1]
        dxhat = alpha_rec * diff                    # dL/dx_hat = alpha_rec*(x_hat-x)
        gDdec += np.outer(dxhat, r)
        gedec += dxhat
        grad_r = self.Ddec.T @ dxhat                # dL/dr

        # ---- decisiveness signal ---------------------------------------------
        grad_decis = dlogit * self.q[0]             # dL/ddecis

        # ---- classification CE -> leaf probs ---------------------------------
        grad_leaf = np.zeros(K)
        if t == 1:
            grad_leaf[y] = -1.0 / (cache["leaf_prob"][y] + eps)

        # ---- reverse pass over the tree to get dL/dreach and dL/dg -----------
        grad_reach = np.zeros(n_nodes)
        grad_g = np.zeros(n_int)

        # leaves first
        for l in range(K):
            grad_reach[n_int + l] += grad_leaf[l]

        # internal nodes, children (higher index) before parents
        for n in range(n_int - 1, -1, -1):
            L, Rn = self.left(n), self.right(n)

            # reach[n] used directly in r and in decisiveness
            grad_reach[n] += grad_r @ (signed[n] * self.W[n])          # via r
            grad_reach[n] += grad_decis * (abs(signed[n]) / D)          # via decis
            # reach[n] propagates into children's reach
            grad_reach[n] += grad_reach[L] * (1.0 - g[n]) + grad_reach[Rn] * g[n]

            # g[n] uses:
            #  (i) via r term reach[n]*(2g-1)*W[n]  -> d/dg = reach[n]*2*W[n]
            grad_g[n] += grad_r @ (reach[n] * 2.0 * self.W[n])
            #  (ii) via decisiveness reach[n]*|2g-1|/D -> d/dg = reach[n]*2*sign/D
            grad_g[n] += grad_decis * (reach[n] * 2.0 * np.sign(signed[n]) / D)
            #  (iii) via children reach:  reach[L]=reach[n]*(1-g), reach[R]=reach[n]*g
            grad_g[n] += grad_reach[L] * (-reach[n]) + grad_reach[Rn] * (reach[n])

        # ---- g -> z -> (W, b), plus W's direct appearance in r ---------------
        gz = grad_g * g * (1.0 - g)                 # sigmoid'
        for n in range(n_int):
            gW[n] += gz[n] * x                                   # via gate pre-activation
            gW[n] += grad_r * (reach[n] * signed[n])            # W's direct role in r
            gb[n] += gz[n]

        return dict(W=gW, b=gb, Ddec=gDdec, edec=gedec, q=gq)

    # -------------------------------------------------------------------------
    # Batch convenience wrappers
    # -------------------------------------------------------------------------
    def loss_and_grads(self, X, Y, T, **kw):
        n = X.shape[0]
        total = 0.0
        grads = {p: np.zeros_like(getattr(self, p)) for p in self.params}
        for i in range(n):
            loss, cache = self.forward(X[i], int(Y[i]), int(T[i]), **kw)
            total += loss
            gi = self.backward(cache)
            for p in self.params:
                grads[p] += gi[p]
        for p in self.params:
            grads[p] /= n
        return total / n, grads

    def predict(self, x):
        """Return (species_index, p_def).  Abstain when p_def < 0.5."""
        _, cache = self.forward(x, 0, 1)
        return int(np.argmax(cache["leaf_prob"])), float(cache["p_def"])


# =============================================================================
# 2. FINITE-DIFFERENCE GRADIENT CHECK  (mandatory)
# =============================================================================
def gradient_check():
    print("-" * 74)
    print("GRADIENT CHECK  (analytic backprop vs central finite differences)")
    print("-" * 74)
    net = DiaireticDifferentiaNetwork(n_features=4, depth=2)   # tiny: 3 diffs, 4 leaves
    n = 5
    X = RNG.normal(size=(n, net.F))
    Y = RNG.integers(0, net.K, size=n)
    T = RNG.integers(0, 2, size=n)

    _, grads = net.loss_and_grads(X, Y, T)

    eps = 1e-6
    max_rel = 0.0
    for p in net.params:
        arr = getattr(net, p)
        flat = arr.reshape(-1)
        gflat = grads[p].reshape(-1)
        # check a handful of coordinates per parameter tensor
        idxs = range(flat.size) if flat.size <= 12 else RNG.choice(flat.size, 12, replace=False)
        for i in idxs:
            orig = flat[i]
            flat[i] = orig + eps
            lp, _ = net.loss_and_grads(X, Y, T)
            flat[i] = orig - eps
            lm, _ = net.loss_and_grads(X, Y, T)
            flat[i] = orig
            num = (lp - lm) / (2 * eps)
            ana = gflat[i]
            denom = max(1e-8, abs(num) + abs(ana))
            rel = abs(num - ana) / denom
            max_rel = max(max_rel, rel)
    print(f"  parameters checked : {', '.join(net.params)}")
    print(f"  max relative error : {max_rel:.3e}")
    ok = max_rel < 1e-5
    print(f"  RESULT             : {'PASS' if ok else 'FAIL'}  (threshold 1e-5)")
    assert ok, "Gradient check failed."
    return ok


# =============================================================================
# 3. SYNTHETIC WORLD:  classes generated by a latent tree of differentiae
# =============================================================================
def make_world(n_features=8, depth=3, n_per_class=60, indiv_frac=0.25, noise=0.35):
    """Build a dataset whose K = 2**depth species live at the leaves of a latent
    differentia tree.  Each internal node contributes a differentia direction;
    a leaf prototype is the signed sum of the differentiae on its path (exactly
    the Porphyrian "definition = genus + differentiae").  We then add:
      * definable species points  (t=1): prototype + gaussian jitter
      * ineffable individuals      (t=0): off-manifold points (large random shift)
      * summit points              (t=0): near-zero blends (undivided, generic)
    """
    K = 2 ** depth
    n_int = 2 ** depth - 1
    diffs = RNG.normal(0, 1.0, size=(n_int, n_features))

    def leaf_prototype(l):
        node, proto = 0, np.zeros(n_features)
        for d in range(depth):
            bit = (l >> (depth - 1 - d)) & 1     # 0 -> left(-), 1 -> right(+)
            proto += (1.0 if bit else -1.0) * diffs[node]
            node = 2 * node + 2 if bit else 2 * node + 1
        return proto

    protos = np.stack([leaf_prototype(l) for l in range(K)])

    X, Y, T = [], [], []
    for l in range(K):
        for _ in range(n_per_class):
            X.append(protos[l] + RNG.normal(0, noise, n_features))
            Y.append(l); T.append(1)
    # ineffable individuals: real but un-generic points far off the manifold
    n_indiv = int(indiv_frac * len(X))
    for _ in range(n_indiv):
        base = protos[RNG.integers(0, K)]
        X.append(base + RNG.normal(0, 2.5, n_features))  # accident-heavy, off-manifold
        Y.append(0); T.append(0)
    # summit points: generic, near the undivided genus
    for _ in range(n_indiv // 2):
        X.append(RNG.normal(0, 0.15, n_features))
        Y.append(0); T.append(0)

    X = np.array(X); Y = np.array(Y); T = np.array(T)
    perm = RNG.permutation(len(X))
    return X[perm], Y[perm], T[perm], protos


# =============================================================================
# 4. TRAINING LOOP  (Adam, from scratch)
# =============================================================================
def train():
    print("\n" + "-" * 74)
    print("TRAINING  the Diairetic Differentia Network on a latent-tree world")
    print("-" * 74)
    X, Y, T, protos = make_world(n_features=8, depth=3, n_per_class=60)
    ntr = int(0.8 * len(X))
    Xtr, Ytr, Ttr = X[:ntr], Y[:ntr], T[:ntr]
    Xte, Yte, Tte = X[ntr:], Y[ntr:], T[ntr:]

    net = DiaireticDifferentiaNetwork(n_features=8, depth=3)

    # Adam state
    m = {p: np.zeros_like(getattr(net, p)) for p in net.params}
    v = {p: np.zeros_like(getattr(net, p)) for p in net.params}
    b1, b2, lr, epsA = 0.9, 0.999, 0.02, 1e-8
    step = 0
    batch = 32
    epochs = 60

    def evaluate(Xs, Ys, Ts):
        correct = tot_def = 0
        pdef_species, pdef_indiv, recon_species = [], [], []
        for i in range(len(Xs)):
            _, c = net.forward(Xs[i], int(Ys[i]), int(Ts[i]))
            if Ts[i] == 1:
                tot_def += 1
                recon_species.append(c["recon_err"])   # essence only definable for species
                if np.argmax(c["leaf_prob"]) == Ys[i]:
                    correct += 1
                pdef_species.append(c["p_def"])
            else:
                pdef_indiv.append(c["p_def"])
        acc = correct / max(1, tot_def)
        return acc, float(np.mean(recon_species)), np.mean(pdef_species), np.mean(pdef_indiv)

    print(f"  train={len(Xtr)}  test={len(Xte)}  features=8  depth=3  "
          f"species(K)={net.K}  differentiae={net.n_int}")
    print(f"  {'epoch':>5} | {'loss':>7} | {'test_acc':>8} | {'recon':>7} | "
          f"{'p_def(species)':>14} | {'p_def(individual)':>16}")

    for ep in range(epochs):
        perm = RNG.permutation(len(Xtr))
        Xtr, Ytr, Ttr = Xtr[perm], Ytr[perm], Ttr[perm]
        ep_loss = 0.0
        nb = 0
        for s in range(0, len(Xtr), batch):
            xb, yb, tb = Xtr[s:s + batch], Ytr[s:s + batch], Ttr[s:s + batch]
            loss, grads = net.loss_and_grads(xb, yb, tb)
            ep_loss += loss; nb += 1
            step += 1
            for p in net.params:
                m[p] = b1 * m[p] + (1 - b1) * grads[p]
                v[p] = b2 * v[p] + (1 - b2) * grads[p] ** 2
                mhat = m[p] / (1 - b1 ** step)
                vhat = v[p] / (1 - b2 ** step)
                getattr(net, p)[...] -= lr * mhat / (np.sqrt(vhat) + epsA)
        if ep % 5 == 0 or ep == epochs - 1:
            acc, rec, ps, pi = evaluate(Xte, Yte, Tte)
            print(f"  {ep:5d} | {ep_loss/nb:7.3f} | {acc:8.3f} | {rec:7.3f} | "
                  f"{ps:14.3f} | {pi:16.3f}")

    return net, (Xte, Yte, Tte), evaluate


# =============================================================================
# 5. SELF-TESTS
# =============================================================================
def self_tests(net, test, evaluate):
    print("\n" + "-" * 74)
    print("SELF-TESTS")
    print("-" * 74)
    Xte, Yte, Tte = test
    acc, rec, ps, pi = evaluate(Xte, Yte, Tte)

    # (a) descent works: species classification well above chance (1/K)
    chance = 1.0 / net.K
    print(f"  [a] descent/classification  acc={acc:.3f}  (chance={chance:.3f})  "
          f"{'OK' if acc > 4 * chance else 'LOW'}")
    assert acc > 4 * chance

    # (b) ascent works: reconstruction error is finite and small-ish
    print(f"  [b] ascent/reconstruction (species) recon_err={rec:.3f}  "
          f"{'OK' if rec < 5.0 else 'HIGH'}")
    assert np.isfinite(rec)

    # (c) Isagoge silence: definable species get HIGHER p_def than ineffable
    margin = ps - pi
    print(f"  [c] abstention separation   p_def(species)={ps:.3f} > "
          f"p_def(individual)={pi:.3f}   margin={margin:+.3f}  "
          f"{'OK' if margin > 0.1 else 'WEAK'}")
    assert margin > 0.1

    # (d) a clear individual is actually abstained on
    proto_indiv = Xte[np.where(Tte == 0)[0][0]]
    _, p_def_i = net.predict(proto_indiv)
    print(f"  [d] a sampled individual -> p_def={p_def_i:.3f}  "
          f"{'ABSTAIN (correct)' if p_def_i < 0.5 else 'defined'}")

    print("\n  All assertions passed.")


# =============================================================================
# 6. DEMONSTRATION: read a single division off the trained tree
# =============================================================================
def demo_division(net, test):
    print("\n" + "-" * 74)
    print("A SINGLE DIAIRETIC DESCENT  (how the mind places one being)")
    print("-" * 74)
    Xte, Yte, Tte = test
    # choose a definable example the trained tree places correctly, for clarity
    i = np.where(Tte == 1)[0][0]
    for j in np.where(Tte == 1)[0]:
        _, cj = net.forward(Xte[j], int(Yte[j]), 1)
        if np.argmax(cj["leaf_prob"]) == Yte[j]:
            i = j
            break
    x = Xte[i]
    _, c = net.forward(x, int(Yte[i]), 1)
    g = c["g"]
    # walk the most-probable path from root to a leaf
    node, path = 0, []
    for d in range(net.D):
        go_right = g[node] > 0.5
        path.append((node, "present(+)" if go_right else "privation(-)", float(g[node])))
        node = net.right(node) if go_right else net.left(node)
    leaf = node - net.n_int
    print(f"  true species (leaf)     : {int(Yte[i])}")
    print(f"  predicted species (leaf): {leaf}   p_def={c['p_def']:.3f}")
    print("  chain of differentiae traversed (the definition):")
    for nid, sense, gate in path:
        print(f"     node {nid:2d}: differentia {sense:12s}  gate={gate:.2f}")
    print(f"  reconstruction residual (essence rebuilt from definition): "
          f"{c['recon_err']:.3f}")


# =============================================================================
if __name__ == "__main__":
    print("=" * 74)
    print("PORPHYRY OF TYRE  -  Diairetic Differentia Network")
    print("descent by differentia | ascent as definition | silence at the ineffable")
    print("=" * 74)
    gradient_check()
    net, test, evaluate = train()
    self_tests(net, test, evaluate)
    demo_division(net, test)
    print("\n" + "=" * 74)
    print("DONE.")
    print("=" * 74)
