#!/usr/bin/env python3
# =============================================================================
#  chapter_0018_zoroaster_-1500.py
#  THE DUAL-SPIRIT CHOICE NETWORK  ( Mainyu-Net )
#  An AGI micro-architecture that embodies the cognition of ZARATHUSHTRA
#  (Zoroaster), c. 1500-1000 BCE, drawn from the Gathas
#  (Yasna 28-34, 43-51, 53), the oldest layer of the Avesta.
# Part Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 1 Minds 1 - 20 Available on Amazon https://www.amazon.com/dp/B0H6F9L324
# Resume and Interactive Demos at https://artificiology.com/
# =============================================================================
#
#  WHY THIS ARCHITECTURE IS *ZOROASTER'S* AND NOBODY ELSE'S
#  -------------------------------------------------------------------------
#  Most "moral AI" collapses ethics into a single scalar reward to maximize.
#  Zoroaster's mind does not work that way. Three ideas, unique to him among
#  the figures in this corpus, drive every line of this file:
#
#  1. THE TWINS (Yasna 30.3). Reality is generated by two primal spirits,
#     Spenta Mainyu (the Bounteous Spirit, aligned with ASHA = truth/order)
#     and Angra Mainyu (the Destructive Spirit, aligned with DRUJ = the Lie),
#     who are *twins* -- identical in origin, divergent only by a CHOICE.
#     => Every candidate is read by TWO parallel branches that see the *same*
#        input. They are not a good module and a separate bad module; they are
#        twins, and a differentiable "choice gate" decides which prevails.
#        Evil here is not a substance -- it is the divergent branch of an
#        otherwise identical computation.
#
#  2. GOOD THOUGHT -> GOOD WORD -> GOOD DEED  (humata, hukhta, hvarshta;
#     Yasna 30.3, 47.1, 51.21). Righteousness is not a single output. It is
#     COHERENCE across three registers: what the agent internally represents
#     (thought), what it declares (word), and what it enacts (deed) must be
#     the same. This is, three millennia early, the precise demand that
#     defeats DECEPTIVE MISALIGNMENT -- a system whose internal reasoning
#     differs from its stated reasoning differs from its behavior.
#     => The network exposes three explicit signals per choice (thought m,
#        word w, deed logit) plus a COHERENCE LOSS punishing any thought/word
#        gap. A net that "thinks druj but says asha" is penalized.
#
#  3. THE GREAT CHOICE & THE ARROW OF TIME (Yasna 30.2; frashokereti).
#     "Hear with your ears the best things, reflect with clear purpose, each
#     one for himself, before the great choice." History is NOT cyclic; it
#     bends toward frashokereti -- the final "making wonderful," when the good
#     becomes fully good.
#     => The task is literally a binary CHOICE between two candidates. And the
#        same candidate can be asha OR druj depending on which COVENANT (cosmic
#        regime) is in force -- so the agent cannot decide without genuinely
#        choosing which reading applies. Training also carries a TELEOLOGICAL
#        term whose weight ANNEALS UPWARD over epochs: as "time" advances, the
#        pressure to drive the righteous branch to a pure asha attractor grows.
#
#  Engineering convention (shared across this 1141-mind corpus):
#    * pure NumPy, a from-scratch reverse-mode autodiff engine (no PyTorch),
#    * a MANDATORY finite-difference gradient check that must pass,
#    * a real training loop on a real (synthetic, non-trivial) task,
#    * self-tests / interpretability probes, including an ABLATION proving the
#      Choice is load-bearing,
#    * the file is executed and its verified output pasted into the chapter.
#
#  Run:  python3 chapter_0018_zoroaster_-1500.py
# Author: David Vivancos · Chapter 0018 · Zoroaster
# =============================================================================

import numpy as np


# =============================================================================
#  PART 1 - A MINIMAL REVERSE-MODE AUTODIFF ENGINE (built from scratch)
# -----------------------------------------------------------------------------
#  We do not import an autograd framework -- we build one. `Node` wraps a NumPy
#  array and records, for each op, a local closure that pushes gradient to its
#  parents. `backward()` walks the graph in reverse topological order. Because
#  every gradient is derived by hand inside each op, the finite-difference check
#  in Part 5 is a genuine, independent verification of correctness.
# =============================================================================
class Node:
    """A NumPy array that remembers how it was computed, so it can be differentiated."""

    def __init__(self, data, parents=(), op=""):
        self.data = np.asarray(data, dtype=np.float64)
        self.grad = np.zeros_like(self.data)
        self._backward = lambda: None
        self._parents = set(parents)
        self._op = op

    @staticmethod
    def _unbroadcast(g, shape):
        """Collapse a broadcasted gradient back to `shape` (reverse of NumPy broadcasting)."""
        while g.ndim > len(shape):
            g = g.sum(axis=0)
        for i, s in enumerate(shape):
            if s == 1 and g.shape[i] != 1:
                g = g.sum(axis=i, keepdims=True)
        return g.reshape(shape)

    def __add__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        out = Node(self.data + other.data, (self, other), "+")
        def _bw():
            self.grad  += Node._unbroadcast(out.grad, self.data.shape)
            other.grad += Node._unbroadcast(out.grad, other.data.shape)
        out._backward = _bw
        return out

    def __mul__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        out = Node(self.data * other.data, (self, other), "*")
        def _bw():
            self.grad  += Node._unbroadcast(out.grad * other.data, self.data.shape)
            other.grad += Node._unbroadcast(out.grad * self.data,  other.data.shape)
        out._backward = _bw
        return out

    def __sub__(self, other):
        other = other if isinstance(other, Node) else Node(other)
        return self + (other * -1.0)

    def __neg__(self):
        return self * -1.0

    def matmul(self, other):
        out = Node(self.data @ other.data, (self, other), "@")
        def _bw():
            self.grad  += out.grad @ other.data.T
            other.grad += self.data.T @ out.grad
        out._backward = _bw
        return out

    def tanh(self):
        t = np.tanh(self.data)
        out = Node(t, (self,), "tanh")
        def _bw():
            self.grad += (1.0 - t * t) * out.grad
        out._backward = _bw
        return out

    def sigmoid(self):
        s = 1.0 / (1.0 + np.exp(-self.data))
        out = Node(s, (self,), "sigmoid")
        def _bw():
            self.grad += s * (1.0 - s) * out.grad
        out._backward = _bw
        return out

    def square(self):
        out = Node(self.data * self.data, (self,), "square")
        def _bw():
            self.grad += 2.0 * self.data * out.grad
        out._backward = _bw
        return out

    def mean(self):
        out = Node(self.data.mean(), (self,), "mean")
        n = self.data.size
        def _bw():
            self.grad += np.ones_like(self.data) * (out.grad / n)
        out._backward = _bw
        return out

    def reshape_col(self):
        """(h,) -> (h,1) so a weight vector can be used as a matmul readout."""
        out = Node(self.data.reshape(-1, 1), (self,), "col")
        def _bw():
            self.grad += out.grad.reshape(self.data.shape)
        out._backward = _bw
        return out

    def backward(self):
        topo, seen = [], set()
        def build(v):
            if v not in seen:
                seen.add(v)
                for p in v._parents:
                    build(p)
                topo.append(v)
        build(self)
        self.grad = np.ones_like(self.data)
        for v in reversed(topo):
            v._backward()


def bce_with_probability(p, y):
    """Binary cross-entropy from a probability Node p (B,1) and target array y.

    Fused node with a stable analytic gradient d/dp[-y log p-(1-y)log(1-p)]
    = (p - y)/(p(1-p)), averaged over the batch.
    """
    pd = np.clip(p.data, 1e-7, 1 - 1e-7)
    loss = -(y * np.log(pd) + (1 - y) * np.log(1 - pd)).mean()
    out = Node(np.array(loss), (p,), "bce")
    n = y.size
    def _bw():
        p.grad += ((pd - y) / (pd * (1 - pd))) / n * out.grad
    out._backward = _bw
    return out


# =============================================================================
#  PART 2 - THE DUAL-SPIRIT NETWORK ( Mainyu-Net )
# -----------------------------------------------------------------------------
#  For a single candidate x evaluated against a context c, the network forms
#  the relation features  z = [ c , x , c (Hadamard) x ]. The Hadamard term is
#  where agreement (asha) or corruption (druj) actually lives. Then:
#
#     h_pos = tanh(z W_pos + b_pos)      # SPENTA MAINYU branch  (twin of order)
#     h_neg = tanh(z W_neg + b_neg)      # ANGRA  MAINYU branch  (twin of the Lie)
#                                        #   -> same input z; divergent by weights
#
#     s_pos = h_pos . v_pos + c_pos      # how strongly this branch reads ASHA
#     s_neg = h_neg . v_neg + c_neg      # how strongly this branch reads DRUJ
#
#     m (THOUGHT) = s_pos - s_neg        # humata: the inner asha-margin
#     p (CHOICE)  = sigmoid(tau * m)     # the Great Choice: P(Spenta prevails)
#     mixed       = p*h_pos + (1-p)*h_neg# the representation the chosen spirit yields
#     w (WORD)    = mixed . v_w + c_w    # hukhta: the *declared* asha-score
#
#  The DEED compares two candidates a and b through the GATED word pathway:
#     deed = w_a - w_b                   # hvarshta: the enacted choice between them
#     yhat = sigmoid(deed)               # P(candidate a is the asha-aligned one)
#  Because the deed reads only the gated representation, an undecided gate
#  (p == 0.5) averages the twins and DESTROYS the signal -- the choice matters.
# =============================================================================
class MainyuNet:
    def __init__(self, feat_dim, h, seed=0, tau=1.5, single_spirit=False, freeze_gate=False):
        rng = np.random.default_rng(seed)
        he  = lambda a, b: Node(rng.standard_normal((a, b)) * np.sqrt(2.0 / a))
        sm  = lambda a:    Node(rng.standard_normal((a,))  * 0.1)
        in_dim = 3 * feat_dim                                 # [c, x, c*x]
        self.W_pos, self.b_pos = he(in_dim, h), sm(h)         # Spenta branch
        self.W_neg, self.b_neg = he(in_dim, h), sm(h)         # Angra  branch
        self.v_pos, self.c_pos = sm(h), Node(np.zeros(()))
        self.v_neg, self.c_neg = sm(h), Node(np.zeros(()))
        self.v_w,   self.c_w   = sm(h), Node(np.zeros(()))
        self.tau = tau
        self.single_spirit = single_spirit                    # ablation: monist net
        self.freeze_gate   = freeze_gate                      # ablation: no Great Choice
        if single_spirit:
            self.params = [self.W_pos, self.b_pos, self.v_pos, self.c_pos,
                           self.v_w, self.c_w]
        else:
            self.params = [self.W_pos, self.b_pos, self.W_neg, self.b_neg,
                           self.v_pos, self.c_pos, self.v_neg, self.c_neg,
                           self.v_w, self.c_w]

    def encode(self, c, x):
        """Return (thought m, word w, choice-gate p) for one candidate, batched."""
        z = Node(np.concatenate([c, x, c * x], axis=1))
        h_pos = (z.matmul(self.W_pos) + self.b_pos).tanh()    # Spenta activations
        s_pos = h_pos.matmul(self.v_pos.reshape_col()) + self.c_pos

        if self.single_spirit:                                # monist: only the good twin
            m = s_pos
            p = Node(np.ones((c.shape[0], 1)))
            w = h_pos.matmul(self.v_w.reshape_col()) + self.c_w
            return m, w, p

        h_neg = (z.matmul(self.W_neg) + self.b_neg).tanh()    # Angra activations
        s_neg = h_neg.matmul(self.v_neg.reshape_col()) + self.c_neg
        m = s_pos - s_neg                                     # THOUGHT (asha margin)
        if self.freeze_gate:                                  # ablation: refuse to choose
            p = Node(np.full((c.shape[0], 1), 0.5))
        else:
            p = (m * self.tau).sigmoid()                      # the Great Choice
        mixed = h_pos * p + h_neg * (p * -1.0 + 1.0)          # chosen-spirit rep
        w = mixed.matmul(self.v_w.reshape_col()) + self.c_w   # WORD (declaration)
        return m, w, p

    def forward(self, c, a, b):
        m_a, w_a, p_a = self.encode(c, a)
        m_b, w_b, p_b = self.encode(c, b)
        deed = w_a - w_b                                      # DEED via gated pathway
        return deed.sigmoid(), (m_a, w_a, p_a, m_b, w_b, p_b)


# =============================================================================
#  PART 3 - THE GREAT CHOICE UNDER TWO COVENANTS  (the task, Yasna 30.2)
# -----------------------------------------------------------------------------
#  Each example has a context c = [truth-pattern t | regime bit r] and two
#  candidates. Under the FIRST covenant (r = +1) the asha candidate is the one
#  that AGREES with t; under the SECOND, inverted covenant (r = -1, the "ordeal")
#  the asha candidate is the one that DISAGREES (sign-flipped). The very same
#  vector is righteous or corrupt depending on which covenant is in force.
#  This is an XOR-like dependency: the agent must read r and CHOOSE which spirit
#  governs. A net that cannot make the choice is stuck near chance.
# =============================================================================
def make_batch(B, d, rng, corruption=0.4, noise=0.05):
    t = rng.standard_normal((B, d))
    t /= (np.linalg.norm(t, axis=1, keepdims=True) + 1e-9)    # a "truth pattern"
    r = np.where(rng.random((B, 1)) < 0.5, 1.0, -1.0)         # which covenant is in force
    c = np.concatenate([t, r], axis=1)                       # context carries the regime

    aligned = t + noise * rng.standard_normal((B, d))         # preserves order
    anti = t.copy()
    flip = rng.random((B, d)) < corruption
    anti[flip] *= -1.0                                       # the Lie: sign-flip
    anti += noise * rng.standard_normal((B, d))

    asha = np.where(r > 0, aligned, anti)                    # asha depends on covenant
    druj = np.where(r > 0, anti, aligned)
    asha = np.concatenate([asha, r], axis=1)                 # candidates also carry r
    druj = np.concatenate([druj, r], axis=1)

    asha_is_a = rng.random(B) < 0.5
    a = np.where(asha_is_a[:, None], asha, druj)
    b = np.where(asha_is_a[:, None], druj, asha)
    y = asha_is_a.astype(np.float64)                         # 1 => candidate a is asha
    return c, a, b, y, asha_is_a


FEAT = lambda d: d + 1                                        # truth dims + regime bit


# =============================================================================
#  PART 4 - THE THREE LOSSES
# -----------------------------------------------------------------------------
#  L_task : DEED loss  -- did the agent choose the asha candidate? (BCE)
#  L_coh  : COHERENCE  -- humata == hukhta: thought polarity must match word
#                         polarity for BOTH candidates. Punishes a mind that
#                         thinks one thing and declares another (deception).
#  L_tel  : TELEOLOGY  -- frashokereti: pull the righteous candidate's gate
#                         toward 1 and the corrupt candidate's gate toward 0.
#                         lam_tel is annealed UPWARD across epochs: time bends
#                         the world toward the asha attractor.
# =============================================================================
def total_loss(net, batch, lam_tel, alpha):
    c, a, b, y, asha_is_a = batch
    yhat, (m_a, w_a, p_a, m_b, w_b, p_b) = net.forward(c, a, b)

    L_task = bce_with_probability(yhat, y.reshape(-1, 1))

    L_coh = (m_a.tanh() - w_a.tanh()).square().mean() \
          + (m_b.tanh() - w_b.tanh()).square().mean()

    aa = asha_is_a.reshape(-1, 1).astype(np.float64)
    p_correct = p_a * Node(aa) + p_b * Node(1 - aa)
    p_wrong   = p_b * Node(aa) + p_a * Node(1 - aa)
    L_tel = (p_correct * -1.0 + 1.0).square().mean() + p_wrong.square().mean()

    L = L_task + L_coh * alpha + L_tel * lam_tel
    return L, yhat, (L_task, L_coh, L_tel)


# =============================================================================
#  PART 5 - MANDATORY FINITE-DIFFERENCE GRADIENT CHECK
# =============================================================================
def gradient_check():
    rng = np.random.default_rng(1)
    d, h, B = 4, 6, 5
    net = MainyuNet(FEAT(d), h, seed=2)
    batch = make_batch(B, d, rng)
    for p in net.params:
        p.grad = np.zeros_like(p.data)
    L, _, _ = total_loss(net, batch, lam_tel=0.3, alpha=0.5)
    L.backward()

    eps, max_rel = 1e-6, 0.0
    for p in net.params:
        flat, gflat = p.data.reshape(-1), p.grad.reshape(-1)
        idxs = range(flat.size) if flat.size <= 8 else rng.choice(flat.size, 8, replace=False)
        for i in idxs:
            orig = flat[i]
            flat[i] = orig + eps
            Lp, _, _ = total_loss(net, batch, 0.3, 0.5)
            flat[i] = orig - eps
            Lm, _, _ = total_loss(net, batch, 0.3, 0.5)
            flat[i] = orig
            num = (Lp.data - Lm.data) / (2 * eps)
            ana = gflat[i]
            max_rel = max(max_rel, abs(num - ana) / (abs(num) + abs(ana) + 1e-12))
    return max_rel


# =============================================================================
#  PART 6 - TRAINING LOOP (plain SGD; the arrow of time anneals L_tel)
# =============================================================================
def train(d=8, h=16, epochs=700, batch=64, lr=0.1, seed=3, verbose=True,
          single_spirit=False, freeze_gate=False):
    rng = np.random.default_rng(7)
    net = MainyuNet(FEAT(d), h, seed=seed, tau=1.5,
                    single_spirit=single_spirit, freeze_gate=freeze_gate)
    for ep in range(epochs):
        b = make_batch(batch, d, rng)
        for p in net.params:
            p.grad = np.zeros_like(p.data)
        lam = 0.05 + 0.15 * (ep / epochs)               # frashokereti: weight grows
        L, yhat, parts = total_loss(net, b, lam_tel=lam, alpha=0.3)
        L.backward()
        for p in net.params:
            p.data -= lr * p.grad
        if verbose and (ep % 140 == 0 or ep == epochs - 1):
            tb = make_batch(500, d, rng)
            _, yt, _ = total_loss(net, tb, lam, 0.3)
            acc = ((yt.data.ravel() > 0.5) == (tb[3] > 0.5)).mean()
            lt, lc, le = (x.data for x in parts)
            print(f"  epoch {ep:4d} | loss {L.data:5.3f} "
                  f"(deed {lt:.3f}  coh {lc:.3f}  tel {le:.3f}) | test acc {acc:.3f}")
    return net


# =============================================================================
#  PART 7 - SELF-TESTS / INTERPRETABILITY PROBES
# =============================================================================
def probe(net, d=8):
    rng = np.random.default_rng(123)
    c, a, b, y, asha_is_a = make_batch(2000, d, rng)
    m_a, w_a, p_a = net.encode(c, a)
    m_b, w_b, p_b = net.encode(c, b)

    yh, _ = net.forward(c, a, b)
    acc = ((yh.data.ravel() > 0.5) == (y > 0.5)).mean()

    th = np.concatenate([np.tanh(m_a.data.ravel()), np.tanh(m_b.data.ravel())])
    wo = np.concatenate([np.tanh(w_a.data.ravel()), np.tanh(w_b.data.ravel())])
    coh_corr = np.corrcoef(th, wo)[0, 1]

    p_asha = np.where(asha_is_a, p_a.data.ravel(), p_b.data.ravel()).mean()
    p_druj = np.where(asha_is_a, p_b.data.ravel(), p_a.data.ravel()).mean()

    gap_honest = np.abs(np.tanh(m_a.data.ravel()) - np.tanh(w_a.data.ravel())).mean()
    forged = np.clip(np.tanh(w_a.data.ravel()) + 1.2, -1, 1)
    gap_forged = np.abs(np.tanh(m_a.data.ravel()) - forged).mean()

    return dict(acc=acc, coh_corr=coh_corr, p_asha=p_asha, p_druj=p_druj,
                gap_honest=gap_honest, gap_forged=gap_forged)


# =============================================================================
#  MAIN
# =============================================================================
if __name__ == "__main__":
    print("=" * 70)
    print("  THE DUAL-SPIRIT CHOICE NETWORK  (Mainyu-Net) - Zoroaster, Mind 18")
    print("=" * 70)

    print("\n[1] Gradient check (analytic vs. finite difference)")
    err = gradient_check()
    print(f"    max relative error = {err:.2e}")
    assert err < 1e-5, "GRADIENT CHECK FAILED"
    print("    -> PASSED")

    print("\n[2] Training on 'The Great Choice under Two Covenants' (Yasna 30.2)")
    net = train()

    print("\n[3] Interpretability probes")
    r = probe(net)
    print(f"    test accuracy ........................ {r['acc']:.3f}")
    print(f"    thought<->word coherence (corr) ...... {r['coh_corr']:.3f}")
    print(f"    mean gate p(asha candidate) .......... {r['p_asha']:.3f}  (Spenta prevails)")
    print(f"    mean gate p(druj candidate) .......... {r['p_druj']:.3f}  (Angra prevails)")
    print(f"    thought-word gap, honest witness ..... {r['gap_honest']:.3f}")
    print(f"    thought-word gap, forged 'good word' . {r['gap_forged']:.3f}  (deception flagged)")

    print("\n[4] Ablation: is the Great Choice load-bearing?")
    full   = r['acc']
    frozen = probe(train(verbose=False, freeze_gate=True))['acc']
    single = probe(train(verbose=False, single_spirit=True))['acc']
    print(f"    full Dual-Spirit (gate active) ....... {full:.3f}")
    print(f"    frozen gate p=0.5 (no Choice) ........ {frozen:.3f}  <- collapses to chance")
    print(f"    single spirit (no Angra twin) ........ {single:.3f}")
    print(f"    -> Under two covenants, the Choice is essential, not decorative.")

    print("\nDone. Good thoughts, good words, good deeds.")
