#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# =============================================================================
#  Chapter 204 — Jabir ibn Hayyan (Geber), c.721–c.815 CE
#  Reference architecture:  THE MIZAN BALANCE ENGINE
# Part of the Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 11 Minds 201 - 220 Available on Amazon https://www.amazon.com/dp/B0HKF7TRFF
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · chapter_0204_jabir_ibn_hayyan_geber_721 - Jabir ibn Hayyan (Geber), c.721–c.815 CE
#
#  WHY THIS ARCHITECTURE, AND WHY IT IS *NOT* A TRANSFORMER
#  -------------------------------------------------------
#  Almost every modern network answers a question by storing surface statistics
#  and retrieving a weighted blend of them (attention over stored keys). Jabir's
#  whole science says the opposite: the surface (zahir, the "manifest" face) is
#  precisely the thing you must NOT trust. Every substance wears two faces — a
#  manifest one you can see and weigh, and a hidden one (batin) folded inside it
#  that does the real work. Gold is outwardly hot-and-moist but inwardly cold-
#  and-dry; lead is the mirror image. To *know* a thing is to compute its hidden
#  face from its manifest one. To *transform* a thing is to invert the two faces
#  under a strict law of conservation — you may redistribute the natures, but the
#  total quantity of "quality-stuff" is conserved, exactly as matter is conserved
#  in a sealed vessel. This is his ‘ilm al-mizan, the Science of the Balance.
#
#  Three primitives, each a doctrine made mechanical:
#
#    1. CONSERVED-SIMPLEX STATE.  Every representation is a probability
#       distribution over the K = 4 natures (hot / cold / wet / dry). Total
#       "quality mass" is exactly 1 and is conserved through every layer. There
#       are no free real-valued activations, only proportion. An alchemist, of
#       course, never runs a single balance — the laboratory holds many vessels
#       at once — so the engine keeps H such simplices in parallel (H "vessels").
#       Every vessel conserves mass independently; capacity comes from width, not
#       from abandoning the conservation law.
#
#    2. THE BALANCE OPERATOR (mass-conserving transport).  A transformation is a
#       column-stochastic matrix T (one per vessel) that *redistributes* nature-
#       mass without creating or destroying any. This replaces the linear layer /
#       attention block with a pair of scales that must always balance.
#
#    3. MANIFEST <-> HIDDEN INVERSION (zahir / batin).  The hidden register is the
#       *inverse* balance, T_inv = column_softmax(-M). Manifest and hidden are
#       transport-inverses of one another — a literal mechanisation of "gold's
#       inner face is the negation of its outer face."
#
#  A fourth doctrine enters as an inductive bias, not a layer:
#
#    4. THE 17-SERIES PRIOR.  Jabir held the perfected substance sits at the
#       canonical proportion 1 : 3 : 5 : 8 (these sum to 17, the number he said
#       "governs everything," mapped onto the 28 letters of the Arabic alphabet).
#       We encode this as a gentle prior pulling the *aggregate* balance of the
#       world toward [1,3,5,8]/17. Individual substances deviate freely, and it
#       is their measured deviation from the perfect balance that carries the
#       class signal. Intelligence, for Jabir, is the measurement of deviation
#       from balance.
#
#  The training task is deliberately Jabirian: each "substance" is generated by a
#  hidden recipe passed through a fixed mass-conserving manifestation transport,
#  then observed only through a noisy high-dimensional surface. The engine must
#  recover the hidden identity from the manifest face — the core cognitive act of
#  the corpus. The file closes with a *takwin* demo: "assembling a being to spec"
#  by driving a blank input, under gradient control, to a chosen target balance —
#  the artificial-generation goal of the Kitab al-Tajmi', reduced to its
#  computational skeleton, the made thing remaining subject to its maker.
#
#  Conventions shared across the book: pure NumPy, from scratch, no autograd; a
#  mandatory analytic-vs-finite-difference gradient check; a real training loop,
#  held-out evaluation, and self-tests that run on execution.
# =============================================================================

from __future__ import annotations
import numpy as np

RNG = np.random.default_rng(721)   # seeded with Jabir's traditional birth year

NATURES = ("hot", "cold", "wet", "dry")
K = len(NATURES)                    # K = 4 natures

CANONICAL = np.array([1.0, 3.0, 5.0, 8.0])   # the 17-series
CANONICAL = CANONICAL / CANONICAL.sum()       # normalised: the "perfect balance"


# -----------------------------------------------------------------------------
#  Numerically-stable primitives
# -----------------------------------------------------------------------------
def softmax_last(z: np.ndarray) -> np.ndarray:
    """Softmax over the LAST axis. Turns each nature-vector into a simplex point."""
    z = z - z.max(axis=-1, keepdims=True)
    e = np.exp(z)
    return e / e.sum(axis=-1, keepdims=True)


def col_softmax(M: np.ndarray) -> np.ndarray:
    """Column-wise softmax over axis=-2 for a stack of matrices (..., K, K).
    Each COLUMN sums to 1 -> column-stochastic -> a mass-conserving balance."""
    M = M - M.max(axis=-2, keepdims=True)
    e = np.exp(M)
    return e / e.sum(axis=-2, keepdims=True)


def kl(p: np.ndarray, q: np.ndarray, eps: float = 1e-12) -> float:
    p = np.clip(p, eps, 1.0); q = np.clip(q, eps, 1.0)
    return float(np.sum(p * (np.log(p) - np.log(q))))


# =============================================================================
#  THE MIZAN BALANCE ENGINE  (H parallel conserved vessels)
# =============================================================================
class MizanBalanceEngine:
    def __init__(self, d_in, n_classes, n_vessels=8, lam=0.05, scale=0.5):
        self.d_in = d_in
        self.C = n_classes
        self.H = n_vessels
        self.lam = lam
        H = n_vessels
        # Encoder: one direction-set per vessel -> H manifest simplices.
        self.W_enc = RNG.normal(0, scale, size=(H, K, d_in))
        self.b_enc = np.zeros((H, K))
        # One balance seed per vessel. T = col_softmax(M), T_inv = col_softmax(-M).
        self.M = RNG.normal(0, scale, size=(H, K, K))
        # Readout over the joined [manifest ; hidden] state of all vessels.
        self.W_out = RNG.normal(0, scale, size=(n_classes, 2 * H * K))
        self.b_out = np.zeros(n_classes)

    def get_params(self):
        return {"W_enc": self.W_enc, "b_enc": self.b_enc, "M": self.M,
                "W_out": self.W_out, "b_out": self.b_out}

    # ------------------------------------------------------------------ FORWARD
    def forward(self, X):
        N = X.shape[0]
        # 1) Encode raw surface -> H manifest simplices (N,H,K).
        z = np.einsum("hkd,nd->nhk", self.W_enc, X) + self.b_enc
        a = softmax_last(z)                                   # manifest natures
        # 2) THE BALANCE: redistribute mass per vessel (column-stochastic).
        T = col_softmax(self.M)                              # (H,K,K)
        mp = np.einsum("hkj,nhj->nhk", T, a)                 # manifest', mass=1
        # 3) INVERSION: hidden face = inverse balance of the manifest.
        T_inv = col_softmax(-self.M)                         # (H,K,K)
        b = np.einsum("hkj,nhj->nhk", T_inv, mp)             # hidden natures
        # 4) Join both faces of every vessel and read out.
        f = np.concatenate([mp.reshape(N, -1), b.reshape(N, -1)], axis=1)
        logits = f @ self.W_out.T + self.b_out
        yhat = softmax_last(logits)
        return dict(X=X, a=a, T=T, mp=mp, T_inv=T_inv, b=b, f=f,
                    logits=logits, yhat=yhat, N=N)

    def loss(self, X, y):
        c = self.forward(X)
        yhat, N = c["yhat"], c["N"]
        ce = -np.mean(np.log(yhat[np.arange(N), y] + 1e-12))
        a_mean = c["a"].mean(axis=(0, 1))                    # aggregate balance
        mizan_pen = kl(a_mean, CANONICAL)
        c.update(y=y, ce=ce, mizan_pen=mizan_pen)
        return ce + self.lam * mizan_pen, c

    # ----------------------------------------------------------------- BACKWARD
    def _dz_from_da(self, a, da):
        """Backprop through the per-vessel softmax over natures."""
        return a * (da - (da * a).sum(axis=-1, keepdims=True))

    def backward(self, c):
        X, a, T, mp, T_inv = c["X"], c["a"], c["T"], c["mp"], c["T_inv"]
        yhat, y, N, H = c["yhat"], c["y"], c["N"], self.H

        Y = np.zeros_like(yhat); Y[np.arange(N), y] = 1.0
        dlogits = (yhat - Y) / N
        dW_out = dlogits.T @ c["f"]
        db_out = dlogits.sum(axis=0)
        df = dlogits @ self.W_out                            # (N, 2HK)
        dmp = df[:, :H * K].reshape(N, H, K).copy()
        db = df[:, H * K:].reshape(N, H, K).copy()

        # hidden inversion:  b = T_inv @ mp  (per vessel)
        dmp += np.einsum("nhk,hkj->nhj", db, T_inv)
        dT_inv = np.einsum("nhk,nhj->hkj", db, mp)

        # the balance:  mp = T @ a  (per vessel)
        da = np.einsum("nhk,hkj->nhj", dmp, T)
        dT = np.einsum("nhk,nhj->hkj", dmp, a)

        # 17-series prior on the aggregate manifest
        a_mean = a.mean(axis=(0, 1))
        dmizan = np.log(np.clip(a_mean, 1e-12, 1.0)) - np.log(CANONICAL) + 1.0
        da += self.lam * dmizan[None, None, :] / (N * H)

        dz = self._dz_from_da(a, da)
        dW_enc = np.einsum("nhk,nd->hkd", dz, X)
        db_enc = dz.sum(axis=0)

        # M generates BOTH T and T_inv -> accumulate both paths, per vessel.
        sT = (dT * T).sum(axis=-2, keepdims=True)
        dM_from_T = T * (dT - sT)
        sU = (dT_inv * T_inv).sum(axis=-2, keepdims=True)
        dU = T_inv * (dT_inv - sU)
        dM = dM_from_T - dU

        return {"W_enc": dW_enc, "b_enc": db_enc, "M": dM,
                "W_out": dW_out, "b_out": db_out}

    def grad_input(self, X, y_target):
        _, c = self.loss(X, y_target)
        a, T, T_inv = c["a"], c["T"], c["T_inv"]
        yhat, N, H = c["yhat"], c["N"], self.H
        Y = np.zeros_like(yhat); Y[np.arange(N), y_target] = 1.0
        dlogits = (yhat - Y) / N
        df = dlogits @ self.W_out
        dmp = df[:, :H * K].reshape(N, H, K).copy()
        db = df[:, H * K:].reshape(N, H, K).copy()
        dmp += np.einsum("nhk,hkj->nhj", db, T_inv)
        da = np.einsum("nhk,hkj->nhj", dmp, T)
        a_mean = a.mean(axis=(0, 1))
        dmizan = np.log(np.clip(a_mean, 1e-12, 1.0)) - np.log(CANONICAL) + 1.0
        da += self.lam * dmizan[None, None, :] / (N * H)
        dz = self._dz_from_da(a, da)
        return np.einsum("nhk,hkd->nd", dz, self.W_enc)

    def predict(self, X):
        return self.forward(X)["yhat"].argmax(axis=1)

    def natures_of(self, X):
        c = self.forward(X)
        return c["mp"], c["b"]


# =============================================================================
#  GRADIENT CHECK  (mandatory)
# =============================================================================
def gradient_check(model, X, y, eps=1e-6):
    _, c = model.loss(X, y)
    analytic = model.backward(c)
    worst, report = 0.0, []
    for name, P in model.get_params().items():
        g_num = np.zeros_like(P)
        it = np.nditer(P, flags=["multi_index"])
        while not it.finished:
            idx = it.multi_index
            orig = P[idx]
            P[idx] = orig + eps; lp, _ = model.loss(X, y)
            P[idx] = orig - eps; lm, _ = model.loss(X, y)
            P[idx] = orig
            g_num[idx] = (lp - lm) / (2 * eps)
            it.iternext()
        num = np.linalg.norm(analytic[name] - g_num)
        den = np.linalg.norm(analytic[name]) + np.linalg.norm(g_num) + 1e-12
        rel = num / den
        worst = max(worst, rel); report.append((name, rel))
    return worst, report


# =============================================================================
#  SYNTHETIC "SUBSTANCES" — a Jabirian generative process
# =============================================================================
def make_world(n_classes=4, d_in=16, seed=1):
    """Fix ONE world: its manifestation transport, its surface embedding, and its
    hidden class recipes. Train and test are then sampled from the SAME world."""
    rng = np.random.default_rng(seed)
    T_true = col_softmax(rng.normal(0, 1.0, size=(K, K)))   # the world's balance
    R = rng.normal(0, 1.0, size=(d_in, K))                  # manifest -> surface
    # Distinct hidden recipes: each class is dominated by a different nature,
    # so the classes occupy well-separated regions of the simplex.
    base = np.full((n_classes, K), 0.1)
    for c in range(n_classes):
        base[c, c % K] += 0.9
    base = base / base.sum(axis=1, keepdims=True)
    return dict(T_true=T_true, R=R, base=base, d_in=d_in, n_classes=n_classes)


def sample_substances(world, n_per_class, noise=0.10, seed=0, mean=None, std=None):
    """Draw substances from a fixed world. Optionally reuse train-set feature
    statistics (mean/std) so the test set is standardised the same way."""
    rng = np.random.default_rng(seed)
    T_true, R, base = world["T_true"], world["R"], world["base"]
    X, y = [], []
    for c in range(world["n_classes"]):
        for _ in range(n_per_class):
            h = rng.dirichlet(base[c] * 30.0 + 0.5)   # hidden recipe (on simplex)
            manifest = T_true @ h                     # manifestation (mass kept)
            x = R @ manifest + noise * rng.normal(size=world["d_in"])
            X.append(x); y.append(c)
    X = np.asarray(X); y = np.asarray(y)
    if mean is None:
        mean, std = X.mean(0), X.std(0) + 1e-8
    X = (X - mean) / std
    perm = rng.permutation(len(y))
    return X[perm], y[perm], mean, std


# =============================================================================
#  TRAINING LOOP  (full-batch Adam, from scratch)
# =============================================================================
def train(model, Xtr, ytr, Xte, yte, epochs=600, lr=0.03, weight_decay=2e-4):
    params = model.get_params()
    m = {k: np.zeros_like(v) for k, v in params.items()}
    v = {k: np.zeros_like(v) for k, v in params.items()}
    b1, b2, eps = 0.9, 0.999, 1e-8
    history = []
    for t in range(1, epochs + 1):
        loss, c = model.loss(Xtr, ytr)
        g = model.backward(c)
        for k in params:
            m[k] = b1 * m[k] + (1 - b1) * g[k]
            v[k] = b2 * v[k] + (1 - b2) * g[k] ** 2
            mhat = m[k] / (1 - b1 ** t); vhat = v[k] / (1 - b2 ** t)
            step = lr * mhat / (np.sqrt(vhat) + eps)
            # decoupled weight decay on weight matrices (not the biases)
            if k in ("W_enc", "W_out", "M"):
                step += lr * weight_decay * params[k]
            params[k] -= step
        if t % 75 == 0 or t == 1:
            tr = (model.predict(Xtr) == ytr).mean()
            te = (model.predict(Xte) == yte).mean()
            history.append((t, loss, tr, te))
    return history


# =============================================================================
#  TAKWIN — "assemble a being to a target balance under the creator's control"
# =============================================================================
def takwin(model, d_in, target_class, steps=400, lr=0.3):
    x = 0.01 * RNG.normal(size=(1, d_in))
    tgt = np.array([target_class])
    for _ in range(steps):
        x = x - lr * model.grad_input(x, tgt)
    pred = int(model.predict(x)[0])
    prob = float(model.forward(x)["yhat"][0, target_class])
    mp, hidden = model.natures_of(x)
    return pred, prob, mp[0].mean(0), hidden[0].mean(0)   # mean over vessels


# =============================================================================
#  MAIN
# =============================================================================
def main():
    np.set_printoptions(precision=4, suppress=True)
    print("=" * 74)
    print("  THE MIZAN BALANCE ENGINE  —  Jabir ibn Hayyan (c.721–c.815)")
    print("  conserved-simplex vessels · balance transport · manifest/hidden "
          "inversion")
    print("=" * 74)
    print(f"  Natures (K)          : {NATURES}")
    print(f"  Canonical 17-series  : 1:3:5:8  ->  {CANONICAL}")

    d_in, n_classes, H = 16, 4, 6
    world = make_world(n_classes, d_in, seed=1)
    Xtr, ytr, mu, sd = sample_substances(world, 200, noise=0.08, seed=11)
    Xte, yte, _, _   = sample_substances(world, 60,  noise=0.08, seed=22,
                                         mean=mu, std=sd)
    print(f"  Vessels (H)          : {H}")
    print(f"  Train substances     : {Xtr.shape[0]}   Test: {Xte.shape[0]}")
    print()

    model = MizanBalanceEngine(d_in, n_classes, n_vessels=H, lam=0.05)

    # SELF-TEST 1: mass conservation
    c = model.forward(Xtr[:16])
    for name in ("a", "mp", "b"):
        masses = c[name].sum(axis=-1)
        ok = np.allclose(masses, 1.0, atol=1e-10)
        print(f"  [mass] {name:>2}: every vessel sums to 1 -> {ok} "
              f"(min {masses.min():.10f}, max {masses.max():.10f})")
    print()

    # SELF-TEST 2: gradient check (mandatory)
    worst, report = gradient_check(model, Xtr[:6], ytr[:6], eps=1e-6)
    print("  [gradient check] analytic vs central finite differences:")
    for name, rel in report:
        print(f"      {name:<6} rel-err = {rel:.3e}")
    print(f"  [gradient check] worst rel-err = {worst:.3e}  ->  "
          f"{'PASS' if worst < 1e-6 else 'FAIL'}")
    print()

    # TRAIN
    print("  [training] full-batch Adam on the balance engine")
    hist = train(model, Xtr, ytr, Xte, yte, epochs=600, lr=0.03)
    print(f"      {'epoch':>6} {'loss':>10} {'train_acc':>10} {'test_acc':>10}")
    for (t, loss, tr, te) in hist:
        print(f"      {t:>6} {loss:>10.4f} {tr:>10.3f} {te:>10.3f}")
    final_te = (model.predict(Xte) == yte).mean()
    print(f"  [training] final held-out accuracy = {final_te:.3f}")
    print()

    # SELF-TEST 3: aggregate balance moved toward the 17-series
    a_mean = model.forward(Xtr)["a"].mean(axis=(0, 1))
    print("  [balance prior] aggregate manifest natures vs canonical:")
    for n, val, can in zip(NATURES, a_mean, CANONICAL):
        print(f"      {n:>4}: {val:6.3f}   (canonical {can:5.3f})")
    print(f"      KL(aggregate || 17-series) = {kl(a_mean, CANONICAL):.4f}")
    print()

    # SELF-TEST 4: takwin
    print("  [takwin] driving a blank surface to each target under control:")
    hits = 0
    for tc in range(n_classes):
        pred, prob, mp, hidden = takwin(model, d_in, tc)
        hit = pred == tc; hits += hit
        print(f"      target {tc}: resolved->{pred}  p={prob:5.3f}  "
              f"{'OK' if hit else 'miss'}  | manifest~{mp}  hidden~{hidden}")
    print(f"  [takwin] {hits}/{n_classes} assembled beings matched their spec.")
    print()
    print("=" * 74)
    print("  All self-tests complete.")
    print("=" * 74)


if __name__ == "__main__":
    main()
