"""
================================================================================
chapter_0036_anaximenes_of_miletus_-526.py  --  The Pneuma Continuum Network
A from-scratch (pure NumPy) neural architecture after ANAXIMENES OF MILETUS
(c. 586/585 - c. 526/525 BCE), the third Milesian philosopher.
# Part Encyclopedia of Lost Minds: Echoes on AI By David Vivancos https://www.vivancos.com/
# How History's Greatest Thinkers Would Have Thought About AGI  https://lostmindsai.com
# Tome 2 Minds 21 - 40 Available on Amazon https://www.amazon.com/dp/B0H6QCQ9M7
# Resume and Interactive Demos at https://artificiology.com/
# Author: David Vivancos · Chapter 0036 · Anaximenes of Miletus
================================================================================

WHY THIS ARCHITECTURE, AND WHY IT IS *NOT* A TRANSFORMER
--------------------------------------------------------
Anaximenes' one genuinely original cognitive move -- the move that separates him
from Thales (water) and his teacher Anaximander (the boundless apeiron) -- was
NOT simply "pick a different stuff for the world to be made of." It was deeper:

    He reduced QUALITATIVE difference to QUANTITATIVE difference.

For Anaximenes the world is ONE substance, air (aer), and the bewildering variety
of things -- fire, wind, cloud, water, earth, stone -- are not different *kinds*.
They are the *same* substance at different *densities*. A single scalar control
parameter (density, tuned by the twin processes of rarefaction / manosis and
condensation / pyknosis) generates the entire taxonomy of nature. Theophrastus
(via Simplicius) and Hippolytus both report this, and Anaximenes even gave an
operational, falsifiable test of it (DK13B1): blow on your hand with the mouth
relaxed and the breath is warm (rarefied air); blow through pursed lips and it is
cold (condensed air). Density is something you can *feel* and *control*.

And then the masterstroke (the soul fragment, DK13B2): the SAME substance, in its
rarest and most refined state, is *soul* and *mind*. "Just as our soul, being air,
holds us together, so breath and air surround the whole cosmos." Mind is not a
different thing from world-stuff. It is world-stuff at its rarest density.

This architecture encodes exactly that thesis, and nothing generic:

  1. MONISM / ONE SUBSTANCE.  The whole network's depth is generated by a *single
     shared transformation operator* W (condensation) and W_up (rarefaction),
     applied repeatedly. There is no per-layer zoo of unrelated weight matrices.
     The same operator, re-applied, is the "same air" appearing again and again.

  2. ONE CONTROL PARAMETER = DENSITY.  A single learnable scalar `rho` -- the
     density of the pneuma -- governs the ENTIRE continuum. From it we derive
     s = sigmoid(rho). Condensation multiplies pre-activations by s (concentrate,
     s<1); rarefaction multiplies by (2 - s) (expand, >1). One number tunes the
     whole ladder. This is Anaximenes' "one principle explains all change," made
     mechanical and -- crucially -- differentiable (we gradient-check d loss/d rho).

  3. CONDENSATION then RAREFACTION.  The forward pass walks DOWN the density
     ladder (encode = condense raw input into the refined "soul" latent z), then
     back UP (decode = rarefy the soul back out into the world). z is literally
     "the rarest, most refined air" -- the mind.

  4. BREATH.  Inference/training has a respiratory rhythm: an inhale phase biases
     toward rarefaction, an exhale phase toward condensation, by nudging the
     density schedule. (See `breathe` and the optional breath schedule in train.)

The model is a real, trainable autoencoder over a *single* shared-substance core.
It includes the MANDATORY pieces of this corpus:
  * a finite-difference gradient check that PASSES for every parameter, incl. rho;
  * a real training loop whose reconstruction loss demonstrably decreases;
  * deterministic self-tests (assertions) that run on import-as-main.

References (verified):
  - Theophrastus (via Simplicius), and Hippolytus, Refutatio I.7, on condensation
    and rarefaction of air -- in Kirk, Raven & Schofield, The Presocratic
    Philosophers, 2nd ed. (Cambridge UP, 1983), ch. 4.
  - Daniel W. Graham, Explaining the Cosmos: The Ionian Tradition of Scientific
    Philosophy (Princeton UP, 2006).
  - DK13B1 (the breath / pursed-lips experiment) and DK13B2 (soul-as-air), in
    Diels-Kranz; see also Laks & Most, Early Greek Philosophy vol. III (Loeb, 2016).
  - Stanford Encyclopedia of Philosophy, "Presocratic Philosophy."
================================================================================
"""

from __future__ import annotations
import numpy as np


# =============================================================================
# SECTION 1 -- THE PNEUMA: one substance, one density parameter
# =============================================================================
def sigmoid(x):
    """Stable logistic. Maps the raw density rho -> s in (0, 1)."""
    return np.where(x >= 0, 1.0 / (1.0 + np.exp(-x)),
                    np.exp(x) / (1.0 + np.exp(x)))


class PneumaContinuumNetwork:
    """
    A monist autoencoder. The world (input x) is condensed, step by step using the
    SAME operator W, down to the refined soul-latent z; then rarefied, step by step
    using the SAME operator W_up, back out to a reconstruction. A single density
    scalar rho governs the strength of every step on the ladder.

    Shapes
    ------
      d_in : dimensionality of the world (input/output)
      H    : dimensionality of the air-continuum (hidden state)
      S    : number of density steps each way (depth of the ladder)
    """

    def __init__(self, d_in, H, S=3, seed=0):
        rng = np.random.default_rng(seed)
        self.d_in, self.H, self.S = d_in, H, S

        # --- Parameters ---------------------------------------------------
        # Entry into the continuum: project the world into "air".
        scale_in = 1.0 / np.sqrt(d_in)
        self.Win = rng.normal(0, scale_in, size=(H, d_in))
        self.bin = np.zeros(H)

        # The ONE shared condensation operator (re-applied S times).
        scale_h = 1.0 / np.sqrt(H)
        self.W = rng.normal(0, scale_h, size=(H, H))
        self.b = np.zeros(H)

        # The ONE shared rarefaction operator (re-applied S times).
        self.Wup = rng.normal(0, scale_h, size=(H, H))
        self.bup = np.zeros(H)

        # Exit the continuum: rarefy the refined air back into the world.
        self.Wout = rng.normal(0, scale_h, size=(d_in, H))
        self.bout = np.zeros(d_in)

        # THE ARCHE: a single density scalar. s = sigmoid(rho).
        # Initialised so s ~ 0.5 (balanced air, neither fire nor stone).
        self.rho = np.array(0.0)

        # Breath state (purely a rhythmic schedule modifier; see breathe()).
        self._breath_bias = 0.0

    # -- parameter bookkeeping (used by the gradient checker) --------------
    def params(self):
        return {
            "Win": self.Win, "bin": self.bin,
            "W": self.W, "b": self.b,
            "Wup": self.Wup, "bup": self.bup,
            "Wout": self.Wout, "bout": self.bout,
            "rho": self.rho,
        }

    def set_param(self, name, value):
        setattr(self, name, value)

    # =====================================================================
    # SECTION 2 -- FORWARD: condense to the soul, rarefy back to the world
    # =====================================================================
    def forward(self, X, cache=True):
        """
        X : (N, d_in) batch of worlds.
        Returns (R, loss, cache_dict). Loss is mean-squared reconstruction error.
        """
        N = X.shape[0]
        s = float(sigmoid(self.rho)) + self._breath_bias
        s = min(max(s, 1e-3), 1 - 1e-3)          # keep density physical
        c = s                                     # condensation factor  (<1: concentrate)
        r = 2.0 - s                               # rarefaction factor   (>1: expand)

        # Enter the continuum.
        P0 = X @ self.Win.T + self.bin
        H0 = np.tanh(P0)

        # Walk DOWN the ladder: condensation (shared W).
        Hs = [H0]
        cond_A = []
        h = H0
        for _ in range(self.S):
            A = h @ self.W.T + self.b
            h = np.tanh(c * A)
            cond_A.append(A)
            Hs.append(h)
        Z = h                                     # the soul: rarest, most refined air

        # Walk back UP the ladder: rarefaction (shared W_up).
        Gs = [Z]
        rare_A = []
        g = Z
        for _ in range(self.S):
            A = g @ self.Wup.T + self.bup
            g = np.tanh(r * A)
            rare_A.append(A)
            Gs.append(g)
        G = g

        # Exit the continuum back into the world.
        R = G @ self.Wout.T + self.bout
        diff = R - X
        loss = float(np.mean(diff ** 2))

        cd = None
        if cache:
            cd = dict(X=X, N=N, s=s, c=c, r=r, P0=P0, H0=H0, Hs=Hs, cond_A=cond_A,
                      Z=Z, Gs=Gs, rare_A=rare_A, G=G, R=R, diff=diff)
        return R, loss, cd

    # =====================================================================
    # SECTION 3 -- BACKWARD: manual gradients (BPTT through the shared ops)
    # =====================================================================
    def backward(self, cd):
        """Analytic gradients of the MSE loss w.r.t. every parameter, incl. rho."""
        X, N, s, c, r = cd["X"], cd["N"], cd["s"], cd["c"], cd["r"]
        Hs, cond_A = cd["Hs"], cd["cond_A"]
        Z, Gs, rare_A, G = cd["Z"], cd["Gs"], cd["rare_A"], cd["G"]
        D = self.d_in
        scale = 2.0 / (N * D)

        dR = scale * cd["diff"]                    # (N, d_in)
        dWout = dR.T @ G
        dbout = dR.sum(0)
        dG = dR @ self.Wout                        # (N, H)

        # ---- rarefaction backward (reverse), shared Wup -------------------
        dWup = np.zeros_like(self.Wup)
        dbup = np.zeros_like(self.bup)
        dr_acc = 0.0                               # accumulates d loss / d r
        cur = dG
        for k in range(self.S, 0, -1):
            g_k = Gs[k]                            # tanh output of this step
            A_k = rare_A[k - 1]                    # pre-(scale) activation
            dPu = cur * (1.0 - g_k ** 2)           # through tanh; pre = r * A
            dA = r * dPu
            dr_acc += float(np.sum(dPu * A_k))     # d/dr of (r*A)
            dWup += dA.T @ Gs[k - 1]
            dbup += dA.sum(0)
            cur = dA @ self.Wup                    # grad wrt previous g
        dZ = cur

        # ---- condensation backward (reverse), shared W --------------------
        dW = np.zeros_like(self.W)
        db = np.zeros_like(self.b)
        dc_acc = 0.0                               # accumulates d loss / d c
        cur = dZ
        for k in range(self.S, 0, -1):
            h_k = Hs[k]
            A_k = cond_A[k - 1]
            dPk = cur * (1.0 - h_k ** 2)           # through tanh; pre = c * A
            dA = c * dPk
            dc_acc += float(np.sum(dPk * A_k))     # d/dc of (c*A)
            dW += dA.T @ Hs[k - 1]
            db += dA.sum(0)
            cur = dA @ self.W
        dH0 = cur

        # ---- entry layer --------------------------------------------------
        dP0 = dH0 * (1.0 - cd["H0"] ** 2)
        dWin = dP0.T @ X
        dbin = dP0.sum(0)

        # ---- THE ARCHE: gradient w.r.t. the single density scalar rho -----
        # c = s, r = 2 - s, s = sigmoid(rho) -> ds/drho = s*(1-s)
        ds = s * (1.0 - s)
        # dc/drho = ds ; dr/drho = -ds
        drho = ds * (dc_acc - dr_acc)
        drho = np.array(float(drho))

        return {
            "Win": dWin, "bin": dbin, "W": dW, "b": db,
            "Wup": dWup, "bup": dbup, "Wout": dWout, "bout": dbout,
            "rho": drho,
        }

    # =====================================================================
    # SECTION 4 -- BREATH: a respiratory rhythm over the density schedule
    # =====================================================================
    def breathe(self, phase):
        """
        Nudge the effective density with a breath rhythm.
        phase in [0, 2*pi). Inhale (phase<pi) leans rarefied (lower density);
        exhale leans condensed (higher density). Amplitude is deliberately small
        so it perturbs, not destroys, the learned density. Returns current bias.
        """
        self._breath_bias = -0.04 * np.sin(phase)   # negative sin: inhale -> rarefy
        return self._breath_bias

    def rest(self):
        """Hold the breath: revert to the learned equilibrium density."""
        self._breath_bias = 0.0


# =============================================================================
# SECTION 5 -- TRAINING (vanilla SGD with momentum; one real loop)
# =============================================================================
def train(model, X, epochs=400, lr=0.05, momentum=0.9, breath=True, verbose=True):
    """A real training loop. Minimises reconstruction MSE. Returns loss history."""
    vel = {k: np.zeros_like(v) for k, v in model.params().items()}
    history = []
    for ep in range(epochs):
        if breath:
            model.breathe(2 * np.pi * (ep % 16) / 16.0)   # slow breath cycle
        _, loss, cd = model.forward(X)
        grads = model.backward(cd)
        for name, g in grads.items():
            vel[name] = momentum * vel[name] - lr * g
            model.set_param(name, model.params()[name] + vel[name])
        model.rest()
        history.append(loss)
        if verbose and (ep % 50 == 0 or ep == epochs - 1):
            s = float(sigmoid(model.rho))
            print(f"  epoch {ep:4d}   loss {loss:.6f}   density s={s:.4f}")
    return history


# =============================================================================
# SECTION 6 -- A STRUCTURED SYNTHETIC WORLD (low-rank => compressible)
# =============================================================================
def make_world(N=128, d_in=12, rank=3, seed=7):
    """
    A low-rank dataset: each 'world' is a noisy mixture of `rank` latent factors.
    Because it is genuinely low-rank, a good condenser can capture it in the
    soul-latent and rarefy it back -- exactly Anaximenes' claim that the many
    reduce to the few. Returns X (N, d_in).
    """
    rng = np.random.default_rng(seed)
    basis = rng.normal(0, 1, size=(rank, d_in))         # the few hidden factors
    coeffs = rng.normal(0, 1, size=(N, rank))           # how much of each, per world
    X = coeffs @ basis
    X += 0.05 * rng.normal(0, 1, size=X.shape)          # a little chaos
    # normalise per-feature so MSE is comparable across dims
    X = (X - X.mean(0)) / (X.std(0) + 1e-8)
    return X


# =============================================================================
# SECTION 7 -- MANDATORY FINITE-DIFFERENCE GRADIENT CHECK
# =============================================================================
def gradient_check(model, X, eps=1e-6, tol=1e-5):
    """
    Compares analytic gradients to central finite differences for EVERY parameter,
    including the single density scalar rho. Returns (ok, max_rel_err, report).
    """
    # turn off breath bias so forward is a clean function of the params
    model.rest()
    _, _, cd = model.forward(X)
    analytic = model.backward(cd)

    max_rel = 0.0
    report = []
    for name, P in model.params().items():
        P = np.atleast_1d(P).astype(float)
        flat = P.ravel()
        num = np.zeros_like(flat)
        for i in range(flat.size):
            orig = flat[i]
            flat[i] = orig + eps
            model.set_param(name, P.reshape(model.params()[name].shape))
            _, lp, _ = model.forward(X, cache=False)
            flat[i] = orig - eps
            model.set_param(name, P.reshape(model.params()[name].shape))
            _, lm, _ = model.forward(X, cache=False)
            num[i] = (lp - lm) / (2 * eps)
            flat[i] = orig
        model.set_param(name, P.reshape(model.params()[name].shape))

        ana = np.atleast_1d(analytic[name]).ravel()
        denom = np.maximum(1e-8, np.abs(ana) + np.abs(num))
        rel = np.max(np.abs(ana - num) / denom)
        max_rel = max(max_rel, rel)
        report.append((name, rel))
    ok = max_rel < tol
    return ok, max_rel, report


# =============================================================================
# SECTION 8 -- SELF-TESTS + DEMO  (runs when executed directly)
# =============================================================================
def _run_self_tests():
    print("=" * 72)
    print("PNEUMA CONTINUUM NETWORK  --  self-tests (Anaximenes of Miletus)")
    print("=" * 72)

    # --- determinism -------------------------------------------------------
    a = PneumaContinuumNetwork(d_in=12, H=10, S=3, seed=0)
    b = PneumaContinuumNetwork(d_in=12, H=10, S=3, seed=0)
    Xtiny = make_world(N=16, d_in=12, rank=3, seed=1)
    _, la, _ = a.forward(Xtiny, cache=False)
    _, lb, _ = b.forward(Xtiny, cache=False)
    assert abs(la - lb) < 1e-12, "Same seed must give identical loss"
    print(f"[1] determinism .......... OK   (loss={la:.6f})")

    # --- gradient check (the mandatory one) --------------------------------
    gc_model = PneumaContinuumNetwork(d_in=6, H=7, S=3, seed=3)
    Xgc = make_world(N=10, d_in=6, rank=2, seed=4)
    ok, max_rel, report = gradient_check(gc_model, Xgc)
    print(f"[2] gradient check ....... {'OK' if ok else 'FAIL'}   "
          f"max relative error = {max_rel:.2e}")
    for name, rel in report:
        print(f"        d{name:<5s} rel_err = {rel:.2e}")
    assert ok, "Finite-difference gradient check FAILED"

    # --- training reduces loss --------------------------------------------
    print("[3] training loop:")
    model = PneumaContinuumNetwork(d_in=12, H=10, S=3, seed=0)
    X = make_world(N=128, d_in=12, rank=3, seed=7)
    _, loss0, _ = model.forward(X, cache=False)
    hist = train(model, X, epochs=400, lr=0.05, momentum=0.9, breath=True)
    loss1 = hist[-1]
    print(f"    initial loss {loss0:.6f}  ->  final loss {loss1:.6f}  "
          f"({100*(1-loss1/loss0):.1f}% reduction)")
    assert loss1 < 0.5 * loss0, "Training must at least halve the loss"
    print("    training reduces loss .... OK")

    # --- the soul latent actually compresses ------------------------------
    _, _, cd = model.forward(X)
    Z = cd["Z"]
    print(f"[4] soul-latent z shape {Z.shape}  (the rarest, most refined air)")
    # reconstruction quality on the structured world
    R, final_loss, _ = model.forward(X, cache=False)
    var_explained = 1.0 - np.var(R - X) / np.var(X)
    print(f"    reconstruction variance-explained = {var_explained:.3f}")
    assert var_explained > 0.5, "Condenser should capture the low-rank structure"

    # --- breath visibly modulates density ---------------------------------
    print("[5] breath rhythm modulates effective density:")
    base = float(sigmoid(model.rho))
    densities = []
    for k in range(8):
        model.breathe(2 * np.pi * k / 8.0)
        s = min(max(base + model._breath_bias, 1e-3), 1 - 1e-3)
        densities.append(s)
    model.rest()
    print("    inhale->rarefy / exhale->condense, s over one breath:")
    print("    " + "  ".join(f"{d:.3f}" for d in densities))
    assert max(densities) - min(densities) > 1e-3, "Breath must move the density"

    print("=" * 72)
    print("ALL SELF-TESTS PASSED.")
    print("One substance (air). One operator, re-applied. One scalar (density)")
    print("governing the whole continuum. The soul is air at its rarest.")
    print("=" * 72)
    return model


if __name__ == "__main__":
    _run_self_tests()
